### ISSUE TITLE
Ability to zoom in and pan the chart

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/node-red-dashboard#10]
## Description

Users require a simple and efficient way to visualize time series data. By providing out-of-the-box, good-looking time series charts, we can enhance the user experience and enable users to better analyze and understand their data. These charts should be easily customizable and require minimal configuration to get started.

## Examples
- [Grafana](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/time-series/)
- https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/xychart

### Have you provided an initial effort estimate for this issue?

None

**Comment by rcarmo** [comment]
…with the ability to zoom in and pan the chart, and an easier way to toggle visibility of multiple time series than the current version.

**Comment by MarianRaphael** [comment]
FYI - @joepavitt

**Comment by joepavitt** [comment]
> an easier way to toggle visibility of multiple time series than the current version.

just checking, this would be the idea of sending in a `msg.<something-here>` to the chart node that could control that visibility?

**Comment by rcarmo** [comment]
No, I meant purely from a UX perspective. Limiting series views in the chart node can be done easily enough by just omitting them from the rendered dataset, although I suppose that what you suggest would also be useful.

Right now, the biggest gripes I (personally) have with the current dashboard are that it is really hard to interact with complex charts as a user. It's geared towards very simple, almost completely passive dashboards and efforts essentially zero abilities to explore data beyond a few hundred datapoints as a user.

Everything else (data model, flow-side development, and especially the layout integration inside Node-RED, with the dashboard layout previews) work just fine. I get that we need to get rid of Angular 1.x and revamp the development lifecycle, but if that doesn't afford a better exploration and interactivity UX (which is 90% of the use for dashboards), folk like me will stick to embedding D3.js and Vega :)

**Comment by joepavitt** [comment]
Great feedback @rcarmo appreciate it. We are still _very_ early on at the moment, just re-building out existing functionality in Dashboard 2.0 found in the existing Dashboard, but this will absolutely be a priority for us. Thanks

**Comment by joepavitt** [comment]
There is chartjs plugin that may handle _most_ of this for us: https://www.chartjs.org/chartjs-plugin-zoom/

We'll likely need to add the "reset" option somewhere so that users can easily restore the default state, but it does provide the desired interaction.

**Comment by MarianRaphael** [comment]
Tracked in: https://github.com/FlowFuse/node-red-dashboard/issues/65
