### ISSUE TITLE
Variable `--layout-columns` not defined for `Fixed` Layout

### ISSUE THREAD

**Issue by arturv2000** [FlowFuse/node-red-dashboard#1003]
### Current Behavior

Variable `--layout-columns` is not defined for `fixed` page layout, which leads to behaviour such as described in forum https://discourse.nodered.org/t/dashboard-2-v1-12-0-fixed-layout-broken/88821

Apparently, this variable is unknow for css class `nrdb-layout-group--grid`.

Adding `--layout-columns: 36;` to the class seems to solve the issue, no ideia if just this change is "enough"

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
This is likely the case for https://github.com/FlowFuse/node-red-dashboard/issues/1006 too
