### ISSUE TITLE
dynamic Grafana plugin in iframe did not work

### ISSUE THREAD

**Issue by martin2day2** [FlowFuse/node-red-dashboard#1005]
### Description

Hello,

i have use Dashboard 1 befor and switched to Dashboard 2.0.
Now i setup dashboard 2.0 as befor.
I will switch in a dropdown list between diffrent times to setup the responce from my grafana. This work fine in Dashboard 1.0.

Now in 2.0 i did not get this setup to run. In the first Step i setup only an iframe or an template:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/111582339/5c641dcd-8bd5-47fa-8c84-5a0f3b41eab9)

```html
<div style="width: 100%; height: 100%;">
    <iframe src="http://xxx/xxx?orgId=1&refresh=1s&theme=dark&from=now-1d&to=now&panelId=1" style="border: none; width: 100%; height: 100%;"></iframe>
</div>
```

This work fine. If i write the url whis a function in msg.payload, than i can not see the chart in the i frame or in the template.
Than i see the firt screen of my nodered in the iframe or in the template.
![image](https://github.com/FlowFuse/node-red-dashboard/assets/111582339/239730bf-8e2b-4e48-ae82-960560febe71)

I replace the URL with {{payload}} or {{msg.payload}}.
What did i wrong?

Have a nice day

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Couple of options here:

- There exists a dedicated `iframe` node you may want to use for Dashboard 2.0: https://flows.nodered.org/node/@flowfuse/node-red-dashboard-2-ui-iframe - this will save you a lot of manual coding.
- If you do want to stick with `ui-template` approach, then I'm guessing you're injecting `msg.payload` using `{{ }}` inside the `src` attribute. Dashboard 2.0 is built on VueJS, not Angular, so the syntax is slightly different and explained in our docs [here](https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#working-with-variables).

If you do stick with the `ui-template` approach, in your specific case, you'd want:

```html
<iframe :src="msg.payload" style="border: none; width: 100%; height: 100%;"></iframe>
```

**Comment by joepavitt** [comment]
@martin2day2 if you're able to confirm that resolve the issue, that'd be great, then I can close this out

**Comment by martin2day2** [comment]
Yes, problem solve. Thank you very much for quick help!
