### ISSUE TITLE
ui_template scope does not clean up on configuration change.

### ISSUE THREAD

**Issue by hotNipi** [FlowFuse/node-red-dashboard#1038]
### Current Behavior

User wants to make a template for CSS 

1 Drag in the ui_template (default scope "Widget (Group-scoped)")
2 Write or copy/paste the content into
3 Forget to change the template type to "CSS (All Pages)" 
4 Deploy
5 Change the template type to "CSS (All Pages)"
6 Deploy

Result:
- there's no errors in console or any other indicators that something went wrong. 
- the CSS is not applied to the document head, user cant see any of desired changes
- user can not use this template anymore for CSS (group and page properties are not removed)

Debug panels comparing broken ad correct ui_template for CSS
The broken ui_template "page-back" has values for page and group.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/35291460/7238952b-995c-4d3c-ba53-308a173e6621)

### Expected Behavior

Changing the scope should be possible in all ways.

### Steps To Reproduce

Steps to reproduce described above

Workaround:
Make new ui_template but pay attention to not deploy for wrong scope

1 Drag in the ui_template (and give it a name)
2 Change the template type to "CSS (All Pages)"
3 Write or copy/paste the content into
4 Deploy

### Environment

- Dashboard version: v1.12.2
- Node-RED version:v4.0.0
- Node.js version:v20.14.0
- npm version:
- Platform/OS: Windows 10
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Can see the problem:

https://github.com/FlowFuse/node-red-dashboard/blob/b15c2193116df668407498749f87689a511b61ff/nodes/widgets/ui_template.js#L12-L20

I don't account for the CSS use cases here to clear the unnecessary `group` and `page` variables.

**Comment by arturv2000** [comment]
@joepavitt Noticed that the template does not generate any error if no (page/UI) selected, only gives error when no group is selected. Should it give some kind of error? Should open a separate issue?

**Comment by joepavitt** [comment]
Yeah, I noticed that too, issue would be great. Thanks @arturv2000
