### ISSUE TITLE
Proposal: CSS quick&small fixes to make whole site more pleasant

### ISSUE THREAD

**Issue by hotNipi** [FlowFuse/node-red-dashboard#1040]
### Description

Small CSS tweaks to adjust widgets appearance.

```
/* to make input type widgets repect row heights */
.nrdb-app .v-input--density-default {
    --v-input-control-height: 48px;
}
/* to fix the oval shape of press features for custom icon in switch widget */
.nrdb-switch button{
    aspect-ratio: 1;
}
/* to aligne slider perfectly to horizontal center. 
NB! supresses the gridarea for messages, but those are not in use*/
.nrdb-ui-slider .v-input--horizontal {
    grid-template-rows: auto 0;
}
```

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by arturv2000** [comment]
Thanks

Before:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/378cadae-4155-4e1b-9ff8-5ffc34e40251)

After:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/4e6cef0e-ab46-46f2-98a9-c771c235f3a9)

Small tweak.. but depending on the types of nodes and quantity has some visual effect

**Comment by joepavitt** [comment]
Please feel free to just open a PR for this kind of thing @hotNipi - no need to issue first. Contributions are always welcome

**Comment by hotNipi** [comment]
As it affects the layout a lot I just wanted to be sure that there will be plenty of options to "try before buy"

**Comment by joepavitt** [comment]
PR is still the best place for it as they're explicit code changes/recommendations. We can then pull your branch down and try it out live, rather than having to manually reproduce the changes locally.
