### ISSUE TITLE
Any Sized Button With An Icon But No Text Shows As A Small Circle

### ISSUE THREAD

**Issue by My-Random-Thoughts** [FlowFuse/node-red-dashboard#1058]
### Current Behavior

When creating a button on a dashboard, if an icon is used, but no label, the button shows as a small circle instead.

### Expected Behavior

The button should show as the correct size with the icon centered

### Steps To Reproduce

Example Code:

`[{"id":"bbe1cae0aedd67c2","type":"ui-button","z":"3dc470dd27af6df6","group":"eff15a367f3af282","name":"1x1 Blank","label":"","order":1,"width":"1","height":"1","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":500,"y":240,"wires":[[]]},{"id":"7a5ec9e0bcc02dc9","type":"ui-button","z":"3dc470dd27af6df6","group":"eff15a367f3af282","name":"1x1 Space","label":" ","order":2,"width":"1","height":"1","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":650,"y":240,"wires":[[]]},{"id":"ec2ae93fa1cef56e","type":"ui-button","z":"3dc470dd27af6df6","group":"0c1145602d9355aa","name":"2x1 Blank","label":"","order":2,"width":"2","height":"1","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":500,"y":280,"wires":[[]]},{"id":"1a10491c8e6639be","type":"ui-button","z":"3dc470dd27af6df6","group":"0c1145602d9355aa","name":"2x1 Space","label":" ","order":1,"width":"2","height":"1","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":650,"y":280,"wires":[[]]},{"id":"51f95538d2efa361","type":"ui-button","z":"3dc470dd27af6df6","group":"f2d814bd661bdd28","name":"1x2 Blank","label":"","order":1,"width":"1","height":"2","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":500,"y":320,"wires":[[]]},{"id":"b04913a60167fa61","type":"ui-button","z":"3dc470dd27af6df6","group":"f2d814bd661bdd28","name":"1x2 Space","label":" ","order":2,"width":"1","height":"2","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":650,"y":320,"wires":[[]]},{"id":"6b92acfc4ca9af86","type":"ui-button","z":"3dc470dd27af6df6","group":"76ce3ca25577495f","name":"2x2 Blank","label":"","order":1,"width":"2","height":"2","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":500,"y":360,"wires":[[]]},{"id":"60cdb693c7b0014d","type":"ui-button","z":"3dc470dd27af6df6","group":"76ce3ca25577495f","name":"2x2 Space","label":" ","order":2,"width":"2","height":"2","emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"fast-forward","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","x":650,"y":360,"wires":[[]]},{"id":"eff15a367f3af282","type":"ui-group","name":"1x1","page":"f0bf766a2940d6f2","width":"4","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"0c1145602d9355aa","type":"ui-group","name":"2x1","page":"f0bf766a2940d6f2","width":"4","height":"1","order":3,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"f2d814bd661bdd28","type":"ui-group","name":"1x2","page":"f0bf766a2940d6f2","width":"4","height":"1","order":2,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"76ce3ca25577495f","type":"ui-group","name":"2x2","page":"f0bf766a2940d6f2","width":"4","height":"1","order":4,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"f0bf766a2940d6f2","type":"ui-page","name":"Button Test","ui":"1daee910d1b37604","path":"/page2","icon":"home","layout":"flex","theme":"65bf5b47911b7aa2","order":1,"className":"","visible":"true","disabled":"false"},{"id":"1daee910d1b37604","type":"ui-base","name":"UI-Base","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"showPageTitle":true,"navigationStyle":"default","titleBarStyle":"default"},{"id":"65bf5b47911b7aa2","type":"ui-theme","name":"Light","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]`

Code should produce this:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/21334396/46d4013c-821b-46dd-936e-c2d38a722770)

### Environment

- Node-RED : node-red-docker@4.0.1 /usr/src/node-red
- Node.js  : v22.3.0
- npm      : 10.8.1
- Platform : Linux 6.1.0-18-amd64 x86_64
- Browser  : Firefox 127.0.2

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by hotNipi** [comment]
Maybe to provide option for size 1x1 and if no label to be square or round, any other size or auto just follow sizing rules.

**Comment by My-Random-Thoughts** [comment]
I am happy for round buttons, but only if it's an option.

A 1x1 round would not work in this instance:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/21334396/fb1a41e6-ddb6-4279-8f50-0637a73acdd0)
where I have 2x 1x1 buttons to the right of text boxes.

**Comment by arturv2000** [comment]
With the latest dashboard version (1.12.4) this is what I get:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/8f5b40ce-8c7e-42d6-a744-6910865fa9d6)

Seems to be already fixed.

**Comment by hotNipi** [comment]
So let then the round option be for user to figure out. Not too much of science anyway. Just a bit of CSS.

**Comment by My-Random-Thoughts** [comment]
Thank you @arturv2000, it is indeed fixed.  It looks like it was updated less than 2 hours before I posted.
