### ISSUE TITLE
resizing ui-button doesn't work

### ISSUE THREAD

**Issue by Makku303** [FlowFuse/node-red-dashboard#1061]
### Current Behavior

changing the value of the size property, the button will add a margin instead of resizing the actual button.

### Expected Behavior

The button should resize based on the value of the size property.

### Steps To Reproduce

Create a ui-button set the initial size property.
Change the size property larger from the initial property but lower or same value of the group size.

### Environment

- Dashboard version: v1.12.4
- Node-RED version: v3.1.10
- Node.js version: v20.10.0
- npm version: 10.8.0
- Platform/OS: Windows 10 Enterprise v10.0.19045 build 19045
- Browser: google chrome v126.0.6478.127, MS Edge Version 126.0.2592.81 

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by arturv2000** [comment]
Hi

Not able to reproduce either with Node-Red 4.0.2 or 3.1.7 (booth using Dashboard 1.12.4)


https://github.com/FlowFuse/node-red-dashboard/assets/17281826/86b1b96d-dbd7-4a66-b31a-c52a498af1d7

**Comment by Makku303** [comment]
Thanks. I found the main cause of the issue being the global CSS I added affecting the behavior of the button.
