### ISSUE TITLE
`ui-template` How to get a flow variable?

### ISSUE THREAD

**Issue by kevinshane** [FlowFuse/node-red-dashboard#1073]
Hi noob here, in node red we can get a flow or global variable by using `flow.get("blah")`, however it seems inside `ui-template` I can't read or get a flow value, currently I have to use function node to read a flow variable and then pass that variable as a `msg.blah` to template node. So my question is, how exactly I can read flow variable directly inside a `ui-template` ? Thanks guys!

**Comment by kevinshane** [comment]
> Here, we assign `msg.payload` (could be anything) to a value from the global/flow stores
Thanks for the explaination. If I understanding correctly, when a value is updated and passed to `ui-template` node, it will cause the entire dashboard to re-render (assuming db is build only with `ui-template` node), is it correct?

**Comment by joepavitt** [comment]
>  it will cause the entire dashboard to re-render (assuming db is build only with ui-template node), is it correct?

Not necessarily, it'll just update the components using the `msg.` properties in `ui-template`.

**Comment by kevinshane** [comment]
OK thank you for your explaination.
