### ISSUE TITLE
`ui-template` How to display ssh `journalctl -f` log?

### ISSUE THREAD

**Issue by kevinshane** [FlowFuse/node-red-dashboard#1074]
Hi, I would like to display a remote host journalctl log by using the `ui-template` node. Is it possible to do that? Thanks guys!

**Comment by joepavitt** [comment]
Hi Kevin, from the Dashboard side, you can render anything passed to a `ui-template` inside the `msg` object.

As for accessing the log, I think that's more of a general purpose Node-RED question, so may be better served in the [Node-RED Forums](https://discourse.nodered.org/)?
