### ISSUE TITLE
How to use data tracker in third-party ui node

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#1076]
Hi guys,

Perhaps a stupid question, but I am not sure how I can use the data tracker in a third-party ui node vue file.

Because the standard ui nodes do it like this:

```
import { useDataTracker } from '../data-tracker.mjs'

setup (props) {
   useDataTracker(props.id)
}
```

Not sure whether I should include somehow the data-tracker.mjs into my own Vite build.
Or can I use the one that is already available in the dashboard somehow?

Thanks!
Bart

**Comment by joepavitt** [comment]
Unfortunately, it's not possible currently. Hence we have to build the trackers, etc. manually in a third-party node.

@cstns may have some ideas on how we _could_ do this though?

**Comment by cstns** [comment]
From the top of my head we could expose the composable. I'd need to give it a go and play with this idea but it might work

**Comment by bartbutenaers** [comment]
Hey guys,
Thanks for considering to add it!!

It would be nice if all the nodes would have a bit of similar implementation, to allow developers to find their way more easily...

**Comment by colinl** [comment]
Can someone point me to where I can find out what the datatracker is, in case I might want to use it?

**Comment by cstns** [comment]
https://dashboard.flowfuse.com/contributing/widgets/core-widgets.html#data-tracker
