### ISSUE TITLE
Documentation: Teleports example not working as suggested.

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#1082]
Hi,

In https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#teleports there is an example on how to render an image instead of the page name in DB2. 

When trying this however, this does only partially work: the image is displayed, but not in place of the Page name but to the right of it.

On a side note: If it would be to the left of the Page name, that would be fine too. However I am unable to do so by adding CSS in the `<img>` (or my CSS is wrong..). 

DB2 version 1.12.4.

Is the example still correct?
Thanks!

**Comment by joepavitt** [comment]
In the [documentation for that example](https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#page-name-app-bar-title):

> We can also turn off the rendering of the page name under the Dashboard's main settings, so, when using the teleport, this would be the only content rendered in the top-left.

Adding content via Teleport is step 1, hiding the page name (by clicking the "Edit Settings" in hte top of the Dashboard sidebar) is the second part
