### ISSUE TITLE
Mdi icon not appearing

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#1093]
Hi guys,

I want to show the material design icon [play_arrow](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:play_arrow:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=play&icon.size=24&icon.color=%235f6368):

![image](https://github.com/user-attachments/assets/ceb7f357-7ac2-48cb-921c-e1cbd6738a2b)

Never used this icon set before, but I assume I need to use the ***icon name***:

![image](https://github.com/user-attachments/assets/b14fdf1c-bf67-40c8-88c3-6ae667441a8a)

But it doesn't show up on my button.  If I use another icon name, it works fine:

![image](https://github.com/user-attachments/assets/03407505-c067-4742-8da7-470c842a5060)

The icon name ends up fine in my html page:

![image](https://github.com/user-attachments/assets/64582b3a-1e0d-472f-bc7c-418795747741)

Probably I am doing something stupid wrong, but can't see it...

Thanks!
Bart

**Comment by arturv2000** [comment]
Try using `play-outline`

![image](https://github.com/user-attachments/assets/89aafedc-2cde-43a2-85ca-28c2760fcdc5)

The icons list is here: [https://pictogrammers.com/library/mdi/](https://pictogrammers.com/library/mdi/ ), the link you sent is for another icon library, some have the same name but not all of them

**Comment by bartbutenaers** [comment]
@arturv2000,
Yes you are right (of course...).
I did a quick search for material design icons.  Wasn't aware that there were multiple libraries available.
Should have looked in the documentation or in the info panels, were the correct link is everywhere available.

Thanks!!
Bart
