### ISSUE TITLE
Switch does not send topic out even it is set at ui

### ISSUE THREAD

**Issue by burner-** [FlowFuse/node-red-dashboard#1102]
### Current Behavior

Switch does not send topic out even it is set at ui
![image (11)](https://github.com/user-attachments/assets/86b56fc9-a71f-4356-b6c4-adfbc6ff446e)

### Expected Behavior

Node should send msg.topic at state change when it is configured.

### Steps To Reproduce

look attached picture. Add switch, add debug, click switch and look message. 

### Environment

- Dashboard version: 1.13.0
- Node-RED version: 3.0.2
- Platform/OS: docker, ubuntu
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by colinl** [comment]
Is this a duplicate of #456?  If so then I believe a PR is working its way through the system.

**Comment by joepavitt** [comment]
This should now be fixed with #1090 and the `1.14.0` release 

Please can you confirm @burner- ?

**Comment by burner-** [comment]
Yes looks that this bug is fixed now.
