### ISSUE TITLE
Show Dashboard 2.0 seems not to work with Nodered  4.0.2 [Menu > View > Dashboard 2.0]

### ISSUE THREAD

**Issue by jdudvc** [FlowFuse/node-red-dashboard#1104]
### Current Behavior

with version 4.0.2 of node-red, when I want to access [Menu > View > Dashboard 2.0] the window remains empty.

### Expected Behavior

By following this menu line [Menu > View > Dashboard 2.0] I expect to be able to administer the dashbord 2.0

### Steps To Reproduce

installing node-red 4.0.2 and dashboard 2.0 version 1.13.0

goto [Menu > View > Dashboard 2.0]

### Environment

- Dashboard version: 1.13.0
- Node-RED version: 4.0.2
- Node.js version:  20.15.1
- npm version: 10.7.0
- Platform/OS: raspberry os Bookworm 2024-07-04
- Browser: Chrome Version 126.0.6478.127 on Windows

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by colinl** [comment]
It works ok for me.

> the window remains empty.
What window remains empty?  Perhaps a screenshot would be helpful.

**Comment by jdudvc** [comment]
> It works ok for me.
> 
> > the window remains empty.
> > What window remains empty?  Perhaps a screenshot would be helpful.

I am delighted to read this. This is proof that I must be doing something wrong.

I tried again on 3 other devices and I got the same result.

![Capture d’écran 2024-07-18 084405](https://github.com/user-attachments/assets/258da09e-44f2-495e-b7c5-8dd1b9f0c40c)

If I upgrade to NodeRed V3 it works normally.

**Comment by joepavitt** [comment]
Sometimes you need to move away from the Dashboard 2.0 tab and back to it when you've first added nodes on.

**Comment by jdudvc** [comment]
> Sometimes you need to move away from the Dashboard 2.0 tab and back to it when you've first added nodes on.

Oh yes indeed, it works now.

I switched from one version of the dashboard to another a few times:

dashboard > dashboard 2.0 > dashboard > dashboard 2.0 > dashboard > dashboard 2.0 

and that didn't change anything.

Then I did a Refresh of the page (F5) and it worked.
