### ISSUE TITLE
Have "Dialog" group types

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1106]
### Description

One of the most common use cases and requests I keep seeing for `ui-template` is to create a Dialog.

Having a `Dialog` node is tricky, because often users want to have custom content inside that they've defined, and within the context of the Node-RED tray, that's very difficult to configure.

We could offer the `ui-form` to present as a Dialog, but another, more flexible idea here is that any `ui-group` can be configured to be a `Dialog` type. 

We then enable use the existing `ui-control` schema to show/hide a group to control the visibility of the Dialog

#### Request:

- Groups have a new "Type" property
- Type can be set as "Dialog" or "Default"
- Default renders as per now, in line on a page.
- Dialog would render the group as a centrally aligned modal/dialog on the page, [which can be shown/hidden via UI Control](https://dashboard.flowfuse.com/nodes/widgets/ui-control.html#show-hide) 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Love this idea.

In the words of the great Picard "make it so"
