### ISSUE TITLE
UI Markdown - Mermaid content doesn't render on page refresh

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1121]
### Current Behavior

When refreshing the browser, any mermaid content is rendered as raw `markdown`, instead of a rendered mermaid chart.

### Expected Behavior

The mermaid chart should still render as an actual chart after a page refresh

### Steps To Reproduce

1. Add a `ui-markdown` node
2. Paste in the below "Example Mermaid" content
3. View the Dashboard
4. Refresh the Dashboard

#### Example Mermaid

```
graph TD;
A-->B;
A-->C;
B-->D;
C-->E;
```

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by buschhardtt** [comment]
My workaround is:

- add Inject-Node with one time injection after 0.1 sec
