### ISSUE TITLE
Third party nodes not being loaded when node-red projects are in use.

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#1129]
### Current Behavior

There is some guesswork in this, but from forum post https://discourse.nodered.org/t/dashboard-2-question/89759 it seems that third party nodes are not loaded when node-red projects are in use.  It seems that when projects are in use the flows file and the associated package.json is in `.node-red/projects/<theproject>` not in `.node-red`.  I think that the dashboard loader is looking in .node-red/package.json rather than the one in the project.  I don't use projects so can't easily test this.  The OP on the forum copied the third party node entries into the .node-red package.json and that fixed the problem.

### Environment

- Dashboard version: 1.13.0
- Node-RED version: 4.0.2
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by arturv2000** [comment]
I use the projects feature in node-red in all my instances, and don't have any issues loading third-party widgets (`ui-frame`, `ui-led`, `ui-gauge-classic`).

All instances where created initially with node-red V3.xx, don't know if that could be important.

**Comment by colinl** [comment]
Which package.json do they appear in?

**Comment by arturv2000** [comment]
They are in the `package.json` in the `userDir` (set via the `-u` flag when launching node-red service) root (in the same level as `settings.js`, `context` dir).

The `package.json` inside the project folder is relatively empty, just having:

```json
{
    "name": "test1",
    "description": "A Node-RED Project",
    "version": "0.0.1",
    "dependencies": {},
    "node-red": {
        "settings": {
            "flowFile": "flows.json",
            "credentialsFile": "flows_cred.json"
        }
    }
}
```

**Comment by rvangeijtenbeek** [comment]
Items get added to the package.json in the project folder when you use the option to declare dependencies. 

Node-RED editor menu > Projects > Project Settings > Dependencies - it will show a list of nodes used in your project flows that can optionally be added as dependencies.

**Comment by arturv2000** [comment]
Ok, did not use that feature to indicate the project dependencies.

Just using the projects feature to have separated flows files and to use GIT. The dependencies in my case i manage individually since is typically just 3~4 extra packages that are common to most projects i have.

**Comment by joepavitt** [comment]
Closing this is it boiled down to the original reporter manually installing via terminal, and not installing to the correct `package.json`
