### ISSUE TITLE
Example for ui-page

### ISSUE THREAD

**Issue by buschhardtt** [FlowFuse/node-red-dashboard#1134]
Hallo, do You have a simple example how to change the visibilty of a page?
For example I want only shown certein user a page, for all other this page is hidden.

I see in documentation "these can be overridden by the user at runtime using a ui-control node", but how exact?

msg.[ui-page-ID].visible = false :-) ??

Thank You Thomas

**Comment by joepavitt** [comment]
Thanks for the question - you'll find the answer in the[ UI Control Docs](https://dashboard.flowfuse.com/nodes/widgets/ui-control.html#show-hide)

**Comment by buschhardtt** [comment]
Oh Im so sorry I missed this documentationpage.

Thank You Joe (for your time)
