### ISSUE TITLE
ui-link. add feauture to "open the link in new tab"

### ISSUE THREAD

**Issue by mountain181** [FlowFuse/node-red-dashboard#1157]
### Description

I need ui-link config setting wheter or not hyperlink should be open in new tab. Now, when pressing hyperlink in navigation menu (ui-link). The link replaces dashboard web page.  I want ui-link hyperlink to open in new browser tab instead. If any questions please ask. 

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Thanks for opening the issue @mountain181 - closing as it's a duplicate of #1125 and will be addressed shortly
