### ISSUE TITLE
UI Control: Open external site not working as per example.

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#1158]
### Current Behavior

Nothing happens..

### Expected Behavior

A site (url sent by button) opens in a new (or the same) browser window.

### Steps To Reproduce

[
    {
        "id": "4882290db8563350",
        "type": "debug",
        "z": "529f871459430a97",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 790,
        "y": 560,
        "wires": []
    },
    {
        "id": "1d2494af36e71c20",
        "type": "ui-button",
        "z": "529f871459430a97",
        "group": "5c3fa2715edc9ba5",
        "name": "",
        "label": "button",
        "order": 1,
        "width": 0,
        "height": 0,
        "emulateClick": false,
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "iconPosition": "left",
        "payload": "https://www.google.com",
        "payloadType": "str",
        "topic": "url",
        "topicType": "str",
        "buttonColor": "",
        "textColor": "",
        "iconColor": "",
        "x": 290,
        "y": 520,
        "wires": [
            [
                "dbcc95f97f5bf51c"
            ]
        ]
    },
    {
        "id": "dbcc95f97f5bf51c",
        "type": "change",
        "z": "529f871459430a97",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "link",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 450,
        "y": 520,
        "wires": [
            [
                "b0975b666ac696aa"
            ]
        ]
    },
    {
        "id": "6d4bf619be7e1a26",
        "type": "ui-control",
        "z": "529f871459430a97",
        "name": "",
        "ui": "e9690ed2a2e30bab",
        "events": "all",
        "x": 800,
        "y": 520,
        "wires": [
            []
        ]
    },
    {
        "id": "b0975b666ac696aa",
        "type": "template",
        "z": "529f871459430a97",
        "name": "",
        "field": "payload",
        "fieldType": "msg",
        "format": "handlebars",
        "syntax": "mustache",
        "template": "{\n    {{topic}}: '{{{link}}}'\n}\n",
        "output": "str",
        "x": 620,
        "y": 520,
        "wires": [
            [
                "6d4bf619be7e1a26",
                "4882290db8563350"
            ]
        ]
    },
    {
        "id": "5c3fa2715edc9ba5",
        "type": "ui-group",
        "name": "Information & Links",
        "page": "1c561fd9d2311d74",
        "width": "4",
        "height": "1",
        "order": 2,
        "showTitle": true,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "e9690ed2a2e30bab",
        "type": "ui-base",
        "name": "Dashboard DSRI",
        "path": "/dashboard",
        "includeClientData": true,
        "acceptsClientConfig": [
            "ui-notification",
            "ui-control",
            "ui-text-input",
            "ui-button",
            "ui-button-group",
            "ui-dropdown",
            "ui-radio-group",
            "ui-switch",
            "ui-text",
            "ui-slider",
            "ui-table",
            "ui-chart",
            "ui-gauge",
            "ui-markdown",
            "ui-template"
        ],
        "showPathInSidebar": false,
        "showPageTitle": false,
        "navigationStyle": "fixed",
        "titleBarStyle": "default"
    },
    {
        "id": "1c561fd9d2311d74",
        "type": "ui-page",
        "name": "Help",
        "ui": "e9690ed2a2e30bab",
        "path": "/help",
        "icon": "help-box-multiple-outline",
        "layout": "grid",
        "theme": "e9a406b6866a2897",
        "order": 2,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "e9a406b6866a2897",
        "type": "ui-theme",
        "name": "UM Theme",
        "colors": {
            "surface": "#001c3d",
            "primary": "#039fdb",
            "bgPage": "#ffffff",
            "groupBg": "#ffffff",
            "groupOutline": "#039fdb"
        },
        "sizes": {
            "pagePadding": "12px",
            "groupGap": "12px",
            "groupBorderRadius": "4px",
            "widgetGap": "12px"
        }
    }
]

Which on button click sends a payload of 
![image](https://github.com/user-attachments/assets/99a1f72b-c3ef-4b6d-a71b-56b339868e9b)

Which is (if I'm not mistaken) idential (exept for URL) to the UI Control example in the Help and on Docs:
![image](https://github.com/user-attachments/assets/a673466b-85bd-4899-8d52-1711ddedacda)

However, external site does not open when clicking the button. UI Control generates error:
![image](https://github.com/user-attachments/assets/6ea08c9a-3dd0-4f54-b804-816451b8c154)

Unless I am doing something wrong.. ?

Also, documentation does not mention if the external site opens in a new browser window. 
It would be very nice to be able to have control over that.

### Environment

- Dashboard version: 1.14.0
- Node-RED version: 4.0.2
- Node.js version: 20.15.0
- Browser: vivaldi, firefox

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by SynoUser-NL** [comment]
When you think you've checked everything.. 🫨 
Thanks Joe!

Is there a way to open the link in a new browser window\tab at this time?

**Comment by joepavitt** [comment]
> Is there a way to open the link in a new browser window\tab at this time?

Not yet, but please do open a Feature Request

**Comment by SynoUser-NL** [comment]
https://github.com/FlowFuse/node-red-dashboard/issues/1163

Thanks!
