### ISSUE TITLE
UI-Control: Enable opening (external) link in a new browser window\tab

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#1163]
### Description

Request to make it possible to open a link (external to Dashboard site, internal may be nice as well) in a new browser window or tab (target="_blank").

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Easy option here is that as part of the `{ url: "" }` we also have an optional `target` parameter which supports this feature
