### ISSUE TITLE
ui-switch in 'show state of input' mode shows wrong state in status when waiting, and wrong icon switch state after refresh.

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#1174]
### Current Behavior

If a ui-switch is configured to not passthrough, and with 'show state of input' then when the switch is clicked it correctly goes into the 'waiting' state, showing the rotating arrow on the icon.  However, the state shown under the switch shows the wrong state. It should show the original state until a message is received with the new state.  In other words the status should also show the state of the input, not the state of the output.
In addition, if the page is refreshed when in the 'waiting' state it switches to the new state, it should stay showing the old state.

### Expected Behavior

Switch status should show state of input when in that mode.
Page refresh when in 'waiting' mode should show the original switch state.

### Environment

- Dashboard version: github version 27866e4, 07/08/24
- Node-RED version: 4.0.2
- Node.js version: 20.5.`
- npm version:
- Platform/OS: Ubuntu on PC
- Browser: Edge

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
> state shown under the switch

Just to check, you're referring to the state shown under the switch _node_ here? Not the switch in the Dashboard itself?

> In addition, if the page is refreshed when in the 'waiting' state it switches to the new state, it should stay showing the old state.

Hmm. fairly sure I have that tested, I'll double check

**Comment by colinl** [comment]
> > state shown under the switch
> 
> Just to check, you're referring to the state shown under the switch _node_ here? Not the switch in the Dashboard itself?

Correct, for example, after clicking a switch that is Off, this shows in the dashboard
![image](https://github.com/user-attachments/assets/928c8604-734e-4778-bf5c-bad4c6e4b24f)

and this in the editor
![image](https://github.com/user-attachments/assets/01d214bc-0490-485b-95b7-092658bad6d2)

Then if I refresh the dashboard it shows
![image](https://github.com/user-attachments/assets/ef879bc6-86d0-4676-8eee-02a4d14e30a6)

On a different issue (so OT here I suppose), if one is using custom icons, how does that interact with the waiting state?

**Comment by joepavitt** [comment]
> if one is using custom icons, how does that interact with the waiting state?

It's all the same, there is a loading graphic that substitutes for the custom icon

**Comment by colinl** [comment]
Unfortunately, after #1175, it seems that the switch no longer sends messages when clicked in 'show state of input' mode.

**Comment by joepavitt** [comment]
Yep, that's silly of me - I'll get some E2E's written for this to prevent the constant regressions

**Comment by colinl** [comment]
Great, working perfectly now :)
