### ISSUE TITLE
Dynamic Properties: UI Gauge

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1180]
Using [Dynamic Properties Best Practices](https://dashboard.flowfuse.com/contributing/widgets/core-widgets.html#dynamic-properties), implement:

- Label
- Gauge Type (`gtype`)
- Gauge Style (`gstyle`)
- Title (`title`)
- Units (`units`)
- Icon (`icon`)
- Prefix (`prefix`)
- Suffix (`suffix`)
- Segments (`segments`)
- Min (`min`)
- Max (`max`)

as dynamic properties.

**Comment by makerstorage** [comment]
Waiting to have this

**Comment by joepavitt** [comment]
Thanks @makerstorage - it does have a pull request open, but needed some changes before it can be merged. Hopefully it'll be available this week or next.

**Comment by makerstorage** [comment]
Thanks. Great to hear this.

**Comment by gayanSandamal** [comment]
Fixes https://github.com/FlowFuse/node-red-dashboard/issues/1255
