### ISSUE TITLE
Dynamic Properties: UI Switch

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1181]
Using [Dynamic Properties Best Practices](https://dashboard.flowfuse.com/contributing/widgets/core-widgets.html#dynamic-properties), implement:

- Label
- Passthru
- Decouple
- offcolor
- oncolor

as dynamic properties.

**Comment by bartbutenaers** [comment]
Hi @joepavitt,
I had most of this completed tonight.  Will try to finish it tomorrow evening.
So you can assign this one to me.
