### ISSUE TITLE
Typedinput for buttons in ui-table

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#1188]
As discussed [here](https://github.com/FlowFuse/node-red-dashboard/pull/1171#issuecomment-2277380023) a typedinput for the buttons in a ii-table would be more user friendly.

I will take care of this as soon as I have time.

**Comment by joepavitt** [comment]
Going to give this to @Steve-Mcl as he has a little wiggle room at the moment

**Comment by Steve-Mcl** [comment]
Hey @bartbutenaers I have read the linked issue several times. I may just be tired but I am not certain what the task is?

Any chance you could add some detail to this issue pls?

An annotated screenshot describing your expectation would go a long way to help.

Ta.

**Comment by Steve-Mcl** [comment]
@joepavitt I am not 100% clear on the requirement of this. Could you or @bartbutenaers clarify please?

**Comment by joepavitt** [comment]
Currently, buttons will render their label based on the "Key" value. However, that means you have to manually inject a value into your row of data, e.g. if you want a button saying "Delete":

```
{
    "delete": "Delete Me"
}
```

setting the "Key" value to `delete`, would then render "Delete Me" in the button. Ideally, we'd have the option to just render a static string for all buttons, so a `TypedInput` on the `Key` field _I think_ is the solution here? 

We may need to change the "Key" label in the config to "Value", then the `TypedInput` would have `Key` and `String` options?

**Comment by bartbutenaers** [comment]
Hi @Steve-Mcl,
Sorry for the delay! 
Well I understand your confusion.  I also had now to reread the discussion a couple of times to load it all back into my brain.  But I see that you have meanwhile created a PR to implement Joe's feedback. 
Thanks for that!!
