### ISSUE TITLE
Button should send it's label on every press

### ISSUE THREAD

**Issue by mountain181** [FlowFuse/node-red-dashboard#1190]
### Description

Button to send label of button on every press. It would be easier to make automations based on button label if label always existed in msg object (look button start/reset in video). Now i use ui_update.label, but it doesnt persist through page reloads, or on new input msg to button. My wish : Whenever button is clicked. Button should always output it's label. 

https://github.com/user-attachments/assets/9f30c00a-9700-45e1-bf82-892108ed466e

![Add msg label  Should exist on every button click](https://github.com/user-attachments/assets/9af70688-af6a-4338-8ba5-5fa29765b394)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
> Now i use ui_update.label, but it doesnt persist through page reloads

This is not expected? That should be persisting?

**Comment by mountain181** [comment]
Not expected that it should persist. Hence a feature request to have a msg.label or something like that

**Comment by mountain181** [comment]
a msg.label would have very niche usecases, and probably not useful for 99% of node red dashboard developers, so we can close the issue.

**Comment by joepavitt** [comment]
it is, and it's difficult to justify as why wouldn't we then _also_ include every other property too? It could get out of hand quite quickly.

For this, I would recommend using the Node-RED context store. When you click a temperature, you set a `flow.state` to `ready`. Then when you've clicked `start` it changes the state to `started`. You can have a "switch" node to check the current state on each button press and action accordingly.

**Comment by colinl** [comment]
@mountain181 if I understand the requirement correctly then the usual technique would be to use the topic for this.

**Comment by mountain181** [comment]
@colinl Topic doesnt tell anything what label of button is. 

As you can see in video the same button is both start and reset depending on what state the system is in. I thought that adding a msg.label based on client data would be the single source of truth of what label state button is. So that i did not need to keep track of states myself. msg.payload is telling me what button is pressed so no msg.topic necessary for that. 

Technically i could combine all the buttons into 1 button if i had a msg.label telling me what label was on button. This to keep track of state. Anyways, im just glad dashboard team added dynamic labels, so  i cant complain. I can keep track of label state myself using flow variables. Its not a problem really

**Comment by colinl** [comment]
> Topic doesnt tell anything what label of button is.

It does if you update the topic configuration to the same as the label.

**Comment by colinl** [comment]
Something like this
```
[{"id":"b95f821c8a86bc95","type":"ui-button","z":"997da33a0beedade","group":"4f87bd59a15b847e","name":"Topic test","label":"button","order":0,"width":0,"height":0,"emulateClick":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"","iconPosition":"left","payload":"","payloadType":"str","topic":"topic","topicType":"msg","buttonColor":"","textColor":"","iconColor":"","x":520,"y":7080,"wires":[["75ad5ee096439b09"]]},{"id":"75ad5ee096439b09","type":"debug","z":"997da33a0beedade","name":"debug 2533","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":700,"y":7080,"wires":[]},{"id":"113d600dc07f5562","type":"inject","z":"997da33a0beedade","name":"","props":[{"p":"topic","vt":"str"},{"p":"ui_update.label","v":"Label 1","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Label 1","x":330,"y":7080,"wires":[["b95f821c8a86bc95"]]},{"id":"573fc2f4a17a085d","type":"inject","z":"997da33a0beedade","name":"","props":[{"p":"topic","vt":"str"},{"p":"ui_update.label","v":"Label 2","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Label 2","x":330,"y":7140,"wires":[["b95f821c8a86bc95"]]},{"id":"4f87bd59a15b847e","type":"ui-group","name":"test","page":"c6ff182a4185f2f2","width":"6","height":"1","order":1,"showTitle":false,"className":"","visible":"true","disabled":"false"},{"id":"c6ff182a4185f2f2","type":"ui-page","name":"Test page","ui":"ID-BASE-1","path":"/testpage","icon":"home","layout":"grid","theme":"f9b6670b127dc219","order":1,"className":"","visible":"true","disabled":"false"},{"id":"ID-BASE-1","type":"ui-base","name":"Dashboard","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-control","ui-notification","ui-gauge-classic"]},{"id":"f9b6670b127dc219","type":"ui-theme","name":"FlowForge Theme","colors":{"surface":"#152a47","primary":"#005aff","bgPage":"#ffffff","groupBg":"#ffffff","groupOutline":"#cc3e3e"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

**Comment by mountain181** [comment]
Never crossed my mind i could do that. Thank you sir, i will tell you how it goes
