### ISSUE TITLE
[Regression] Text Size no longer working in ui-text node.

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#1193]
### Current Behavior

In the current `main` on github (commit fff158d200) text styling in the ui-text node appears to be broken. It is ok in 1.14.0.  
A ui-text node configured with
![image](https://github.com/user-attachments/assets/4aec9a6f-8b38-4959-84db-68f8038c5e15)
Shows the text at normal size.  Looking in the dev tools it seems the DOM and CSS have changed significantly for the node and I cannot see any trace of the styling in the CSS.
```
[{"id":"094aac740f188806","type":"ui-text","z":"997da33a0beedade","group":"4f87bd59a15b847e","order":0,"width":0,"height":0,"name":"Text size test","label":"Text size test","format":"{{msg.payload}}","layout":"row-spread","style":true,"font":"","fontSize":"72","color":"#717171","className":"","x":540,"y":7180,"wires":[]},{"id":"4f87bd59a15b847e","type":"ui-group","name":"test","page":"c6ff182a4185f2f2","width":"6","height":"1","order":1,"showTitle":false,"className":"","visible":"true","disabled":"false"},{"id":"c6ff182a4185f2f2","type":"ui-page","name":"Test page","ui":"ID-BASE-1","path":"/testpage","icon":"home","layout":"grid","theme":"f9b6670b127dc219","order":1,"className":"","visible":"true","disabled":"false"},{"id":"ID-BASE-1","type":"ui-base","name":"Dashboard","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-control","ui-notification","ui-gauge-classic"]},{"id":"f9b6670b127dc219","type":"ui-theme","name":"FlowForge Theme","colors":{"surface":"#152a47","primary":"#005aff","bgPage":"#ffffff","groupBg":"#ffffff","groupOutline":"#cc3e3e"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]
```

### Environment

- Dashboard version: Main branch as of 10/08/24, commit fff158d200
- Node-RED version: 4.0.2
- Node.js version:
- npm version:
- Platform/OS: Ubuntu
- Browser: Edge

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gayanSandamal** [comment]
@colinl Thank you for reporting. I will do a further investigation on this

**Comment by colinl** [comment]
I have edited the title as it is only the text size that does not work. Font and Colour do work.
