### ISSUE TITLE
Blank Sidebar when def icon is a function (subflows)

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#1195]
This breaks the sidebar. subflows icon can be a function.

![image](https://github.com/user-attachments/assets/a297a221-b57b-4624-99ad-f17bcce87a4f)

_Originally posted by @Steve-Mcl in https://github.com/FlowFuse/node-red-dashboard/pull/1165#discussion_r1712632661_

**Comment by bartbutenaers** [comment]
Hey @Steve-Mcl ,
Damn didn't see that one coming...
Is this something you can fix? 
Because I am off today, and I have no experience with subflows.
Never used subflows to be honest.

**Comment by Steve-Mcl** [comment]
> Hey @Steve-Mcl , Damn didn't see that one coming... Is this something you can fix? Because I am off today, and I have no experience with subflows. Never used subflows to be honest.

Hey Bart. The key was to use `RED.utils.getNodeIcon` - it resolves the path to the image URL and takes into accound any override set on the nodes properties.  Also, I noticed you had an `<image>` tag for images.  Not sure that works (did you mean `<img>`?) Anyhow, the all (SVGs, PNGs,...) are now rendered in `<i> tags and are set via the `mask-image` CSS properties in an attempt to create a consistent white on black. (see screenshot in PR #1196)

**Comment by Steve-Mcl** [comment]
PS, the reason i didnt apply icon images for anything other than the subflow originally was because I knew the difficulties involved in getting the varing iconography to appear consistent in the tree view (and so left non-subflows with the original default icon).  

Fixing this up took waaaaay longer than I care to admit :yikes:

**Comment by bartbutenaers** [comment]
> Not sure that works (did you mean <img>?) 

Yes indeed you are right.  Seems I have been using SVG images for too long time...  I had changed one of my ui nodes to use a png image.  And it was there.  Perhaps that Chrome did me a favour by displaying it anyway.  And that it would fail on other browsers.  Don't know.  Anyway you found a much better way...

> Fixing this up took waaaaay longer than I care to admit

Oeps, now I feel bad 😞
