### ISSUE TITLE
chart node does not send full dataset / cannot recieve full dataset

### ISSUE THREAD

**Issue by kes31** [FlowFuse/node-red-dashboard#1216]
### Current Behavior

When a chart node is recieving a new datapoint input it is outputting exactly this datapoint

### Expected Behavior

following your documentation on https://flowfuse.com/blog/2023/05/persisting-chart-data-in-node-red/ the chart node should output the full dataset

### Steps To Reproduce

1. add slider connected to chart node connected to debug note giving full message.
2. open page and move slider
3. check debug output

### Environment

- Dashboard version: 1.14
- Node-RED version: 4.0.2

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
HI @kes31 - we need to update that article, as it's referring to Dashboard 1.0 

This is not an approach we take in Dashboard 2.0

**Comment by kes31** [comment]
@joepavitt  ok, thank you. I understand. So I'll have create my own process for having json persistance.
