### ISSUE TITLE
Sidebar - cannot drop widget on empty group

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#1228]
### Current Behavior

When I want to move a widget in the sidebar to an empty group, that always fails:

![sidebar_empty_group](https://github.com/user-attachments/assets/39dd79cb-693e-49af-91be-80676d755d84)

As soon as there is at least 1 widget already available in the group, it works fine.
I have no clue how to solve it myself in the code...

### Expected Behavior

I would expect the empty group somehow to accept a widget being dropped.

### Steps To Reproduce

1. Create an empty group in the sidebar.
2. Try to move a widget to it

### Environment

- Dashboard version: 1.15.0
- Node-RED version: 3.0.3
- Node.js version: 18.19.0
- npm version:
- Platform/OS: Linux 6.1.0-rpi7-rpi-v8 arm64 LE
- Browser: Chrome (Windows)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
@Steve-Mcl mind taking a look at this next week please?

**Comment by Steve-Mcl** [comment]
Just noticed, the same issue exists for dropping groups onto a page.

![chrome_tx7V1cgiTB](https://github.com/user-attachments/assets/30d52600-470e-4d18-a62e-89b12642e780)
