### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by dastriebel** [FlowFuse/node-red-dashboard#1229]
### Current Behavior

Docu page https://dashboard.flowfuse.com/layouts/:

We currently offer **_three_** different layout options:

[Grid](https://dashboard.flowfuse.com/layouts/types/grid.html)
[Fixed](https://dashboard.flowfuse.com/layouts/types/fixed.html)
[Notebook](https://dashboard.flowfuse.com/layouts/types/notebook.html)
[Tabs](https://dashboard.flowfuse.com/layouts/types/tabs.html)

### Expected Behavior

"three" should be "four"

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by gayanSandamal** [comment]
Thanks for reporting this bug, @dastriebel 

While reviewing the issue you pointed out, I also noticed that the reference to the Tabs layout was missing from the ["Getting Started" page under the "Layout Options"](https://dashboard.flowfuse.com/getting-started.html#layout-options) section. I've added both now.

https://github.com/FlowFuse/node-red-dashboard/pull/1267

**Comment by dastriebel** [comment]
Thanks for that, so a smal ishue ist grwowing ;-)
