### ISSUE TITLE
UI Gauge data not storing

### ISSUE THREAD

**Issue by gayanSandamal** [FlowFuse/node-red-dashboard#1242]
Data not storing in the server side as mentioned [here](https://github.com/FlowFuse/node-red-dashboard/pull/1238#issuecomment-2312423104)

**Comment by joepavitt** [comment]
The data is saving server-side, this is not a bug, but was a piece of feedback on the PR you had opened because you hadn't implemented the server-side logic

**Comment by gayanSandamal** [comment]
> The data is saving server-side, this is not a bug, but was a piece of feedback on the PR you had opened because you hadn't implemented the server-side logic

Noted, I deleted the branch which I created for this too
