### ISSUE TITLE
Button - Not filling height > 1 with "Compact" or "Comfortable" sizings

### ISSUE THREAD

**Issue by JulianStremel** [FlowFuse/node-red-dashboard#1276]
### Current Behavior

Buttons do not fill the container when "compact" or "comfortable" is used as theme

### Expected Behavior

Buttons should fill their container everytime

### Steps To Reproduce

Create Button
Set Page theme to "compact" or "comfortable"

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Can you include a screenshot please? Not sure what you mean by "container"?

**Comment by JulianStremel** [comment]
![Screenshot 2024-09-10 124339](https://github.com/user-attachments/assets/30a0bbe6-0456-46f1-ad5f-143137e2d396)
![Screenshot 2024-09-10 124413](https://github.com/user-attachments/assets/5059ef2b-4715-4fff-8d0e-48a54f540eba)
![Screenshot 2024-09-10 124538](https://github.com/user-attachments/assets/78bfee19-6d5a-4fb5-8eeb-7ffaf08794c5)

**Comment by JulianStremel** [comment]
You can see that in different theming modes the button does not fill the set rows of 2 but only 1

**Comment by joepavitt** [comment]
Ah, got it, so when you're setting height > 1 the issue arises. Thanks, will schedule a fix.

**Comment by JulianStremel** [comment]
I fixed it already its contained inside my pull request its just one line in the "common.css"
