### ISSUE TITLE
Line chart: first two points of 2nd and all subsequent series are not connected

### ISSUE THREAD

**Issue by MartinJura** [FlowFuse/node-red-dashboard#1279]
### Current Behavior

When plotting a line chart with more than one series only the first two data points of the first series are connected by a line. The first two datapoints of the second and all subsequent series are not connected by a line.
![CleanShot 2024-09-09 at 13 30 43@2x](https://github.com/user-attachments/assets/433f6276-d7a2-47b2-95d5-10cc5dff84c6)

### Expected Behavior

When plotting a line chart with more than one series all datapoints of each series are connected by a line

### Steps To Reproduce

- create a function which sends multiple messages, one for each series
- add a chart node

### Environment

- Dashboard version: 1.16.0
- Node-RED version: 4.0.2
- Node.js version: 20.17.0
- npm version: 10.8.2
- Platform/OS: Debian Bookworm
- Browser: Safari

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by E1cid** [comment]
This has been fixed here https://github.com/FlowFuse/node-red-dashboard/issues/1255
