### ISSUE TITLE
Number input does not adhere to min or max range

### ISSUE THREAD

**Issue by JulianStremel** [FlowFuse/node-red-dashboard#1282]
### Current Behavior

When tapping "up" or "down" on the arrows next to the inpu a value below or above the specified range can be set and will be send as a message

### Expected Behavior

when going above or below the specified range the value should be clamped to the nearest border 

### Steps To Reproduce

setup a numeric input with range 20-100 and step width 1 and tap up and or down above and below the range

### Environment

- Dashboard version: 1.16
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by mountain181** [comment]
@gayanSandamal and flowfuse team already made fix for this. So you might as well delete this. Soon to be merged into main. Look this pull request. Looks good. https://github.com/FlowFuse/node-red-dashboard/pull/1273
