### ISSUE TITLE
Expose Mobile Columns in Layout Config

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1291]
### Description

It's is possible to override the column count at each breakpoint using CSS currently, but this isn't low-code friendly.

We should expose these at the page level (maybe base to be consistent across the full Dashboard?) to make this easier.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
Is this a duplicate of #1225?

**Comment by joepavitt** [comment]
It most certainly is, I was on my phone when creating this, did a quick search (as I remembered one being created) and couldn't find it.

Closing as duplicate of #1225
