### ISSUE TITLE
Add "Timeseries" x-axis for Bar Charts

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1293]
### Description

https://discourse.nodered.org/t/visualizing-numerical-data-on-bar-chart-with-x-axis-type-set-as-on-timestamp/90997/2

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Duplicate of #1045

**Comment by Snotmann** [comment]
....
