### ISSUE TITLE
Chart node missing data after page reconnect

### ISSUE THREAD

**Issue by E1cid** [FlowFuse/node-red-dashboard#1297]
### Current Behavior

When you have an open browser tab showing chart in background, after some time the page disconnects. When returning to tab the page reconnect, and does not refresh. When new data comes in the data for the time the page was not connected is missing, It returns after you refresh page.
images available here https://discourse.nodered.org/t/dashboard-2-0-chart-node-page-reconnect-issue/91017

### Expected Behavior

When page reconnects the page should be refreshed to show the missing data

### Steps To Reproduce

create chart feed in data every 10 seconds. send tab to background. wait 20mins, return to tab and wait for new incoming data

### Environment

- Dashboard version: 1.16
- Node-RED version: 3.1.3
- Node.js version: 20
- npm version: 5
- Platform/OS: Android
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by colinl** [comment]
Possibly the same issue as #1115, which is the same problem with text widget.

**Comment by colinl** [comment]
For the record, this also affects the Switch node. A change of state while disconnected is not shown on re-connection. Probably other node types have the same issue.

**Comment by Steve-Mcl** [comment]
> For the record, this also affects the Switch node. A change of state while disconnected is not shown on re-connection. Probably other node types have the same issue.

My PR #1343 works in such a way that it _should_ be a universal fix (i.e. not only for charts missing data)

**Comment by colinl** [comment]
I can confirm that the PR does fix the problem, at least for the Text node (#1115) and the Switch node.

**Comment by Steve-Mcl** [comment]
> I can confirm that the PR does fix the problem, at least for the Text node (#1115) and the Switch node.

Thanks for trying it out Colin 👍
