### ISSUE TITLE
Number input node does not honor limits

### ISSUE THREAD

**Issue by burner-** [FlowFuse/node-red-dashboard#1311]
### Current Behavior

Number input node does not honor given limits. Also looks that step setting does not affect. 
![image](https://github.com/user-attachments/assets/21ac2b0d-b63c-44f9-bbeb-b11d4f2a00b8)
![image](https://github.com/user-attachments/assets/50cd7aa3-110e-44d6-9502-4b1a1f3ce62e)

### Expected Behavior

Number should get capped inside of limits. 
Also there should be default value setting or use minimum as default value. 

### Steps To Reproduce

`[
    {
        "id": "0b36d6f8694a47ec",
        "type": "ui-number-input",
        "z": "74439af8f8b3af7f",
        "group": "797253700d88e905",
        "name": "",
        "label": "Lämpötila",
        "order": 0,
        "width": 0,
        "height": 0,
        "topic": "topic",
        "topicType": "msg",
        "min": "36",
        "max": "38",
        "step": "2",
        "tooltip": "",
        "passthru": false,
        "sendOnBlur": true,
        "sendOnEnter": true,
        "className": "",
        "clearable": false,
        "icon": "",
        "iconPosition": "left",
        "iconInnerPosition": "inside",
        "x": 1540,
        "y": 880,
        "wires": [
            [
                "e234f97f93e25ba7"
            ]
        ]
    },
    {
        "id": "e234f97f93e25ba7",
        "type": "change",
        "z": "74439af8f8b3af7f",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "poolSetTemp",
                "pt": "flow",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1840,
        "y": 880,
        "wires": [
            []
        ]
    },
    {
        "id": "a94d54c33a67b824",
        "type": "inject",
        "z": "74439af8f8b3af7f",
        "name": "",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "x": 1050,
        "y": 880,
        "wires": [
            [
                "043a05ab1c59d114"
            ]
        ]
    },
    {
        "id": "043a05ab1c59d114",
        "type": "change",
        "z": "74439af8f8b3af7f",
        "name": "get flow.poolSetTemp",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "poolSetTemp",
                "tot": "flow"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1240,
        "y": 880,
        "wires": [
            [
                "0b36d6f8694a47ec"
            ]
        ]
    },
    {
        "id": "797253700d88e905",
        "type": "ui-group",
        "name": "Ohjaus",
        "page": "caa16f1777392341",
        "width": "6",
        "height": "1",
        "order": 1,
        "showTitle": true,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "caa16f1777392341",
        "type": "ui-page",
        "name": "Hovi Palju",
        "ui": "8a15abae6f331a3e",
        "path": "/hovipalju",
        "icon": "home",
        "layout": "grid",
        "theme": "c5c72d6ee93d3aaf",
        "order": 1,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "8a15abae6f331a3e",
        "type": "ui-base",
        "name": "Johteenhovi",
        "path": "/dashboard",
        "includeClientData": true,
        "acceptsClientConfig": [
            "ui-notification",
            "ui-control"
        ],
        "showPathInSidebar": false,
        "showPageTitle": true,
        "navigationStyle": "default",
        "titleBarStyle": "default"
    },
    {
        "id": "c5c72d6ee93d3aaf",
        "type": "ui-theme",
        "name": "Dark",
        "colors": {
            "surface": "#3b3b3b",
            "primary": "#0094ce",
            "bgPage": "#a6a6a6",
            "groupBg": "#3b3b3b",
            "groupOutline": "#cccccc"
        },
        "sizes": {
            "pagePadding": "12px",
            "groupGap": "12px",
            "groupBorderRadius": "4px",
            "widgetGap": "12px"
        }
    }
]`

### Environment

- Dashboard version: 1.16.0
- Node-RED version: 4.0.2

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
I think this is a duplicate of #1273, which has been fixed so should be available in the next release.

**Comment by mountain181** [comment]
Fix is provided already, so you can delete the issue

**Comment by colinl** [comment]
@burner- could you close this please if it is fixed in 1.17

**Comment by burner-** [comment]
looks that this is fixed in 1.17.
