### ISSUE TITLE
Configurable Browser Tab Icon

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1327]
Given https://github.com/FlowFuse/node-red-dashboard/issues/1326, the configured icon should now show in the active browser tab for Dashboard 2.0

**Comment by gayanSandamal** [comment]
As per my investigation the browser tab icon (Favicon) should be in ".ico" format and must load the resource from local. Which means the favicon should be in the app directory to use.

Further investigating for alternative options

**Comment by joepavitt** [comment]
Is there anything useful here:

https://github.com/FlowFuse/node-red-dashboard/issues/821

**Comment by gayanSandamal** [comment]
> Is there anything useful here:
> 
> #821

Thanks Joe, it helps with both the online asset loading and mime types

**Comment by joepavitt** [comment]
Closed by #1335
