### ISSUE TITLE
Configurable PWA Icon

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1328]
Given https://github.com/FlowFuse/node-red-dashboard/issues/1326, the configured icon shows when Dashboard is installed locally to a mobile device or laptop.

### Configuring PWA

1. Open Browser on Mobile
2. Navigate to `ipaddress:port/dashboard`
3. Settings > Install (Exact phrasing depends on which phone you've got)

**Comment by gayanSandamal** [comment]
@joepavitt

I’ve tried making the PWA icon dynamic, but unfortunately, it's not something that can be set at runtime like a favicon. PWA icons must be specified at build time, and they only support files in the local directory. External image URLs are not supported.

Also I've [this way](https://stackoverflow.com/questions/50086761/dynamic-icon-pwa-manifest) which was mentioned in the main issue #1144 

We’ll need to generate the icons during the build process and ensure they’re bundled within the application.

**Comment by joepavitt** [comment]
What happened to the option of serving up `manifest` file via the Express server? e.g. https://stackoverflow.com/questions/50086761/dynamic-icon-pwa-manifest

**Comment by joepavitt** [comment]
Yes, it would need to be a local file, but I think that's still an option here, as we can upload local files to Node-RED?

**Comment by gayanSandamal** [comment]
> What happened to the option of serving up `manifest` file via the Express server? e.g. https://stackoverflow.com/questions/50086761/dynamic-icon-pwa-manifest

This works when we have the icons in the public directory itself.

 > Yes, it would need to be a local file, but I think that's still an option here, as we can upload local files to Node-RED?
 
 I will try in this way as well
