### ISSUE TITLE
Multiline text input, the first line text is partially hidden

### ISSUE THREAD

**Issue by ThomasAndreini** [FlowFuse/node-red-dashboard#1329]
### Current Behavior

I inserted a text input node, configured in multiline mode, when I write inside it the first line is partially hidden at the top
<img width="1890" alt="Screenshot 2024-09-25 122052" src="https://github.com/user-attachments/assets/d7702caa-b53e-44f1-99d2-ab6b8842955e">

### Expected Behavior

I expect the first line to be completely visible

### Steps To Reproduce

Add text node to dashboard, set as multiline

### Environment

- Dashboard version: 1.17.0
- Node-RED version: 4.0.3 docker image
- Node.js version:
- npm version:
- Platform/OS: Raspberry PI OS 64bit
- Browser: Chrome 129.0.6668.59

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
This has now been fixed
