### ISSUE TITLE
Cannot install on staging for testing

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#133]
### Description

All flowforge scoped packages on staging get installed from GitHub package manager.

This package needs to add the same mechanism that other packages (e.g. launcher) to make it available to the staging environment,

@hardillb could you direct us on this one pls?

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
@Steve-Mcl I believe this has been resolved now with the devops changes made by @ppawlowski?
