### ISSUE TITLE
Basic query: Is there a gauge that can have a centered differential display?

### ISSUE THREAD

**Issue by houser42** [FlowFuse/node-red-dashboard#1332]
### Description

I hope a very basic query is allowed here?
I am looking at porting a number of NR systems I have maintained over the years that use Dashboard 1.0 and so I am currently learning Dashboard 2.0. Very promising!

The only few basic things I am missing to be able to start porting and migrating is a centered gauge and a smaller or configurable LED.  Are there such things in the pipeline?  I have searched with no luck.

**Comment by bartbutenaers** [comment]
> and a smaller or configurable LED.

See [here](https://flows.nodered.org/node/@flowfuse/node-red-dashboard-2-ui-led)

**Comment by colinl** [comment]
What exactly do you mean by a centred differential display?
[@colinl/node-red-dashboard-2-ui-gauge-classic](https://flows.nodered.org/node/@colinl/node-red-dashboard-2-ui-gauge-classic) can be configured with zero at the centre.

**Comment by houser42** [comment]
Very kind of you to reply. Apologies for unclear question.

Yes, that gauge works, but is a specific design.
Aa tickbox for "centered" in the modern gauge that comes with the flow fuse 2-0package is what I would really want.
Like it is in the v1 one.
This is the setting that V1 gauge that I would use a lot:
<img width="417" alt="Screenshot 2024-09-26 at 12 05 53" src="https://github.com/user-attachments/assets/a9b1528b-e877-49ca-9c8e-d8ad2e495046">
Many thanks!

**Comment by houser42** [comment]
> > and a smaller or configurable LED.
> 
> See [here](https://flows.nodered.org/node/@flowfuse/node-red-dashboard-2-ui-led)

Yes, that one does it. Apart that the normal state is too big. It is unclear to me how to set this from the docs 
 "Size: The relative size of the LED with width x height"
It is not in he settings of the led node itself, so via css payload?  If there is a flow example I would appreciate it.
Many thanks

**Comment by bartbutenaers** [comment]
> apart from the normal state being too big

Yes indeed.  I also use the led's in my new dashboard at home, and I have to admit that they immediately look quite big.
Not sure how you change the height, because they `display: flex` and all kind of other magic CSS stuff.
You can find the code [here](https://github.com/FlowFuse/node-red-dashboard-2-ui-led/blob/main/ui/components/UILed.vue).
