### ISSUE TITLE
Clarify this is the "Dashboard 2" - the successor to node-red-dashboard v1

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#134]
### Description

There is some confusion, even among regulars (See https://discourse.nodered.org/t/how-to-add-a-radio-button-in-node-red/80601/6?u=steve-mcl) as to what dashboard 2 is. 

We should endeavour to make this clearer in the package info.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Think within our documentation and readme now we are sufficiently describing ourself as the successor/v2.
