### ISSUE TITLE
ui-chart: shows data from until now, even if only historical data is provided

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#1347]
### Current Behavior

I send a set of historical data to the chart and it shows the data and left a big empty area until the "now" time:
![grafik](https://github.com/user-attachments/assets/0b0ab208-710f-43ac-83b8-6c2991bdf9b3)

### Expected Behavior

Just plot the data that is inside the chart completly filling the area.
In the past it was like this, but I cannot tell you exactly since what version this error occurs.

### Steps To Reproduce

Please try this flow:
`[{"id":"39c4b3151ba5a5c3","type":"ui-chart","z":"8a529076413cb26a","group":"1aa8388d568444ce","name":"Diagramm","label":"","order":9,"chartType":"line","category":"c","categoryType":"property","xAxisLabel":"","xAxisProperty":"t","xAxisPropertyType":"msg","xAxisType":"time","xAxisFormat":"","xAxisFormatType":"auto","yAxisLabel":"","yAxisProperty":"v","ymin":"","ymax":"","action":"replace","stackSeries":false,"pointShape":"false","pointRadius":4,"showLegend":true,"removeOlder":"24","removeOlderUnit":"3600","removeOlderPoints":"","colors":["#ffff00","#ff8000","#0080c0","#2ca02c","#d62728","#98df8a","#ff9896","#9467bd","#c5b0d5"],"textColor":["#c4c4c4"],"textColorDefault":false,"gridColor":["#e5e5e5"],"gridColorDefault":true,"width":"12","height":"12","className":"","x":1250,"y":800,"wires":[[]]},{"id":"48397a742687565d","type":"inject","z":"8a529076413cb26a","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"[{\"c\":\"PV\"},{\"c\":\"Speicher\"},{\"c\":\"VNB\"},{\"c\":\"Haushalt\"},{\"c\":\"Heizung\"},{\"c\":\"Total\"},{\"c\":\"VNB\",\"t\":1727593265192,\"v\":3},{\"c\":\"Haushalt\",\"t\":1727593272704,\"v\":834},{\"c\":\"Haushalt\",\"t\":1727593294705,\"v\":718},{\"c\":\"Haushalt\",\"t\":1727593305711,\"v\":610},{\"c\":\"Haushalt\",\"t\":1727593316706,\"v\":505},{\"c\":\"Haushalt\",\"t\":1727593327710,\"v\":374},{\"c\":\"Haushalt\",\"t\":1727593338709,\"v\":256},{\"c\":\"Haushalt\",\"t\":1727593349694,\"v\":213},{\"c\":\"Haushalt\",\"t\":1727593376706,\"v\":202},{\"c\":\"PV\",\"t\":1727593378260,\"v\":-991},{\"c\":\"Haushalt\",\"t\":1727593464700,\"v\":192},{\"c\":\"Speicher\",\"t\":1727593477303,\"v\":814},{\"c\":\"Heizung\",\"t\":1727593482133,\"v\":23},{\"c\":\"PV\",\"t\":1727593580268,\"v\":-1053},{\"c\":\"Haushalt\",\"t\":1727593598699,\"v\":182},{\"c\":\"Haushalt\",\"t\":1727593642703,\"v\":172},{\"c\":\"VNB\",\"t\":1727593725277,\"v\":-11},{\"c\":\"Total\",\"t\":1727593725277,\"v\":228},{\"c\":\"Speicher\",\"t\":1727593779255,\"v\":895},{\"c\":\"Haushalt\",\"t\":1727593802702,\"v\":182},{\"c\":\"PV\",\"t\":1727593812292,\"v\":-1114},{\"c\":\"Haushalt\",\"t\":1727593813708,\"v\":289},{\"c\":\"Haushalt\",\"t\":1727593824694,\"v\":400},{\"c\":\"Haushalt\",\"t\":1727593834702,\"v\":502},{\"c\":\"Haushalt\",\"t\":1727593845706,\"v\":622},{\"c\":\"Haushalt\",\"t\":1727593856704,\"v\":736},{\"c\":\"Haushalt\",\"t\":1727593867706,\"v\":811},{\"c\":\"Heizung\",\"t\":1727593903210,\"v\":23},{\"c\":\"PV\",\"t\":1727593926328,\"v\":-1176},{\"c\":\"VNB\",\"t\":1727594039320,\"v\":-9},{\"c\":\"Total\",\"t\":1727594039320,\"v\":272},{\"c\":\"Speicher\",\"t\":1727594111321,\"v\":385},{\"c\":\"PV\",\"t\":1727594134336,\"v\":-1247},{\"c\":\"Haushalt\",\"t\":1727594139705,\"v\":712},{\"c\":\"Haushalt\",\"t\":1727594150706,\"v\":594},{\"c\":\"Haushalt\",\"t\":1727594161706,\"v\":478},{\"c\":\"Haushalt\",\"t\":1727594172710,\"v\":361},{\"c\":\"Haushalt\",\"t\":1727594183702,\"v\":254},{\"c\":\"Haushalt\",\"t\":1727594194692,\"v\":192},{\"c\":\"Heizung\",\"t\":1727594319164,\"v\":23},{\"c\":\"VNB\",\"t\":1727594387336,\"v\":-11},{\"c\":\"Total\",\"t\":1727594387336,\"v\":851},{\"c\":\"Speicher\",\"t\":1727594417358,\"v\":1038},{\"c\":\"PV\",\"t\":1727594434345,\"v\":-1187},{\"c\":\"PV\",\"t\":1727594481375,\"v\":-1273},{\"c\":\"Haushalt\",\"t\":1727594512699,\"v\":177},{\"c\":\"PV\",\"t\":1727594513012,\"v\":-1159},{\"c\":\"PV\",\"t\":1727594523376,\"v\":-1061},{\"c\":\"PV\",\"t\":1727594533394,\"v\":-996},{\"c\":\"PV\",\"t\":1727594544363,\"v\":-942},{\"c\":\"Haushalt\",\"t\":1727594561700,\"v\":187},{\"c\":\"Haushalt\",\"t\":1727594571708,\"v\":199},{\"c\":\"PV\",\"t\":1727594575391,\"v\":-1095},{\"c\":\"PV\",\"t\":1727594585402,\"v\":-1173},{\"c\":\"PV\",\"t\":1727594606455,\"v\":-1269},{\"c\":\"Haushalt\",\"t\":1727594629708,\"v\":189},{\"c\":\"Haushalt\",\"t\":1727594685706,\"v\":178},{\"c\":\"PV\",\"t\":1727594688412,\"v\":-1204},{\"c\":\"PV\",\"t\":1727594699396,\"v\":-1118},{\"c\":\"VNB\",\"t\":1727594733403,\"v\":-12},{\"c\":\"Total\",\"t\":1727594733403,\"v\":68},{\"c\":\"Speicher\",\"t\":1727594735402,\"v\":885},{\"c\":\"Haushalt\",\"t\":1727594738732,\"v\":189},{\"c\":\"Heizung\",\"t\":1727594742999,\"v\":23},{\"c\":\"PV\",\"t\":1727594755406,\"v\":-1261},{\"c\":\"PV\",\"t\":1727594817413,\"v\":-1195},{\"c\":\"Haushalt\",\"t\":1727594845695,\"v\":179},{\"c\":\"PV\",\"t\":1727594859416,\"v\":-1030},{\"c\":\"PV\",\"t\":1727594870404,\"v\":-913},{\"c\":\"PV\",\"t\":1727594880428,\"v\":-784},{\"c\":\"PV\",\"t\":1727594891011,\"v\":-614},{\"c\":\"Haushalt\",\"t\":1727594891701,\"v\":168},{\"c\":\"PV\",\"t\":1727594901471,\"v\":-458},{\"c\":\"Haushalt\",\"t\":1727594910707,\"v\":179},{\"c\":\"PV\",\"t\":1727594924025,\"v\":-543},{\"c\":\"PV\",\"t\":1727594934414,\"v\":-624},{\"c\":\"Haushalt\",\"t\":1727594938692,\"v\":189},{\"c\":\"PV\",\"t\":1727594944430,\"v\":-726},{\"c\":\"PV\",\"t\":1727594955408,\"v\":-858},{\"c\":\"Haushalt\",\"t\":1727594962702,\"v\":200},{\"c\":\"PV\",\"t\":1727594965427,\"v\":-1008},{\"c\":\"PV\",\"t\":1727594975429,\"v\":-1121},{\"c\":\"PV\",\"t\":1727594986409,\"v\":-1209},{\"c\":\"PV\",\"t\":1727594996438,\"v\":-1282},{\"c\":\"PV\",\"t\":1727595017434,\"v\":-1387},{\"c\":\"Speicher\",\"t\":1727595043450,\"v\":1162},{\"c\":\"PV\",\"t\":1727595062500,\"v\":-1484},{\"c\":\"PV\",\"t\":1727595093487,\"v\":-1627},{\"c\":\"VNB\",\"t\":1727595109498,\"v\":-11},{\"c\":\"Total\",\"t\":1727595109498,\"v\":454},{\"c\":\"Heizung\",\"t\":1727595162894,\"v\":23},{\"c\":\"Haushalt\",\"t\":1727595309708,\"v\":214},{\"c\":\"Haushalt\",\"t\":1727595320694,\"v\":327},{\"c\":\"Haushalt\",\"t\":1727595330702,\"v\":436},{\"c\":\"Haushalt\",\"t\":1727595341703,\"v\":551},{\"c\":\"Speicher\",\"t\":1727595349953,\"v\":1019},{\"c\":\"Haushalt\",\"t\":1727595352704,\"v\":664},{\"c\":\"Haushalt\",\"t\":1727595363755,\"v\":777},{\"c\":\"Haushalt\",\"t\":1727595374707,\"v\":822},{\"c\":\"Haushalt\",\"t\":1727595452708,\"v\":781},{\"c\":\"PV\",\"t\":1727595452934,\"v\":-1715},{\"c\":\"VNB\",\"t\":1727595510930,\"v\":-9},{\"c\":\"Total\",\"t\":1727595510930,\"v\":687},{\"c\":\"VNB\",\"t\":1727595547956,\"v\":1},{\"c\":\"Total\",\"t\":1727595547956,\"v\":697},{\"c\":\"PV\",\"t\":1727595563033,\"v\":-1531},{\"c\":\"PV\",\"t\":1727595573888,\"v\":-1393},{\"c\":\"VNB\",\"t\":1727595576898,\"v\":13},{\"c\":\"Total\",\"t\":1727595576898,\"v\":387},{\"c\":\"PV\",\"t\":1727595583903,\"v\":-1198},{\"c\":\"Heizung\",\"t\":1727595585185,\"v\":23},{\"c\":\"Haushalt\",\"t\":1727595594738,\"v\":736},{\"c\":\"PV\",\"t\":1727595594919,\"v\":-1004},{\"c\":\"PV\",\"t\":1727595605892,\"v\":-822},{\"c\":\"VNB\",\"t\":1727595613887,\"v\":2},{\"c\":\"Total\",\"t\":1727595613887,\"v\":-195},{\"c\":\"PV\",\"t\":1727595615939,\"v\":-733},{\"c\":\"Speicher\",\"t\":1727595619897,\"v\":-48},{\"c\":\"PV\",\"t\":1727595626040,\"v\":-656},{\"c\":\"Speicher\",\"t\":1727595629924,\"v\":-117},{\"c\":\"Speicher\",\"t\":1727595647894,\"v\":-105},{\"c\":\"PV\",\"t\":1727595647895,\"v\":-695},{\"c\":\"Haushalt\",\"t\":1727595651704,\"v\":777},{\"c\":\"PV\",\"t\":1727595657906,\"v\":-770},{\"c\":\"Speicher\",\"t\":1727595657906,\"v\":-73},{\"c\":\"Haushalt\",\"t\":1727595675705,\"v\":684},{\"c\":\"Haushalt\",\"t\":1727595686706,\"v\":593},{\"c\":\"Haushalt\",\"t\":1727595697707,\"v\":491},{\"c\":\"Haushalt\",\"t\":1727595708686,\"v\":388},{\"c\":\"PV\",\"t\":1727595711912,\"v\":-682},{\"c\":\"Haushalt\",\"t\":1727595718701,\"v\":268},{\"c\":\"PV\",\"t\":1727595721924,\"v\":-621},{\"c\":\"Haushalt\",\"t\":1727595729695,\"v\":237},{\"c\":\"Haushalt\",\"t\":1727595740701,\"v\":225},{\"c\":\"PV\",\"t\":1727595743917,\"v\":-577},{\"c\":\"PV\",\"t\":1727595807917,\"v\":-615},{\"c\":\"PV\",\"t\":1727595829907,\"v\":-697},{\"c\":\"PV\",\"t\":1727595839932,\"v\":-775},{\"c\":\"PV\",\"t\":1727595850915,\"v\":-879},{\"c\":\"Haushalt\",\"t\":1727595852699,\"v\":237},{\"c\":\"PV\",\"t\":1727595860921,\"v\":-1033},{\"c\":\"PV\",\"t\":1727595870923,\"v\":-1203},{\"c\":\"Haushalt\",\"t\":1727595880706,\"v\":258},{\"c\":\"PV\",\"t\":1727595880934,\"v\":-1409},{\"c\":\"PV\",\"t\":1727595890950,\"v\":-1607},{\"c\":\"PV\",\"t\":1727595901083,\"v\":-1753},{\"c\":\"Haushalt\",\"t\":1727595907698,\"v\":278},{\"c\":\"PV\",\"t\":1727595911915,\"v\":-1919},{\"c\":\"VNB\",\"t\":1727595919927,\"v\":-17},{\"c\":\"Total\",\"t\":1727595919927,\"v\":1975},{\"c\":\"PV\",\"t\":1727595921936,\"v\":-2048},{\"c\":\"Haushalt\",\"t\":1727595959702,\"v\":257},{\"c\":\"Speicher\",\"t\":1727595978924,\"v\":1726},{\"c\":\"Haushalt\",\"t\":1727595995695,\"v\":278},{\"c\":\"Heizung\",\"t\":1727595997418,\"v\":23},{\"c\":\"Haushalt\",\"t\":1727596005704,\"v\":294},{\"c\":\"PV\",\"t\":1727596007950,\"v\":-2196},{\"c\":\"PV\",\"t\":1727596039925,\"v\":-2332},{\"c\":\"Haushalt\",\"t\":1727596048736,\"v\":316},{\"c\":\"PV\",\"t\":1727596091005,\"v\":-2460},{\"c\":\"Speicher\",\"t\":1727596293599,\"v\":2147},{\"c\":\"Haushalt\",\"t\":1727596364701,\"v\":323},{\"c\":\"VNB\",\"t\":1727596390587,\"v\":-10},{\"c\":\"Total\",\"t\":1727596390587,\"v\":303},{\"c\":\"Heizung\",\"t\":1727596416808,\"v\":23},{\"c\":\"PV\",\"t\":1727596437595,\"v\":-2573},{\"c\":\"Haushalt\",\"t\":1727596490689,\"v\":343},{\"c\":\"PV\",\"t\":1727596564675,\"v\":-2727},{\"c\":\"Haushalt\",\"t\":1727596580729,\"v\":369},{\"c\":\"Speicher\",\"t\":1727596594731,\"v\":2395},{\"c\":\"PV\",\"t\":1727596628675,\"v\":-2872},{\"c\":\"VNB\",\"t\":1727596732708,\"v\":6},{\"c\":\"Total\",\"t\":1727596732708,\"v\":483},{\"c\":\"VNB\",\"t\":1727596743679,\"v\":70},{\"c\":\"Total\",\"t\":1727596743679,\"v\":547},{\"c\":\"Haushalt\",\"t\":1727596743697,\"v\":813},{\"c\":\"Haushalt\",\"t\":1727596753701,\"v\":1249},{\"c\":\"Haushalt\",\"t\":1727596764701,\"v\":1719},{\"c\":\"Haushalt\",\"t\":1727596774705,\"v\":2153},{\"c\":\"PV\",\"t\":1727596776796,\"v\":-2666},{\"c\":\"Haushalt\",\"t\":1727596785703,\"v\":2627},{\"c\":\"VNB\",\"t\":1727596791694,\"v\":80},{\"c\":\"Total\",\"t\":1727596791694,\"v\":351},{\"c\":\"Haushalt\",\"t\":1727596796701,\"v\":2935},{\"c\":\"Speicher\",\"t\":1727596797731,\"v\":-354}]","payloadType":"json","x":1090,"y":800,"wires":[["39c4b3151ba5a5c3"]]},{"id":"1aa8388d568444ce","type":"ui-group","name":"Leistung","page":"abcfc8e4f23f361a","width":"12","height":"1","order":1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"abcfc8e4f23f361a","type":"ui-page","name":"Datenbank","ui":"fd06eabec55c4e5d","path":"/database","icon":"database-outline","layout":"flex","theme":"a965ccfef139317a","order":4,"className":"","visible":"true","disabled":"false"},{"id":"fd06eabec55c4e5d","type":"ui-base","name":"Dashboard 2.0","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"navigationStyle":"default","titleBarStyle":"fixed"},{"id":"a965ccfef139317a","type":"ui-theme","name":"Default","colors":{"surface":"#6db046","primary":"#32cd32","bgPage":"#000000","groupBg":"#333333","groupOutline":"#616161"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]`

### Environment

- Dashboard version: v1.7.1
- Node-RED version: v4.0.3
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Firefox 130.0.1 / Win10

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by m-schaeffler** [comment]
This is caused by sending the different lines first without any data:
![grafik](https://github.com/user-attachments/assets/c4d8a51e-85e0-4399-85d8-464d98762f5d)
If I remove these data points, the issue is gone:
![grafik](https://github.com/user-attachments/assets/2dc2d4cf-4e62-4e13-92e8-bcc1d090c00b)
But I cannot control the sequence of the lines any more. I do need to do this, to ensure that every line has always it's defined color!

**Comment by colinl** [comment]
Try sending a message with no topic and payload an empty array after the message with all the topics.  I don't know if it will work but worth trying.

Alternatively, for the message with all the topics, set a very old timestamp which will be off the left side of any real data.

**Comment by colinl** [comment]
For the initial elements which setup the order, specify an old timestamp which will be off the front of the data, or specify the timestamp of the first real sample.  With no timestamp it defaults to the current time so it thinks there is data for 'now'.

**Comment by m-schaeffler** [comment]
> For the initial elements which setup the order, specify an old timestamp which will be off the front of the data, or specify the timestamp of the first real sample. With no timestamp it defaults to the current time so it thinks there is data for 'now'.

I will try this latest on Friday.
