### ISSUE TITLE
@flowfuse/node-red-dashboard-2-ui-led - size settings in GUI?

### ISSUE THREAD

**Issue by houser42** [FlowFuse/node-red-dashboard#1351]
### Description

@flowfuse/node-red-dashboard-2-ui-led - size settings in GUI?

We could really use a setting in the GUI to set the size for this useful node.
As is = large, as well as medium and small.

These option would do for us, but px by px might be appropriate for other people.
Many thanks.

**Comment by joepavitt** [comment]
Thanks @houser42 - we've had this [request on the UI LED repo](https://github.com/FlowFuse/node-red-dashboard-2-ui-led/issues) too, I'll get it added to our development board.
