### ISSUE TITLE
Configure Default Page

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#137]
### Description

When you have multiple pages defined, the router seems to just default to the page created the soonest. We should provide an option to define the "Default" page that would load when a user navigates to the `base` url, without specifying a page.

This option likely makes sense to live at the Dashboard 2.0 side menu (defined in `ui_base.html`), as by toggling on 'default' for one page, we need to affect all other pages, which I think is tricky to conduct from within a single widget's configuration menu.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Hitting circular dependency issues where I want the `ui-base` to provide a selection of a `ui-page` (to define the default page), however, `ui-base` is required by a `ui-page` in order to define where that `ui-page` exists.

**Comment by gemini86** [comment]
This may not be the appropriate place for this type of comment, but it's my opinion that this feature should follow dashboard 1.0's implementation where the page order is determined by the order they listed in the sidebar, and the first parge is always loaded by default (/dashboard). Mentioning just in case this does get worked on in the future. The current work-around is to move all groups and widgets you want on the default page to the one that loads by default (in my case, the most recent page created) and then rename that page.

**Comment by joepavitt** [comment]
Thanks @gemini86 - think you're presenting a very reasonable solution there. Prevents the circular dependency problem we have too.
