### ISSUE TITLE
running old flows against new src causes errors

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#1370]
### Current Behavior

it is possible to get a situation where breakpoints are not defined

![image](https://github.com/user-attachments/assets/326716c0-2184-4ced-b228-5651b8eb5dff)

### Expected Behavior

should guard or provide defaults

### Environment

- Dashboard version: git source
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gayanSandamal** [comment]
> @gayanSandamal can you take this is a high priority please, we'll need this addressed before a release.

I will prioritise this
