### ISSUE TITLE
V1.18.0: Rounded Half Gauge: tiny KPI value

### ISSUE THREAD

**Issue by enqoders** [FlowFuse/node-red-dashboard#1385]
### Current Behavior

Half Gauge - Rounded:  The KPI value (5.4) is tiny and out of proportion compared with the previous version.

<img width="337" alt="image" src="https://github.com/user-attachments/assets/67b54598-dc74-4e00-8c78-f209c761b3db">

### Expected Behavior

The value/unit (24.6) is big and visible
![image](https://github.com/user-attachments/assets/8c200a70-c9d1-4269-81f9-f042c857a01a)

### Environment

Dashboard version: 1.18.0
Node-RED version: 4.0.5
Node.js version: v20.6.0
npm version: 9.8.1
Platform/OS: MacOS
Browser: Chrome Version 128.0.6613.138 (Official Build) (arm64)
 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Problem was introduced in https://github.com/FlowFuse/node-red-dashboard/pull/1353/files#diff-db418d12c562abfca7a5d735428a2e24ac2cd54a3795550187a71f698335474fR396-R409 - fix incoming
