### ISSUE TITLE
Dynamic html needs to be sanetized

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#1387]
Hi guys,

Our friend @dceejay has reviewed my [pull-request](https://github.com/FlowFuse/node-red-dashboard/pull/1382) for html labels.  He correctly mentioned that I needed to sanetize the html.  While implementing a fix, I saw that the same problem does exist in many other places.

The dom-purify library is currently only used for the `v-html` in the ui-markdown node.  But not for the `v-html`  attribute in the following files:
+ [PropsTable.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/docs/components/PropsTable.vue#L14)
+ [EventList.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/docs/components/EventsList.vue)
+ [UIText.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/ui/src/widgets/ui-text/UIText.vue#L5)
+ [ControlsTable.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/docs/components/ControlsTable.vue)
+ [MigrationPropertyTable.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/docs/components/MigrationPropertyTable.vue#L30C66-L32C17)
+ [UIButton.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/ui/src/widgets/ui-button/UIButton.vue#L17)
+ [UINotification.vue](https://github.com/FlowFuse/node-red-dashboard/blob/main/ui/src/widgets/ui-notification/UINotification.vue#L16)

Not sure whether all of these might impose a security risk, but I assume it is better to have a look at all of them.

If you want I can have a look at this...

Bart

**Comment by m-schaeffler** [comment]
👍

**Comment by bartbutenaers** [comment]
This has been implemented for all widgets.  The remaining ones where about the documentation, but that seems not to be a security risk (see PR conversation).  So for me this issue is completed.
