### ISSUE TITLE
V1.18: Stacked bar charts broken

### ISSUE THREAD

**Issue by MartinJura** [FlowFuse/node-red-dashboard#1388]
### Current Behavior

The display of stacked bar charts is broken.
![CleanShot 2024-10-12 at 16 55 37@2x](https://github.com/user-attachments/assets/2cfc0d51-79ce-4703-86a6-d5bbfa5d9349)

### Expected Behavior

Values of a series are properly stacked

### Steps To Reproduce

Use the example for stacked bar charts from the documentation ("financial data"). The screenshot above shows the result.

### Environment

- Dashboard version: 1.18.0
- Node-RED version: 4.0.5
- Node.js version: 
- npm version:
- Platform/OS: Mac OS
- Browser: Safari

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Thanks for raising, I found this myself too, and fixed it in https://github.com/FlowFuse/node-red-dashboard/pull/1386
