### ISSUE TITLE
A way to set fontsizes in the ui-gauge?

### ISSUE THREAD

**Issue by houser42** [FlowFuse/node-red-dashboard#1395]
### Description

Ideally a way to set the various text instances in the ui-gauge in GUI would be nice.
By far most importantly obviously the actual text value inside the gauge in the GUI.
If that is not on the cards, is there a way to set fontsizes in the ui-gauge by CSS?
..and If so, is there an instruction somewhere? Many thanks.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by houser42** [comment]
Many thanks @m-schaeffler  !
Would it be too much to ask where this goes? Is there an example?
I assume into either the css styling in the GUI of the ui.gauge node or in a template node?
I tried in the obvious ways but ny skillset on this is not what it should be.
Would certainly appreciate an example if that is a possibility.

**Comment by m-schaeffler** [comment]
just add a 'ui-template' node:
![Bildschirmfoto vom 2024-10-13 14-08-05](https://github.com/user-attachments/assets/b0c39dad-815f-40b7-989c-3cded84adc60)

    [{"id":"e7dad5fbea401e4e","type":"ui-template","z":"bf934c281a6f35c0","group":"","page":"","ui":"fd06eabec55c4e5d","name":"CSS classes 2.0","order":0,"width":0,"height":0,"head":"","format":"/* Gauge */\n.nrdb-ui-gauge-size-lg .nrdb-ui-gauge-value span {\n  font-size: 2.5rem !important;\n}\n.nrdb-ui-gauge-size-md .nrdb-ui-gauge-value span {\n  font-size: 2rem !important;\n}\n.nrdb-ui-gauge-size-sm .nrdb-ui-gauge-value span {\n  font-size: 1.5rem !important;\n}\n.nrdb-ui-gauge-size-xs .nrdb-ui-gauge-value span {\n  font-size: 1.25rem !important;\n}\n.nrdb-ui-gauge-size-xss .nrdb-ui-gauge-value span {\n  font-size: 1.1rem !important;\n}","storeOutMessages":true,"passthru":false,"resendOnRefresh":true,"templateScope":"site:style","className":"","x":540,"y":620,"wires":[[]]},{"id":"fd06eabec55c4e5d","type":"ui-base","name":"Dashboard 2.0","path":"/dashboard","appIcon":"","includeClientData":false,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false,"showPageTitle":true,"navigationStyle":"default","titleBarStyle":"fixed"}]

**Comment by houser42** [comment]
Many thanks @m-schaeffler 
Truly appreciated! Easy when you know where the code goes ;)

**Comment by houser42** [comment]
Many thanks @m-schaeffler 
Truly appreciated! Easy when you know where the code goes ;)
That looks good and does the job.
