### ISSUE TITLE
v1.18.0: ui-chart group tooltips in highy populated charts

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#1396]
### Current Behavior

the tooltips look like this:
![Bildschirmfoto vom 2024-10-12 12-49-33](https://github.com/user-attachments/assets/c87b465b-2217-49c5-bc04-c0194ce0edf2)
![Bildschirmfoto vom 2024-10-12 12-50-09](https://github.com/user-attachments/assets/da536efc-7cf0-44e6-bebb-d337e94a86c4)
![Bildschirmfoto vom 2024-10-13 12-55-46](https://github.com/user-attachments/assets/61c11171-0930-47b2-b378-8227f336d37a)

### Expected Behavior

perhaps it could only show one data point of each line?

### Steps To Reproduce

fill line chart with lots of data points

### Environment

- Dashboard version: 1.18.0
- Node-RED version: 4.0.5
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
> perhaps it could only show one data point of each line?

Hmm, that's our expected behaviour too. 

Not sure why ChartJS is thinking otherwise. We configured it to read a single point from each series for the matching x-coordinates.

We'll try to reproduce this and get a fix in. Thanks for raising.
