### ISSUE TITLE
Drag in first node creates phantom "unused config nodes" issue

### ISSUE THREAD

**Issue by hotNipi** [FlowFuse/node-red-dashboard#1401]
### Current Behavior

Starting from nothing - drag button into, it is preconfigured.

![image](https://github.com/user-attachments/assets/158d330f-bc2c-4363-bfde-90be208b1dee)

It creates 4 config nodes

![image](https://github.com/user-attachments/assets/395faefd-0a4c-462d-bb4f-2ad8f11763d5)

Everything seems really ok
But if you deploy

![image](https://github.com/user-attachments/assets/f84d8d33-4469-4e4e-899a-4273e67be49d)
![image](https://github.com/user-attachments/assets/76d9399f-8144-462d-9c80-d040fea9b4b3)

It renders on dashboard but unused configs still exist on every deploy.
And there's no clue what the user should do with them.

Refresh the browser tab clears the issue. 

No difference if you have fresh install of the dashboard or if you just clear everything dashboard related to start over.

### Expected Behavior

Adding first node to flow should be seamless. 

### Environment

- Dashboard version: 1.18.0
- Node-RED version: 4.0.2
- Node.js version: 20.14.0
- npm version:
- Platform/OS: Windows 10 
- Browser: Chrome latest

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
There is also a similar issue here i that "UI Link" nodes are never recognised as being used, even though they're "used" by the UI Base
