### ISSUE TITLE
UI Element: Spacer

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1415]
### Description

In the original Dashboard, it was possible to add "Spacers", which would just leave blank white space in the application It meant you had more control over alignment of your elements. 

This would be a config node, and addable via the Dashboard 2.0 side panel.

In the UI itself, it would not render any content within the widget, but just leave it as a blank space. The space should have a width/height option, and nothing else.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### Requested By:

https://app-eu1.hubspot.com/help-desk/26586079/view/233410279/ticket/8321776358/thread/4745614815#live-chat

**Comment by colinl** [comment]
Won't it be redundant once the WYSIWYG editor is released?

**Comment by joepavitt** [comment]
Not necessarily, if I want a widget far-left, and another far-right, withba big space in-between, a space is still appropriate?

**Comment by colinl** [comment]
> With WYSIWYG, we won't be enabling x/y positioning like original Dashboard did

In that case then yes, spacers will be required.

**Comment by colinl** [comment]
I think it would be convenient if spacers could be added from within the WYSIWYG editor, rather than having to close it, add the spacer, and open it again.  Or perhaps this has been considered already.

**Comment by joepavitt** [comment]
> Or perhaps this has been considered already.

It has, but the WYSIWYG editor will be deployed out in phases, so to start with (which is already complicated enough from a coding perspective) it'll just be resizing/reordering groups.
