### ISSUE TITLE
Table: Add "image" cell type

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#1418]
### Description

Originally requested in forums: https://discourse.nodered.org/t/dashboard-2-0-table-image/92558

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by bartbutenaers** [comment]
Does the width and heigth of the images need to be adjustable in the config screen?  Although if you have multiple columns of type 'image', then the settings would be applicable to every column.

**Comment by joepavitt** [comment]
I think we cap the height at `120px` or some arbitrary number for now. 

The other thing we could maybe better support is the use of `:src="item.src"` within the HTML variation.

**Comment by joepavitt** [comment]
Closed by #1422
