### ISSUE TITLE
Add meta specifications to improve functionality on mobile devices

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#142]
### Description

D1 has various meta definitions in the ui web page that improve access on mobile. For example, on Android, if Add to Home Screen is used to add a dashboard shortcut to the home screen then the dashboard appears without the browser address bar, increasing the space available.  I believe this is enabled by
`<meta name="mobile-web-app-capable" content="yes">`
D1 actually provides all of the meta definitions below, but I don't know what they all do.
`<meta name="apple-mobile-web-app-capable" content="yes"> <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"> <meta name="apple-mobile-web-app-title" content="Node-RED"> <meta name="mobile-web-app-capable" content="yes">`

### Have you provided an initial effort estimate for this issue?

I am no FlowForge team member

**Comment by joepavitt** [comment]
https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/88?u=joepavitt

Suggestions that this may not be working as intended, will re-open to investigate

**Comment by joepavitt** [comment]
You're absolutely right, lazy testing on my part, apologies. I'm modifying `index.html`, and changes aren't being taken into affect, even when I change _any_ other meta tags too. Not sure what's going on and needs more investigation.

**Comment by colinl** [comment]
Checking again in v1.0.0 this appears to have been fixed.  I am now seeing the mobile meta data and (on Android) Add to Home Screen provides a shortcut that hides the address bar.  I can't test on an Apple device however.
