### ISSUE TITLE
Bit confused how to handle new dashboard url

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#1436]
Hi guys,

I had last week changed the url to my dashboard, to test my dashboard behind the Tailscale reverse proxy for my latest [tutorial](https://discourse.nodered.org/t/tutorial-secure-your-home-automation-with-tailscale/92849/13).  
1. My url changed from `https:\\<my-virtual-devicename>:1880\dashboard` to `https:\\<my-virtual-devicename>\dashboard`.  
2. But then my pwa app couldn't connect to Node-RED anymore.  
3. When I opened the new url in Chrome and clicked on the *"add to home screen"* menu, I got a message that the app was already installed.  
4. So I had to remove the dashboard app manually.
5. Then I repeated the  *"add to home screen"* again, which installed the app again for the correct url.
6. But I got this message about some name update (and an option to remove the app again):

   ![image](https://github.com/user-attachments/assets/a3f92c15-9732-4789-9779-79dfc5bc470d)

BTW unfortunately not sure anymore when exactly I got the warning.  But same happened on my wife's Android smartphone.

To be honest I have no idea whether my actions were correct.  And also no idea at all what those names mean.  The icon in my home screen shows the text *"Dashboard"* now.

I seem to remember that there was a recent change about names, but can be mistaken.  So not sure if I am perhaps mixing to separate things right now...  Hopefully somebody can illuminate me.

Thanks!
Bart

**Comment by joepavitt** [comment]
So we recently introduced the fact that the PWA's name is driven by the `Name` field in the Dashboard configuration. I suspect your phone has recognised that it's the "same" app, but with a name change?

**Comment by joepavitt** [comment]
When a PWA is installed, it's essentially a browser wrapping the site, so will still point to old URLs, etc. It's all defined int he underlying `manifest.yml` which we serve from Node-RED

**Comment by colinl** [comment]
> the PWA's name is driven by the `Name` field in the Dashboard configuration.

Is that the name field in ui_base?  I tried setting that, Deploying, uninstalling the app on the Android phone and re-installing it.  I don't get any notification like @bartbutenaers saw, but it still shows Dashboard for the app on Android, not the name I configured.

**Comment by colinl** [comment]
What is the url for the manifest?

**Comment by bartbutenaers** [comment]
@joepavitt 
Yes you are right, my icon label has indeed switched:

![image](https://github.com/user-attachments/assets/f6f50415-bdf8-4baf-9543-d5e0ddf79b61)

When I change the name again in the flow editor:

![image](https://github.com/user-attachments/assets/295cffba-a03b-4536-9e1f-526911196900)

Then nothing happens on my Android phone: the name is not updated and I don't get a notification.

So I assume I got the popup when reinstalling the PWA app.  Not sure however...
Perhaps the updated name is only used when the PWA app is being installed.

**Comment by joepavitt** [comment]
That's correct. When you install, that's capturing a point-in-time reference to your Dashboard.

You'll need to be reinstalling the PWA for bame changes to take effect

**Comment by bartbutenaers** [comment]
Ok thanks!
Then anybody with the same silly question can at least find the answer here 😋
