### ISSUE TITLE
UIChart：msg.payload = {x:0, y:0}时，线型图会异常

### ISSUE THREAD

**Issue by ayonge20** [FlowFuse/node-red-dashboard#145]
经查源码，由代码`datapoint.x = payload.x || (new Date()).getTime()`引起

**Comment by joepavitt** [comment]
Can you please share a screenshot and logs of the problem you are seeing please?

**Comment by huxianfeng** [comment]
The flow: 
`[
    {
        "id": "68b5eb4af40bcc6d",
        "type": "tab",
        "label": "流程 3",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "1a3cfb4f6a520eff",
        "type": "function",
        "z": "68b5eb4af40bcc6d",
        "name": "sin",
        "func": "\nif (msg.topic == \"sampling\") {\n    context.set(\"sampling\", msg.payload)\n    if (msg.payload == 1) {\n        /** set x = 0 to reproduce the bug.  */\n        context.set(\"x\", 0)\n\n        // context.set(\"x\", 0.000001)\n        \n        /** clear data */\n        let payload = []\n        node.send({payload});\n    }\n} else {\n    let sampling = context.get(\"sampling\")\n    if (sampling == 1) {\n\n        let x = context.get(\"x\")\n\n        let payload = {x, y:Math.sin(x)}\n\n        node.send({payload});\n\n        context.set(\"x\", x + Math.PI / 30)\n    }\n}\nreturn ;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "context.set(\"smapling\", 0)",
        "finalize": "",
        "libs": [],
        "x": 510,
        "y": 280,
        "wires": [
            [
                "c46acd154dbf8456"
            ]
        ]
    },
    {
        "id": "c46acd154dbf8456",
        "type": "ui-chart",
        "z": "68b5eb4af40bcc6d",
        "group": "09f4e2fb381e5d07",
        "name": "",
        "label": "sin(x)",
        "order": 9007199254740991,
        "chartType": "line",
        "xAxisType": "linear",
        "width": "6",
        "height": "6",
        "x": 730,
        "y": 280,
        "wires": [
            []
        ]
    },
    {
        "id": "143e549cf9ccf519",
        "type": "inject",
        "z": "68b5eb4af40bcc6d",
        "name": "start",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "sampling",
        "payload": "1",
        "payloadType": "num",
        "x": 170,
        "y": 380,
        "wires": [
            [
                "1b2bce7594475b67"
            ]
        ]
    },
    {
        "id": "8674f0d195cf8b7e",
        "type": "inject",
        "z": "68b5eb4af40bcc6d",
        "name": "stop",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "sampling",
        "payload": "0",
        "payloadType": "num",
        "x": 170,
        "y": 440,
        "wires": [
            [
                "1b2bce7594475b67"
            ]
        ]
    },
    {
        "id": "9bf9cbc1c021602e",
        "type": "inject",
        "z": "68b5eb4af40bcc6d",
        "name": "ticker",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "1",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 170,
        "y": 280,
        "wires": [
            [
                "1a3cfb4f6a520eff"
            ]
        ]
    },
    {
        "id": "1b2bce7594475b67",
        "type": "function",
        "z": "68b5eb4af40bcc6d",
        "name": "changeState",
        "func": "let lastState = context.get(\"sampling\")\nif (lastState != msg.payload) {\n    context.set(\"sampling\", msg.payload)\n    node.send(msg)\n}\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "// 部署节点后，此处添加的代码将运行一次。 \ncontext.set(\"sampling\", 0)\n",
        "finalize": "",
        "libs": [],
        "x": 370,
        "y": 400,
        "wires": [
            [
                "1a3cfb4f6a520eff"
            ]
        ]
    },
    {
        "id": "09f4e2fb381e5d07",
        "type": "ui-group",
        "name": "Chart",
        "page": "d2582cbb92e39a42",
        "width": "6",
        "height": "1",
        "order": "",
        "disp": true
    },
    {
        "id": "d2582cbb92e39a42",
        "type": "ui-page",
        "name": "Demo",
        "ui": "b2ee1544453b6c40",
        "path": "/",
        "layout": "grid",
        "theme": "bddf2eaa4eb10def"
    },
    {
        "id": "b2ee1544453b6c40",
        "type": "ui-base",
        "name": "Dashboard",
        "path": "/dashboard"
    },
    {
        "id": "bddf2eaa4eb10def",
        "type": "ui-theme",
        "name": "MyTheme",
        "colors": {
            "surface": "#ffffff",
            "primary": "#0094ce",
            "bgPage": "#eeeeee",
            "groupBg": "#ffffff",
            "groupOutline": "#cccccc"
        }
    }
]`
![sin](https://github.com/flowforge/flowforge-nr-dashboard/assets/3321691/901d5812-6848-4303-b330-8071b5d013f3)

**Comment by huxianfeng** [comment]
![code](https://github.com/flowforge/flowforge-nr-dashboard/assets/3321691/7ad856ae-2187-49ec-836c-3333c86dd617)
![ok](https://github.com/flowforge/flowforge-nr-dashboard/assets/3321691/47cc1511-1899-488e-ab99-865e2a2a6c13)
