### ISSUE TITLE
ui-table returns selected objects of old dataset after data refresh

### ISSUE THREAD

**Issue by domiendecleyn-telenetgroup** [FlowFuse/node-red-dashboard#1452]
### Current Behavior

I input data into the ui-table node, which is set to replace, and I select a row. While the row is selected a new dataset is provided to the ui-table node no longer containing the original items. When I now select a row the original, first, selected row is also returned in msg.payload.

### Expected Behavior

I would expect that after a new dataset is loaded in the ui-table node the selected rows array is reset and only the selected row in the second dataset is returned.

### Steps To Reproduce

Click the First query inject node and select a row in the table. msg.payload will return the selected item. Now while the row is selected click the Second query inject node. The table is refreshed with the new data. Select a row again and observe that msg.payload contains both your first selected row from the old dataset + the last selected row from the last dataset.

`[
    {
        "id": "d711b269e4c137e3",
        "type": "inject",
        "z": "efb13646957c2b34",
        "name": "First query",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "[{\"name\":\"Domien\",\"age\":40},{\"name\":\"Kenny\",\"age\":40},{\"name\":\"Kobe\",\"age\":3}]",
        "payloadType": "json",
        "x": 220,
        "y": 240,
        "wires": [
            [
                "76dda57badaf9934"
            ]
        ]
    },
    {
        "id": "2482760b5dc65326",
        "type": "inject",
        "z": "efb13646957c2b34",
        "name": "Second query",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "[{\"name\":\"Paul\",\"age\":40},{\"name\":\"Thérèse\",\"age\":40},{\"name\":\"Lowie\",\"age\":3}]",
        "payloadType": "json",
        "x": 230,
        "y": 320,
        "wires": [
            [
                "76dda57badaf9934"
            ]
        ]
    },
    {
        "id": "76dda57badaf9934",
        "type": "ui-table",
        "z": "efb13646957c2b34",
        "group": "52228ba0b2a9a710",
        "name": "test issue",
        "label": "text",
        "order": 1,
        "width": 0,
        "height": 0,
        "maxrows": 0,
        "passthru": false,
        "autocols": true,
        "showSearch": true,
        "selectionType": "checkbox",
        "columns": [],
        "mobileBreakpoint": "sm",
        "mobileBreakpointType": "defaults",
        "action": "replace",
        "x": 500,
        "y": 260,
        "wires": [
            [
                "c320daa9eb9f3b74"
            ]
        ]
    },
    {
        "id": "c320daa9eb9f3b74",
        "type": "debug",
        "z": "efb13646957c2b34",
        "name": "debug 80",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 760,
        "y": 260,
        "wires": []
    },
    {
        "id": "52228ba0b2a9a710",
        "type": "ui-group",
        "name": "test",
        "page": "deb0481055d5148d",
        "width": "6",
        "height": "1",
        "order": 1,
        "showTitle": true,
        "className": "",
        "visible": "true",
        "disabled": "false",
        "groupType": "default"
    },
    {
        "id": "deb0481055d5148d",
        "type": "ui-page",
        "name": "test",
        "ui": "30e842843660661c",
        "path": "/page3",
        "icon": "home",
        "layout": "grid",
        "theme": "6e074ddb04f907bf",
        "breakpoints": [
            {
                "name": "Default",
                "px": "0",
                "cols": "3"
            },
            {
                "name": "Tablet",
                "px": "576",
                "cols": "6"
            },
            {
                "name": "Small Desktop",
                "px": "768",
                "cols": "9"
            },
            {
                "name": "Desktop",
                "px": "1024",
                "cols": "12"
            }
        ],
        "order": 1,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "30e842843660661c",
        "type": "ui-base",
        "name": "My Dashboard",
        "path": "/dashboard",
        "includeClientData": true,
        "acceptsClientConfig": [
            "ui-notification",
            "ui-control"
        ],
        "showPathInSidebar": false,
        "showPageTitle": true,
        "navigationStyle": "default",
        "titleBarStyle": "default"
    },
    {
        "id": "6e074ddb04f907bf",
        "type": "ui-theme",
        "name": "Default Theme",
        "colors": {
            "surface": "#ffffff",
            "primary": "#0094CE",
            "bgPage": "#eeeeee",
            "groupBg": "#ffffff",
            "groupOutline": "#cccccc"
        },
        "sizes": {
            "pagePadding": "12px",
            "groupGap": "12px",
            "groupBorderRadius": "4px",
            "widgetGap": "12px"
        }
    }
]`

### Environment

- Dashboard version: 1.19.1 
- Node-RED version: 4.0.3
- Node.js version: v20.17.0
- npm version: 
- Platform/OS: Windows
- Browser: Edge / any

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by bartbutenaers** [comment]
@domiendecleyn-telenetgroup,
I had created a [pull-request](https://github.com/FlowFuse/node-red-dashboard/pull/1470) tonight to solve a similar issue for another user.
I think it will also solve your issue, once it is released/

**Comment by bartbutenaers** [comment]
@domiendecleyn-telenetgroup ,
Could you please let us know whether your problem is meanwhile solved with the last version?

**Comment by domiendecleyn-telenetgroup** [comment]
@bartbutenaers It is indeed fixed with release 1.20.0 which included your fix! Thanks a lot.

**Comment by domiendecleyn-telenetgroup** [comment]
Also closing this one up, if you encounter error please check your version (>= 1.20.0)

**Comment by bartbutenaers** [comment]
@domiendecleyn-telenetgroup 
You are welcome.  Thanks for the confirmation!
