### ISSUE TITLE
Option to control when data is emitted from Dropdown node (Multi-Select Mode)

### ISSUE THREAD

**Issue by fougner33** [FlowFuse/node-red-dashboard#1457]
### Description

In Dashboard 2.0, the dropdown node now emits an array of values for each individual selection or deselection made within the dropdown menu. This can lead to multiple emissions, which may be undesirable in certain scenarios, such as querying a database based on the multi-selection.

I am requesting an option that enables the same behaviour as in Dashboard-1, where the dropdown node in multi-select mode emitted an array of selected values only after the dropdown menu was closed (i.e., when clicking outside the menu). This behaviour allowed users to complete their selection without triggering multiple emissions.

Option 1 (default): Emit values at every selection/deselection (current behaviour in Dashboard 2.0)
Option 2: Emit values only when the dropdown menu is closed/loses focus (previous behaviour in Dashboard-1)

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Tackled by @bartbutenaers in #1458

**Comment by joepavitt** [comment]
Closed by #1458
