### ISSUE TITLE
500 error when layout editor attempts to save changes

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#1473]
### Current Behavior

Open Layout Editor, make changes to layout and attempt to save results in a error 500, and changes not saved.

![dash](https://github.com/user-attachments/assets/f975f72c-6e8d-4f42-a191-b0ccab035238)

and developer console...

![error](https://github.com/user-attachments/assets/35b67921-0311-48e9-a89d-38f1449496e1)

### Expected Behavior

Open Layout Editor, make changes to layout and select save. The changes should then be saved.

### Steps To Reproduce

As above

### Environment

- Dashboard version: 1.19.1
- Node-RED version: 4.0.5
- Node.js version: 20.16
- npm version: 10.8.1
- Platform/OS: Oracle remote cloud server / Canonical-Ubuntu-22.04-aarch64-2023.02.15-0
- Browser: Chrome Version 130.0.6723.119

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
Do you have anything _different_ about your NR setup we should be aware of?

**Comment by Paul-Reed** [comment]
It's pretty much a standard install, and regularly updated, both only using the RP script.
I can't think of anything 'different' from 'out of the box' other than `settings.js` is owned by root & https is enabled.
The dashboard has been used since the very early days of DB2, no errors in logs & no other problems that I'm aware of.
The layout used in that example is 'fixed'.

**Comment by Paul-Reed** [comment]
In the node-red-log, this is what I get when I try and save the changes;

NOTE - Ports & URL's redacted

```
url http://0.0.0.0:redacted/flows
{
  groups: [
    {
      id: '25f065c072b233c0',
      name: 'gauges',
      page: 'd6557c66b0d2c002',
      width: 10,
      height: '6',
      order: 1,
      showTitle: false,
      className: '',
      visible: 'true',
      disabled: 'false',
      groupType: 'default',
      _users: [Array]
    },
    {
      id: '4c637ca6c57dac54',
      name: 'Misc',
      page: 'd6557c66b0d2c002',
      width: '14',
      height: '5',
      order: 2,
      showTitle: false,
      className: '',
      visible: true,
      disabled: 'false',
      _users: [Array],
      groupType: 'default'
    }
  ]
} 7q5s5f2ylyw ae3d4aeb3f977a90
AxiosError: socket hang up
    at AxiosError.from (/home/ubuntu/.node-red/node_modules/axios/dist/node/axios.cjs:876:14)
    at RedirectableRequest.handleRequestError (/home/ubuntu/.node-red/node_modules/axios/dist/node/axios.cjs:3156:25)
    at RedirectableRequest.emit (node:events:519:28)
    at eventHandlers.<computed> (/home/ubuntu/.node-red/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:519:28)
    at Socket.socketOnEnd (node:_http_client:524:9)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/ubuntu/.node-red/node_modules/axios/dist/node/axios.cjs:4287:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ECONNRESET',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json',
      'Content-Type': undefined,
      'Node-RED-API-Version': 'v2',
      cookie: 'cf_clearance=c8MqPTy43kwT75rwTEA8xe1n48w69Tt9RyVl__lVIas-1731751524-1.2.1.1-nKaWQNhjMHrtA77_0saTQRXWGGYakntiWzYvpoNTbfmF2dd16fU2aj8EODTclKOrnE4ln6BHJdAZg3lxPG.AEku0sNzfprDdXV_0OwpsyQQM0WppJekwYhx8YpxGHFbA.ZGvkHbJ97YepXYVV24kJGUvbkr3NEA71RCED3z.TkBeOcokkcWFwtXMMckt_CAGI_cc.TMCPQ_rt36ZI7qdpoqKAhwh2D8dpdm6eywx3kN.tAi.x5UAqb3FuafzzrealwpaLkXyr3vBCPI1hwk.wFT63lIBcfXhpZIIywDOOqF7GigOM_c3iDPCSC71k9cXR2ImbQoNYPo1W4.j8nngf330NDGPsDkgt8qQMzQE8HwKZlfi_8F1VEv.ftCEROYt',
      authorization: 'Bearer RHbuQGLkb6SNTbvbndw/QqeDBt68OTBZcDnRn5tc3roBA8mH44DEH51iMBn6BxLhzKaeZVtL5Hu2wnoBSc6KbI57XpRMbcQdtrZGcStWiB3S+dyHtkdsKw+RkR2OBmGgfEgtR7xQY/w/JD9tyXY8ePuDvGVzdOe1sZrYwVv8unI=',
      referer: 'https://redacted/dashboard/energy?edit-key=7q5s5f2ylyw',
      'User-Agent': 'axios/1.7.7',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://0.0.0.0:redacted/flows',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/flows',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '0.0.0.0',
      port: 'redacted',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/flows'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /flows HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'Node-RED-API-Version: v2\r\n' +
        'cookie: cf_clearance=c8MqPTy43kwT75rwTEA8xe1n48w69Tt9RyVl__lVIas-1731751524-1.2.1.1-nKaWQNhjMHrtA77_0saTQRXWGGYakntiWzYvpoNTbfmF2dd16fU2aj8EODTclKOrnE4ln6BHJdAZg3lxPG.AEku0sNzfprDdXV_0OwpsyQQM0WppJekwYhx8YpxGHFbA.ZGvkHbJ97YepXYVV24kJGUvbkr3NEA71RCED3z.TkBeOcokkcWFwtXMMckt_CAGI_cc.TMCPQ_rt36ZI7qdpoqKAhwh2D8dpdm6eywx3kN.tAi.x5UAqb3FuafzzrealwpaLkXyr3vBCPI1hwk.wFT63lIBcfXhpZIIywDOOqF7GigOM_c3iDPCSC71k9cXR2ImbQoNYPo1W4.j8nngf330NDGPsDkgt8qQMzQE8HwKZlfi_8F1VEv.ftCEROYt\r\n' +
        'authorization: Bearer RHbuQGLkb6SNTbvbndw/QqeDBt68OTBZcDnRn5tc3roBA8mH44DEH51iMBn6BxLhzKaeZVtL5Hu2wnoBSc6KbI57XpRMbcQdtrZGcStWiB3S+dyHtkdsKw+RkR2OBmGgfEgtR7xQY/w/JD9tyXY8ePuDvGVzdOe1sZrYwVv8unI=\r\n' +
        'referer: https://redacted/dashboard/energy?edit-key=7q5s5f2ylyw\r\n' +
        'User-Agent: axios/1.7.7\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 0.0.0.0:redacted\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/flows',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://0.0.0.0:redacted/flows',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: Error: socket hang up
      at Socket.socketOnEnd (node:_http_client:524:23)
      at Socket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
}
```

**Comment by Steve-Mcl** [comment]
Hi Paul.

i see from your screenshot the URL was `xxxxxxxx.co.uk` do you have local access to try this via IP address?


> Platform/OS: Ubuntu 24.04 Cloud 

Where is this running? locally? on a cloud platform? 

Do you have any other devices you can test this on?

**Comment by Paul-Reed** [comment]
> do you have local access to try this via IP address?

No, not without a number of changes (ssh enforced - cloudflare)

> Where is this running? locally? on a cloud platform?

It's a Oracle remote cloud server

> Do you have any other devices you can test this on?

Yes, works fine on a local Raspberry Pi
I also have a 2nd Oracle cloud server which I've just tried, and despite both systems having same versions, there is a different problem with the layout editor...
There were initially minor differences in npm & node versions, so I've update both, to be the same versions, and also updated/dist upgrade both operating systems.
(The main server still presents the same issue originally reported above)

**main server**
Dashboard version: 1.19.1
Node-RED version: 4.0.5
OS Canonical-Ubuntu-22.04-aarch64-2023.02.15-0
Node.js version: v20.18
npm version: 10.8.2

**2nd server**
Dashboard version: 1.19.1
Node-RED version: 4.0.5
OS Canonical-Ubuntu-22.04-aarch64-2023.02.15-0
Node.js  version: v20.18.0
npm v10.8.2

As can be seen below, there are no handles to move individual items around, just one handle which moves the page, and if I attempt to grab one the whole page is moved!!
I've tried chrome incognito and MS Edge browsers.

![loayout](https://github.com/user-attachments/assets/5241e193-4b0e-4b33-912c-15b8d8207349)

![2nd server](https://github.com/user-attachments/assets/3988214d-25b9-45e3-be99-991a415d9dc3)

**Comment by Paul-Reed** [comment]
> do you have local access to try this via IP address?

No, not without a number of changes (ssh enforced - cloudflare)

> Where is this running? locally? on a cloud platform?

It's a Oracle remote cloud server

> Do you have any other devices you can test this on?

I also have a 2nd Oracle cloud server which I've just tried, and get the exact same result.
I've just updated both, to be the same versions, and also updated/dist upgrade both operating systems.

**both servers**
Dashboard version: 1.19.1
Node-RED version: 4.0.5
OS Canonical-Ubuntu-22.04-aarch64-2023.02.15-0
Node.js version: v20.18
npm version: 10.8.2

![2nd server](https://github.com/user-attachments/assets/670948ee-5191-4817-8edd-f2c271fa95d3)

**Comment by bartbutenaers** [comment]
@Paul-Reed ,
I see that @Steve-Mcl has merged some pull requests related to this issue.  
Does this mean your problem is now solved, or am I mistaken?
Thanks!

**Comment by Paul-Reed** [comment]
I haven't closed it because Steve has linked this to close via #1488
But yes, can be closed, issue fixed.

**Comment by Steve-Mcl** [comment]
It should have auto closed when merged to main. 

Closing now.

**Comment by jeroenst** [comment]
I have the same issue but I don't use HTTPS.

<img width="1916" height="916" alt="Image" src="https://github.com/user-attachments/assets/46878abb-a4db-4f1a-999a-9e5c726356a6" />

response : {"error":"Invalid URL"}

Environment
- Node-RED version: 4.1.0
- Node.js version: 20.19.4
- npm version: 10.8.2
- Platform/OS: Linux Synology DSM 7.2
- Browser: Firefox 142.0 & Chrome 139.0.7258.154
- Dashboard 2.0 version: 1.27.1

What is causing this issue, and can it be resolved?

**Comment by joepavitt** [comment]
@jeroenst thanks for raising the issue, do you see any errors in your Node-RED logs alongside this? How are you running/deploying Node-RED?
