### ISSUE TITLE
text node does not show 0

### ISSUE THREAD

**Issue by A380Coding** [FlowFuse/node-red-dashboard#1498]
### Current Behavior

Sending payload with integer 0 to text node will not show anything only sending 0 as string will show 0

### Expected Behavior

show 0 when payload with integer 0 is received

### Steps To Reproduce

Send msg.payload with integer 0 to text node

### Environment

- Dashboard version: 1.19.1
- Node-RED version: 4.0.5
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Firefox

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by bartbutenaers** [comment]
@joepavitt 
I will have a look at this one

**Comment by joepavitt** [comment]
Closed by https://github.com/FlowFuse/node-red-dashboard/pull/1500
