### ISSUE TITLE
Clickable=none should be added

### ISSUE THREAD

**Issue by Subnum12** [FlowFuse/node-red-dashboard#1508]
### Description

Any existing property "Clickable" I like to have an additional "none" option. This is essential to use e.g. a ui-switch as indicator.

![grafik](https://github.com/user-attachments/assets/b2743d1a-f157-4d1a-859a-328d68836139)

Yes, there is a [enabled ](https://dashboard.flowfuse.com/nodes/widgets/ui-switch.html#controls) option already. However, that behavior is differed as it not just disables control but also switches style to disabled/not available (grayed out). 

You maybe consider this while fixing issue [662](https://github.com/FlowFuse/node-red-dashboard/issues/622)

**Comment by bartbutenaers** [comment]
@Subnum12
So that way you get a switch that will look like a normal switch, but you can't click it.  Personally I would find that very confusing.  But on the other hand I would never use that "None" option myself, so it would not bother me either that this new option is available there for users like you that like to have it that way.

I will try to find some time this evening to create a PR.

**Comment by colinl** [comment]
Would not something like the LED indicator be better for this?

**Comment by Tragl1968** [comment]
1) Clickable = None
You may use everything that the dashboard node "switch" already can do
AND you can use another icon, so it looks not like a switch but like a "sign"
vs.
2) LED
You CANNOT use another icon, so you have only the LED itself.
(Or someone has to pimp up the node "LED", so that custom icons are possible like in node "switch")

I would appreciate the option "Clickable = None" in Dashboard 2.0 nodes, where applicable

**Comment by bartbutenaers** [comment]
The option is not making the config screen more complex, because it is hidden in a dropdown.  And even if you open the dropdown, it is an extra option that makes sense between the other available options.  So I don't think it will be of any harm to other users, which won't be using this new option.

**Comment by colinl** [comment]
An alternative, which would be more general, might be a new node type that displays one of a configurable set of icons, where the icon to display is determined by the incoming message.

**Comment by Subnum12** [comment]
>     1. Clickable = None
>        You may use everything that the dashboard node "switch" already can do
>        AND you can use another icon, so it looks not like a switch but like a "sign"

Actual you describe my exact use case. I use switches with material design icons  (e.g. door open/close, pump on/off). 

advantages of "Clickable = None" would be
- no impact on existing behavior/flows
- less implementation work as will you have for a new node (less code required to be maintained)
- a way more flexible as LED's.  Icons often do not require description (open/close door icons speaks for it self - LED likely not)
- personalty I prefer just a few high flexible nodes instead having a lot for just a single use-case . 

@colinl I guess with 2 options (0/1) you can have it with ui-switch requested feature implementation for more options you maybe use `ui-button-group` .Of course that would require request Clickable option to be added here as well. (I'm using ui-button-group with material design icons for air-condition mode heat/cool/dry/off )

**Comment by bartbutenaers** [comment]
Unfortunately I wasn't able to finalize my pull request, due to a CSS issue.  I have [asked](https://github.com/FlowFuse/node-red-dashboard/pull/1511) on Discourse for assistance.  Hopefully somebody jumps in to assist me...

**Comment by bartbutenaers** [comment]
> use ui-button-group .Of course that would require request Clickable option to be added here as well

Personally I don't like that idea.  If you click on the label of a switch then you can toggle it.  But if you click on the label of a button-group (with mire than 2 buttons) then the behaviour will become confusing.

**Comment by Subnum12** [comment]
> > use ui-button-group .Of course that would require request Clickable option to be added here as well
> 
> Personally I don't like that idea. If you click on the label of a switch then you can toggle it. But if you click on the label of a button-group (with mire than 2 buttons) then the behaviour will become confusing.

Actually this FR is about indicator functionality "Clickable = None" so you not supposed to click anywhere. 
Let me show you an example for previously mentioned air condition mode indicator:

![grafik](https://github.com/user-attachments/assets/1b1000b3-5624-4ea4-ba22-310fbcd5c487)

However, using `ui-button-group` for control would be possible today already...
