### ISSUE TITLE
"Clickable=none" does not work for icon == custom

### ISSUE THREAD

**Issue by Tragl1968** [FlowFuse/node-red-dashboard#1521]
### Current Behavior

"Clickable=none" does not work, while using "icon=custom" with an icon. (I used Material Design)

In Dashboard:
If I click on the icon, the icon gets an "endless refresh circle".
Refresh of page does stop the "endless refresh circle".

This looks like "clicking an icon" is ignored by  "Clickable=none"
See #1508

### Expected Behavior

In Dashboard:
If I click on the icon nothing should happen

### Steps To Reproduce

- Create a switch node
- Set Icon to "custom"
- Set Clickable to "none"
--> GO in Dashboard:
- Click on icon, see "endless refresh circle"

### Environment

- Dashboard version: 1.20.0
- Node-RED version: 4.0.3
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by bartbutenaers** [comment]
@Tragl1968 
I have created a pull request with a fix:
https://github.com/FlowFuse/node-red-dashboard/pull/1524

**Comment by joepavitt** [comment]
Closed by #1524
