### ISSUE TITLE
UI Group not loading

### ISSUE THREAD

**Issue by aitor-develop** [FlowFuse/node-red-dashboard#1534]
### Current Behavior

After selecting the page using the left-side toolbar group is not loading. 
![image](https://github.com/user-attachments/assets/6d2bc876-5732-4643-967f-a814479ffd0b)

If the group "TAB" is manually selected, then it displays correctly:
![image](https://github.com/user-attachments/assets/4d70a5b0-90e3-42f7-858e-96561edeb088)

The used layout is TABs.

### Expected Behavior

I expected to see the page with all its widgets loaded correctly when I select in the left-side toolbar.

### Steps To Reproduce

1) Select the page
![image](https://github.com/user-attachments/assets/f6c47eb3-caf4-4b5a-a88e-2887f62103d9)

2) Move to another group in the same page that is not the first one
![image](https://github.com/user-attachments/assets/fb492a26-395c-4b9d-be21-dce1467a70b3)

3) Select a new page with the same display "TAB" from a group that is not the first one
2) Wait to open it and see there is nothing.
![image](https://github.com/user-attachments/assets/d4b7fe80-2f83-4c47-8e6c-a228045aaed5)

3) Click on the group name to see content.
![image](https://github.com/user-attachments/assets/7d052b29-82ad-472e-a02f-41dd15585dcf)

### Environment

- Dashboard version: 1.20.0
- Node-RED version:  4.0.2
- Platform/OS: Dockerized NodeRED
- Browser: Brave v1.73.97

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by Steve-Mcl** [comment]
Can you please provide a minimal flow that demonstrates this issue?

**Comment by bartbutenaers** [comment]
@Steve-Mcl ,
You can assign this one to me.  Will try to have a look tonight...
Bart

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl , You can assign this one to me. Will try to have a look tonight... Bart

Your wish is my command 😉

**Comment by bartbutenaers** [comment]
@aitor-develop 
Thanks a lot for the (very) extensive description and example flow.
Being able to reproduce the problem fast, really helps to be able to help.
You were lucky that the wife and kids were still asleep, so I could have a look at it 😄 

See [pull request](https://github.com/FlowFuse/node-red-dashboard/pull/1552)

**Comment by aitor-develop** [comment]
Hello, I'd like to re-open this issue, I recently updated the dashboard to **1.26.0** and this same issue is back.
@joepavitt @bartbutenaers

**Comment by joepavitt** [comment]
Thanks for flagging this @aitor-develop, we have it written up here: https://github.com/FlowFuse/node-red-dashboard/issues/1784 and will be fixing asap

**Comment by aitor-develop** [comment]
Oh missed it, great! Thanks
