### ISSUE TITLE
Difference between documentation and help text in ui-dropdown

### ISSUE THREAD

**Issue by rucksman** [FlowFuse/node-red-dashboard#1553]
### Current Behavior

The documentation for ui-dropdown states that for dynamic options the syntax should be msg.ui_update.options. Clicking on the "fx" icon in the node itself says one should send msg.options.

### Expected Behavior

Documentation and help text in the node itself show show the same - correct - msg format.

### Steps To Reproduce

Take a look into [documentation](https://dashboard.flowfuse.com/nodes/widgets/ui-dropdown.html) and into [the node itself](https://github.com/FlowFuse/node-red-dashboard/blob/d27fd37b46a1678fc51a60078adaf96499c29e1b/nodes/widgets/ui_dropdown.html#L220https://github.com/FlowFuse/node-red-dashboard/blob/d27fd37b46a1678fc51a60078adaf96499c29e1b/nodes/widgets/ui_dropdown.html#L220)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by bartbutenaers** [comment]
That seems to be a leftover from the early days, when the `msg.ui_update` mechanism wasn't introduced yet.
This [pull request](https://github.com/FlowFuse/node-red-dashboard/pull/1555) should fix it.
