### ISSUE TITLE
Issue: Button do not send a topic after deployment

### ISSUE THREAD

**Issue by gilmiz** [FlowFuse/node-red-dashboard#170]
Button do not send the payload right after flow deployment, but need page refresh (F5) to work.

**Environment:**
- @flowforge/node-red-dashboard v0.3.0
- NR v3.1.0-Beta.4, running on Debian 12.1
- Node v18.17.1
- Browsers: FF 116.03 and Edge 116.0.1938.69
- Platform: Win10

![button_test](https://github.com/flowforge/flowforge-nr-dashboard/assets/16917848/d40afce9-d643-4c1e-906c-99a2034c6c9c)

[button_test.zip](https://github.com/flowforge/flowforge-nr-dashboard/files/12505824/button_test.zip)

**Comment by colinl** [comment]
I am not seeing the problem with the imported flow.

**Comment by joepavitt** [comment]
Hi @gilmiz - thanks for raising, I'll get this added to our list for investigation

**Comment by joepavitt** [comment]
It's even more odd, because the problem happens server-side, but it's the client-side browser (Dashboard) that needs the refresh
