### ISSUE TITLE
Support external/third-party widgets

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#174]
### Description

Dashboard 1.0 supported the ability to utilise third-party UI nodes, e.g. https://flows.nodered.org/node/node-red-node-ui-table

Currently our architecture requires code to leave within our own repo, it only considers widgets found in `/ui`, and not any third-party contributions.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by jtalbourdet** [comment]
For my part, our company was planning to start developing widgets linked to our activity and it would be really useful to be able to do so.

**Comment by joepavitt** [comment]
Thanks @jtalbourdet - I'll bump up the priority on this one. Focussed on charts/data-vis improvements this week, but will be sure to target this soon after.

**Comment by joepavitt** [comment]
If there are any widgets that you think could warrant inclusion in core, also very open to PRs too. Appreciate if you've got company-specific needs too though that they'd need to stay separate.

**Comment by joepavitt** [comment]
Working through this, this morning, and have a lot of feature requirements in my head that I want to get dumped out:

- [x] Write HTML in a third party widget and have that render in Dashboard 2.0 UI
- [x] Call `send()` or `submit()` from that third party HTML
- [ ] Define JS in a third party widget and have that functional client-side
- [ ] Ability to `emit` (via socketio) custom events from client and handle them accordingly on the server-side
- [ ] Ability to define JS dependencies/third-party libraries for the client

**Comment by joepavitt** [comment]
For definition of Controllers, Dashboard 1.0 uses `scope.$eval` in order to pass the Angular Controller scope into the function definitions (see [here](https://github.com/node-red/node-red-dashboard/blob/44ef8c8f83e5f89d3f8b3079f16d034b5fd9c5d7/src/directives/ui-template.js#L31)). This is great as it provides server-side defined code with the `scope` object with which functionality can be flexibly defined.

**Comment by joepavitt** [comment]
Have experimented with adding `.methods` property to the `ui-template` node, and can successfully inject a custom defined VueJS function in my new node:

```js
// code that will run client-side
function test () {
    // because this will get evaluated client-side, we have access to vue/this
    const vue = this
    console.log('custom event handler:')
    console.log(vue.$socket.emit('my-custom-event', this.id, {
        payload: "Test"
    }))
}

// methods that will be available to the widget in the Dashboard
config.methods = {
    test: test.toString()
}   

Note we need to convert to string in order to allow passing via SocketIO, am tempted to move the `.toString()` logic to within the template logic itself so that 3rd party devs don't need to worry about that.

Note also that we have access to `this`/`vue` here, which means we can send _any_ socketio events a developer wants to (having added `$socket` as an injection into the Template `h()` function. The challenge I have now is how I then dynamically add handlers to the `socketio` on the server-side so handle these events.

**Comment by joepavitt** [comment]
So, we have an `evts` argument that can be passed into the `base.register` function when a widget is registered to the `ui-base` config node (normally via a proxy function in `ui-group` or `ui-page`.

Felt like this was a clean place within which to add an `onSocket` object, of which the keys are the event types, and then mapped to the function to run on that event being triggered, e.g:

```js
// server-side event handlers
const evts = {
    onSocket: {
        'my-custom-event': function (id, msg) {
            console.log('my-custom-event', id, msg)
        }
    }
}
    
// inform the dashboard UI that we are adding this node
group.register(node, config, evts)
```

**Comment by bartbutenaers** [comment]
Hi @joepavitt,
Nice to see this feature arriving!

> am tempted to move the .toString() logic to within the template logic itself so that 3rd party devs don't need to worry about that.

I must admit that I have never had a look a this, but I see [here](https://socket.io/blog/introducing-socket-io-1-0/#binary-support) that socket.io also offers support to send binary data.  For example @kevingodell has developed [node-red-ui-mp4frag](https://github.com/kevinGodell/node-red-ui-mp4frag) that has a feature to push mp4 fragments to the old dashboard.  I don't know how has implemented that, but perhaps this kind of stuff might have better performance if you can push binary data?

**Comment by joepavitt** [comment]
Binary data could be an option, will investigate. The `toString()` is my first iteration as then easy to do an `eval()` to parse it at the other end for the function definition

**Comment by joepavitt** [comment]
Node-RED exposes the likes of `jQuery`, `d3js` and a few others via `/vendor/vendor.js` which could be injected into `head` of the Dashboard, _if_ a user so wishes to include it for local/offline development purposes

**Comment by joepavitt** [comment]
> Ability to define JS dependencies/third-party libraries for the client

After chat with DCJ this morning, we agreed the right direction was to focus on getting `ui-template` to support `<head>` injection, which I can now report is working on my local development branch.

Will document properly in my docs, but quick summary is:

```js
config.head = [{
    type: 'script',
    data: {
        defer: 'defer',
        src: 'https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js'
    }
}]
```

would add a `<script defer="defer" src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js">` to the `<head>`
