### ISSUE TITLE
Order of widgets change when node-deploy operated

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#183]
1. add 2 ui-text nodes with text "Item 1" ~ "Item 3"
2. deploy and check they are ordered correctly
3. modify the "Item 1" (add an !exclamation! to text)
4. deploy using node-deploy

![chrome_vdkBWWMbUR](https://github.com/flowforge/flowforge-nr-dashboard/assets/44235289/c359948c-0e0a-4af3-bd14-eeb640803f11)

**Comment by nygma2004** [comment]
I am seeing the same issue. I created some templates, and I started moving them to a new Notebook layout page and also creating some markdown nodes as well for documentation. And the UI is not in sync with what I see in the editor:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/16757620/4e864b60-7041-487d-ba1d-2e7cf6bf0488)
