### ISSUE TITLE
ui-text widget layout value does not respect setting

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#184]
The layout of ui-text widget seems to have no effect on the render.

https://github.com/flowforge/flowforge-nr-dashboard/assets/44235289/0de834ba-94f5-4b4a-a786-67ff87c9d25b

**Comment by colinl** [comment]
I think this used to work, at least for some layout options, but I can confirm it is not working for me too with 0.5.0

**Comment by joepavitt** [comment]
Turns out this was broken in https://github.com/FlowFuse/node-red-dashboard/pull/169 with the removal of:
`:class="'nrdb-ui-text--' + props.layout"` - adding it back in with a new PR
