### ISSUE TITLE
ui-button not sending configured payload

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/node-red-dashboard#213]
When configuring a ui-button to send a given payload when clicked, I'm always getting `msg.payload` set to `undefined`.

<img width="464" alt="image" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/51083/fd3e48bc-902c-4d21-b84e-6672634dbe86">

```
[{"id":"19555cbb6e3b33ae","type":"ui-button","z":"bbd8f94b3531c297","group":"c6c7f87a5a5e5013","name":"","label":"button","order":0,"width":0,"height":0,"passthru":false,"tooltip":"","color":"","bgcolor":"","className":"","icon":"","payload":"hello","payloadType":"str","topic":"topic","topicType":"msg","x":230,"y":460,"wires":[[]]}]
```

**Comment by joepavitt** [comment]
Thanks @knolleary - think this is also the same problem as https://github.com/flowforge/flowforge-nr-dashboard/issues/170 

Does a refresh of the client/browser then work?

**Comment by joepavitt** [comment]
As suspected, this is linked to the fact that the `onAction` (or any equivalent) is running on a `node` object that is no longer in existence within the context of Node-RED.

`onConnection`, we bind multiple event handlers to the `socket` connection: `onAction`, `onChange`, `onLoad`. It appears that we don't clean these up currently upon re-deploy, instead we only clear up the parent `onConnection` event handler. So, when a UI button is clicked, it's being caught by the event handler of the _old_ `node`, not the new.

So two things to consider:

1. How do we cleanly tear down these event handlers on `close` of the `ui-base` node?
2. How do we re-establish these connections and event handlers cleanly such that the UI knows no difference, and behaviour is resumed as if nothing happened?
