### ISSUE TITLE
Set slider from a node-red

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#225]
### Description

I need to be able to initialise the slider value from a `msg` property like dashboard 1 does.

Additionally, programmatically setting the limits is sometimes a necessity. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
If `msg.payload` is set and passed to the slider, then this should set the value accordingly.

**Comment by Steve-Mcl** [comment]
Was this fixed between 0.4 and 0.5? I might have been running old code.

**Comment by joepavitt** [comment]
It's not mentioned in the Release Notes, but I have verified locally, and it does work
