### ISSUE TITLE
Add FileInput widget

### ISSUE THREAD

**Issue by liulysk** [FlowFuse/node-red-dashboard#249]
### Description

It would be nice to have widget which would allow to Drag and Drop JSON files.
Vuetify: https://vuetifyjs.com/en/components/file-inputs/

This msg.payload would return parsed JSON Object and msg.path would return file location in user file system msg.name - name of file
Non JSON files would return raw string.

### Properties

- Label

### Events

- **on-action**: this widget would need to send a message back to Node-RED when it's action is uploaded, e.g. button clicked

### Controls

- **enabled**: this widget can be enabled/disabled
- **visible**: this widget can be hidden

### Existing Examples

https://vuetifyjs.com/en/components/file-inputs/

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Thanks for the detailed feature request. We do also have #44 which is similar, just recording for reference.

The complexity with this one is that Node-RED doesn't always have access to a file system (e.g. when running Node-RED in a Cloud environment), so we'd need someway to (a) know that and (b) have a backup option, or communicate accordingly of we know access isn't possible

**Comment by colinl** [comment]
Is this for uploading files from the machine running the browser, or reading files from the machine running node red?

**Comment by joepavitt** [comment]
My interpretation would be the upload of files from browser device given that NR already has the "file in" node for reading files from the Node-RED host machine?

**Comment by liulysk** [comment]
> My interpretation would be the upload of files from browser device given that NR already has the "file in" node for reading files from the Node-RED host machine?

Correct.

When it is mentioned, it would be ideal to access files from dashboard in machine that is running nodered - similar as in here: https://www.youtube.com/watch?v=3QgK4IAAqcQ

**Comment by joepavitt** [comment]
Closed by https://github.com/FlowFuse/node-red-dashboard/pull/981
