### ISSUE TITLE
UI-Form element lacks input capability: Dynamic CSS class cannot be assigned

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/node-red-dashboard#253]
The ui-form element does not allow for any msg input. Due to this limitation, dynamic CSS classes cannot be assigned to the element.

![Screenshot 2023-10-09 at 20 36 36](https://github.com/FlowFuse/node-red-dashboard/assets/73583313/4bb60fac-be79-4c88-93e5-c5a1c028cd5d)
![Screenshot 2023-10-09 at 20 36 30](https://github.com/FlowFuse/node-red-dashboard/assets/73583313/fd5db4dd-f1dd-4268-b992-4e2455be40b9)

**Comment by tonymacdonald2008** [comment]
Was looking for the ability to set default values for form elements via the input msg.payload as is done in dashboard 1. Is this planned functionality?

**Comment by colinl** [comment]
@tonymacdonald2008  this is covered by similar issue #363

**Comment by jtemple967** [comment]
Would also like to add another vote to this issue. I would like to default the input values on the form.

**Comment by joepavitt** [comment]
Closing to focus this into https://github.com/FlowFuse/node-red-dashboard/issues/1000
