### ISSUE TITLE
Add rows to `ui-table` without Array structure

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/node-red-dashboard#255]
### Description

Say I have a table with 2 column: `foo` and `bar`, I'd like to inject a structure to add one row to the table like:

`msg.payload` = 
```json
{
    "foo": 1,
    "bar": 2
}
```

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
I may even extend this as far as saying something like having `_remove: true` would be a way of removing such an entry too, which is the Cloudant/CouchDB model.

**Comment by joepavitt** [comment]
We should copy the approach used in `ui-chart` now whereby we have an "Action" option which is "Append" or "Replace".
