### ISSUE TITLE
UI-Button: ignores custom CSS classes inserted from flow

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/node-red-dashboard#259]
The UI-Button element in ignoring any custom CSS classes that are programmatically inserted via flow logic. However, manually assigned CSS classes work as expected.

![Screenshot 2023-10-10 at 19 12 36](https://github.com/FlowFuse/node-red-dashboard/assets/73583313/9c161945-b9ec-4d27-b80f-8c51458f9b37)
![Screenshot 2023-10-10 at 19 12 42](https://github.com/FlowFuse/node-red-dashboard/assets/73583313/99212391-03c0-4e73-a543-bff7745533a0)
![Screenshot 2023-10-10 at 19 12 47](https://github.com/FlowFuse/node-red-dashboard/assets/73583313/a43c7f39-6763-4dab-90d4-4191d5cbfe01)

**Comment by colin-grierson** [comment]
I have found the same problem on ui-chart but ui-text works for me
