### ISSUE TITLE
Group css class is not being added

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/node-red-dashboard#272]
Adding a class to a group is currently not working as expected. The ability to apply custom CSS is important for managing the behavior of the group

https://github.com/FlowFuse/node-red-dashboard/assets/110285294/7f6ff63c-594b-4abf-a441-05007549b56b

**Comment by joepavitt** [comment]
Thanks @sumitshinde-84 - also odd that there are two rows for `class` too. Will investigate.

**Comment by joepavitt** [comment]
Closed by #288
