### ISSUE TITLE
Forms Node on NodeRed Dashboard 2.0

### ISSUE THREAD

**Issue by PaserVesPro** [FlowFuse/node-red-dashboard#273]
### Description

I've been testing the new Dashboard 2.0 with the aim to replace the old dashboard version I have, as this has new features and more options.
The forms node allows you different kind of forms options, and by clicking submit the written data should be sent by the node. The problem comes once you have sent data, as I have tried to write new data and submit it but the node won't send any message by its output. The only way I have found to write the forms again, is reloading the dashboard window, but I don't think that's practical. I have tried this on a simple flow, by just adding the forms node and a debugger. I tested it with different types of forms and the result remains the same. 

 The flow JSON code I have used is the folllowing:
[
    {
        "id": "bbad80407c6d0bf2",
        "type": "ui-form",
        "z": "2f82b4f977637196",
        "name": "",
        "group": "7ee511c7f05c05ce",
        "label": "Form",
        "order": 0,
        "width": 0,
        "height": 0,
        "options": [
            {
                "label": "Label 1",
                "key": "User1",
                "type": "checkbox",
                "required": true,
                "rows": null
            },
            {
                "label": "Label 2",
                "key": "User2",
                "type": "multiline",
                "required": true,
                "rows": 3
            }
        ],
        "formValue": {
            "User1": false,
            "User2": ""
        },
        "payload": "",
        "submit": "Send",
        "cancel": "Clear",
        "resetOnSubmit": true,
        "topic": "topic",
        "topicType": "msg",
        "splitLayout": "",
        "className": "",
        "x": 310,
        "y": 160,
        "wires": [
            [
                "8e4abff523e4208d"
            ]
        ]
    },
    {
        "id": "7ee511c7f05c05ce",
        "type": "ui-group",
        "name": "Test Group",
        "page": "49ec4fbe10fdeda9",
        "width": "6",
        "height": "1",
        "order": -1,
        "disp": true
    },
    {
        "id": "49ec4fbe10fdeda9",
        "type": "ui-page",
        "name": "Test Page",
        "ui": "295ddb930f648f43",
        "path": "/",
        "layout": "grid",
        "theme": "fec3f9ad375dc4f2",
        "order": -1
    },
    {
        "id": "295ddb930f648f43",
        "type": "ui-base",
        "name": "UI Test",
        "path": "/dashboard"
    },
    {
        "id": "fec3f9ad375dc4f2",
        "type": "ui-theme",
        "name": "Test Theme",
        "colors": {
            "surface": "#ffffff",
            "primary": "#0094ce",
            "bgPage": "#eeeeee",
            "groupBg": "#ffffff",
            "groupOutline": "#cccccc"
        }
    }
]

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Thanks @PaserVesPro just to clarify here

1. Add form to Flow
2. Deploy
3. Form doesn't transmit data when submitted, only after a browser refresh?

**Comment by joepavitt** [comment]
With #213 and #170 closed out, and re-checking this myself, this issue has been resolved.
