### ISSUE TITLE
page css class is not being added

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/node-red-dashboard#284]
https://github.com/FlowFuse/node-red-dashboard/assets/110285294/219ebd18-3912-413c-9084-9a7c7941d844

**Comment by sumitshinde-84** [comment]
I have tried to fix a class injection issue for a UI page. The class appears in the class field, but the style doesn't get applied

**Comment by joepavitt** [comment]
Good point - thanks @sumitshinde-84 - lazy review/merge on my part. Will get proper fix in now.
