### ISSUE TITLE
Dynamically set the elements of a form

### ISSUE THREAD

**Issue by GrtVHecke** [FlowFuse/node-red-dashboard#287]
### Description

Create the elements in a from by msg. properties

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
For reference, when this work is done, with D1, sending in a payload with the same format as the payload sent by the form when Submit is clicked preloads the form with those contents.

**Comment by GrtVHecke** [comment]
@colinl not only preload the data but also create the contents of the form. This would allow to dynamically create forms.

**Comment by colinl** [comment]
It seems I misunderstood your request.  Dynamically creating the the form itself is a completely different bit of work I think. I have created a separate issue for preloading the contents of the form fields:  #363

**Comment by joepavitt** [comment]
Closing to focus this into https://github.com/FlowFuse/node-red-dashboard/issues/1000
