### ISSUE TITLE
Text Inputs not 48px when a single row in height

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#302]
### Description

Text inputs are coming in at 56px tall, which causes inconsistencies with other component heights when considered 1 "row" tall.

This seems to be driven by CSS on `v-field__input` where `min-height` is set to `max(var(--v-input-control-height,56px),1.5rem + var(--v-field-input-padding-top) + var(--v-field-input-padding-bottom) + var(--v-input-chips-margin-bottom) + 2px);`

Adjustments should be made in the base CSS definitions for Dashboard to override some of these values such that the resulting height is 48px.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by QuanHeMa** [comment]
hi,can you assign this to me?

**Comment by joepavitt** [comment]
@QuanHeMa done

**Comment by joepavitt** [comment]
@QuanHeMa any plans to do this?

**Comment by joepavitt** [comment]
Closed as dormant and resolved
