### ISSUE TITLE
Load an ES6 module in a custom UI node

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#308]
### Description

Hi,

Not sure if this is a feature request, or something existing I did not find...

In the example [code](https://github.com/FlowFuse/node-red-dashboard-example-node/blob/main/nodes/ui-example.js#L18) for a custom UI node, it is explained how to download a regular js file:
```
config.head = [{
   type: 'script',
   data: {
      defer: 'defer',
         src: 'https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js'
      }
}]
```
However I need to import an ES6 module.

I see that the core node do it in their vue file, like e.g. the [button](https://github.com/FlowFuse/node-red-dashboard/blob/main/ui/src/widgets/ui-form/UIForm.vue#L31) widget.  But not sure if that is how the custom ui nodes have to do it.  Or why the `data` property is used in the example ui node, instead of a script tag in my custom vue file.  That is why I created my other [issue](https://github.com/FlowFuse/node-red-dashboard/issues/307), to ask if all nodes (core and custom) could be made lookalike...

Can anybody explain me how to do that?

Thanks!!!
Bart

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
>  why the data property is used in the example ui node, instead of a script tag in my custom vue file.

The main difference here is that anything in the `data` property will be loaded into the browser's `<head>`, whereas including a `<script>` tag in the `vue` component file, whilst it should work, from a performance perspective isn't ideal, as it would load as part of the `<body>` in the browser.

**Comment by joepavitt** [comment]
> However I need to import an ES6 module.

This is a challenge, something I wish I supported at the moment, but fear I do not. I will justify reasoning in https://github.com/FlowFuse/node-red-dashboard/issues/307

**Comment by bartbutenaers** [comment]
Ok, thanks for the clarification!
Is there any reason (e.g. Vue naming convention or something like that) why it is called `data` instead of simply `head`?
Because a lot of data is being passed between backend and frontend too, but that is not why this property is being used for...

**Comment by joepavitt** [comment]
That schema comes from: https://www.npmjs.com/package/@unhead/vue

Which allows us to inject hesd content at the Vue component level

**Comment by bartbutenaers** [comment]
Ok.  Very clear.  Thanks!!!

**Comment by bartbutenaers** [comment]
@joepavitt,
My original question was how to load an ES6 module in a custom UI node.  But it is also not clear to me how the ES6 modules in core UI node are being loaded.

For example via the package.json file gets installed:
```
"devDependencies": {
      ....
      "chart.js": "^4.4.0",
       ...
  },
```
And in the UIchart.vue file:
```
import { Chart } from 'chart.js/auto' 
```
But how does the can find the installed js file to download it.  Or is that shipped via a bundler, of something like that?
Thanks!!

**Comment by joepavitt** [comment]
The dependencies are all installed via the `npm install` step. All installed modules then live in `/node_modules`, and the `import { Chart } from 'chart.js/auto'` statement will look in the `/node_modules` folder for the relevant files

**Comment by joepavitt** [comment]
With our recent `0.8.0` release, where this build process has been completely re-written, I believe we can now close this.
