### ISSUE TITLE
ui-switch malfunctions if on/off payloads are strings

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#311]
To replicate, import the attached flow and then:
1. Click the 'on' and 'off' injects while watching the dashboard UI, the switch correctly switches on and off
2. Click the 'on' and 'off' injects while watching the node's status in the editor.  The node only shows 'on'.
3. Click the off inject to get to the state where the UI shows the switch 'off', but the status shows 'on'.
4. Now click the switch in the UI.  The node should send an 'on' message, but in fact sends an 'off', presumably due to the fact that the internal state is incorrect.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/38307/0021a0e0-3626-4793-9bbc-b734f8e69079)

```
[{"id":"110215ae25dce479","type":"inject","z":"b7344d235f3e066e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"on","payloadType":"str","x":210,"y":780,"wires":[["2af9e1f4faedb5e5"]]},{"id":"2af9e1f4faedb5e5","type":"ui-switch","z":"b7344d235f3e066e","name":"Test switch alpha values","label":"Test switch alpha","group":"ec06ac72ac8562eb","order":0,"width":0,"height":0,"passthru":false,"topic":"topic","topicType":"msg","style":"","className":"","onvalue":"on","onvalueType":"str","onicon":"","oncolor":"","offvalue":"off","offvalueType":"str","officon":"","offcolor":"","x":470,"y":820,"wires":[["ffe6f81a81da5d34"]]},{"id":"7595adbe1da58d19","type":"inject","z":"b7344d235f3e066e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"off","payloadType":"str","x":210,"y":840,"wires":[["2af9e1f4faedb5e5"]]},{"id":"ffe6f81a81da5d34","type":"debug","z":"b7344d235f3e066e","name":"debug 26","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":820,"wires":[]},{"id":"ec06ac72ac8562eb","type":"ui-group","name":"test","page":"46dfd140ddb08ebf","width":"6","height":"1","order":-1,"disp":false},{"id":"46dfd140ddb08ebf","type":"ui-page","name":"Test","ui":"04ee189a49c54f22","path":"/","layout":"grid","theme":"23aa79f4e489b044","order":-1},{"id":"04ee189a49c54f22","type":"ui-base","name":"Dashboard","path":"/dashboard"},{"id":"23aa79f4e489b044","type":"ui-theme","name":"Theme 1","colors":{"surface":"#ffffff","primary":"#514fba","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]
```

**Comment by joepavitt** [comment]
Can only partly reproduce this. 

> 2. Click the 'on' and 'off' injects while watching the node's status in the editor. The node only shows 'on'.

This I can reproduce, and will fix now.

> 4. Now click the switch in the UI. The node should send an 'on' message, but in fact sends an 'off', presumably due to the fact that the internal state is incorrect.

This I do not see currently, I receive the payload I would expect each time, although I will investigate further once I fix 2.

**Comment by joepavitt** [comment]
With 2. it seems to only get out of sync when receiving `msg` inputs, rather than interaction via the Dashboard itself.

**Comment by colinl** [comment]
Something like point 4 is still not right, I have started a new issue for it, #457
