### ISSUE TITLE
Slider outputs all values whilst sliding

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#312]
Whilst moving the slider, it outputs all concurrent values in between the starting value, and the finishing value.
For example, moving the slider from 0 to 5, results in payloads of;

![conc](https://github.com/FlowFuse/node-red-dashboard/assets/973580/b8e0ac14-0a50-4f32-99d4-2dcf8a692c50)
...instead of just a single payload of 5.

I seem to recall that in DB1, there was an option to select;
1) Continuous output
2) Only output when slide completed

The issue with this is that if the slider feeds a flow, it could be triggering the flow 100's or 1,000's times in quick succession, for no end gain.

I have checked DB2 Projects and cannot see this in the backlog etc.

**Comment by joepavitt** [comment]
Thanks Paul, great point and feature request. Will add it to the list.
