### ISSUE TITLE
Slider, payload & topic confusion

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#313]
The output payload from the slider is msg.payload, however this, and the topic is not clear in the config.

Currently, it suggests the when the value is changed, there is an option to send the output as;

![test](https://github.com/FlowFuse/node-red-dashboard/assets/973580/e899bb60-58f1-4b7a-9d68-b2a36509dd52)

However, the output is (and should be) the payload, and therefore the assumption is this defines the output topic, but it does not seem to be the case.

![topic](https://github.com/FlowFuse/node-red-dashboard/assets/973580/aed7f852-1df8-48a6-ad0e-33fb6cc16e25)

I have checked the DB2 Projects backlog for this issue.

**Comment by joepavitt** [comment]
Hi @Paul-Reed thanks for raising the issue.

The topic in your case here would be set to `msg.test`, which can only be something if a message is passed _into_ the slider.

If you want a static topic to emit alongside your payload, you can set it to `string` type, and include a fixed topic that will emit with any slider interaction/changes.

**Comment by Paul-Reed** [comment]
Doh! yes of course setting it to string provides the output topic, it was late when I posted and had been wrestling for some time with (and still do not see what) the functionality of having the options `msg`,  `flow` and `global` are in that dropdown.
I have reinstalled DB1 to see, and that does seem to behave the same, but those options are not described in the node help.
