### ISSUE TITLE
Update readme: remove "flowforge"

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#317]
### Description

readme still states "Install the @flowforge/node-red-dashboard package"

This should be "Install the @flowfuse/node-red-dashboard package"

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
Which readme are we talking about?
Possibly the readme for flowforge@node-red-dashboard should be replaced by one that says don't use this, use the flowfuse one instead.

**Comment by Steve-Mcl** [comment]
Line 13 in this packages' readme: https://github.com/FlowFuse/node-red-dashboard/blob/cc0c8ae3a3ad6967c22ca7777703078ab6e92cd3/README.md?plain=1#L13

**Comment by Steve-Mcl** [comment]
Right, somehow I was looking at the wrong readme!

**Comment by colinl** [comment]
The npmjs page for @flowforge/node-red-dashboard is the problem. It still says to use flowforge.
https://www.npmjs.com/package/@flowforge/node-red-dashboard

**Comment by Steve-Mcl** [comment]
Yes, i think I misunderstood Julian's comment.

That will be sorted when the package is depreciated.

**Comment by colinl** [comment]
OK
