### ISSUE TITLE
Add links to flow locations into the layout panel

### ISSUE THREAD

**Issue by TotallyInformation** [FlowFuse/node-red-dashboard#319]
### Description

It would be great to add a link into the Dashboard 2.0 layout panel that would bring the appropriate node into view in the flows.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/1591850/0fcc85e4-d17a-4342-86b5-dfa53ac1c1b7)

So that you could click a link against one of those inputs and see the node in the flows.

That would really help people better understand and use the link between the flows and the layout panel I think.

You can, of course, edit the node direct from the panel but that doesn't help you find the context of that node in your flow.

As discussed in the forum: https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/204?u=totallyinformation

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Can use `RED.view.reveal('<node-id>')` here
