### ISSUE TITLE
Custom Button-icon and/or dynamic properties

### ISSUE THREAD

**Issue by mreis1986** [FlowFuse/node-red-dashboard#322]
### Description

I would like to be implemented option to insert icon code on button widgets. 
There's any document where I can learn how to work with dynamic properties on button classes ?

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Hi @mreis1986 - we don't _currently_ have that supported. I have added this to our todo list though!

**Comment by mreis1986** [comment]
> Hi @mreis1986 - we don't _currently_ have that supported. I have added this to our todo list though!

great! thanks.

what about dynamic properties, there's is any doc where I can read about it?

**Comment by joepavitt** [comment]
All of our documentation can be found here: https://dashboard.flowfuse.com/nodes/widgets/ui-button.html

We don't currently have many implemented, but when we do, they'll be added to those docs.

We have built in the foundational model (see [here](https://dashboard.flowfuse.com/user/dynamic-properties.html)) but with limited resourcing, I've not been able to implement this widely yet.

**Comment by mreis1986** [comment]
> All of our documentation can be found here: https://dashboard.flowfuse.com/nodes/widgets/ui-button.html
> 
> We don't currently have many implemented, but when we do, they'll be added to those docs.
> 
> We have built in the foundational model (see [here](https://dashboard.flowfuse.com/user/dynamic-properties.html)) but with limited resourcing, I've not been able to implement this widely yet.

awesome. thank you again

**Comment by m-schaeffler** [comment]
for my projects the icon parameter is needed: I have it in around 90% of the buttons.

**Comment by joepavitt** [comment]
Closed by #704
