### ISSUE TITLE
ui-chart Y alingment with Data

### ISSUE THREAD

**Issue by novski** [FlowFuse/node-red-dashboard#324]
### Description

I try to use an ui-chart node in line mode and face a chart starting everytime with Y-Axis 0 going up to my Data.
What i would expect is that the Y-Axis starts where my lowest data point is and goes up to my highest datapoint.
This will give me an way more interessting chart as it lets me distinguish between a couple of datapoints in a similar region.

Dashboard 2.0
![Bildschirmfoto 2023-11-07 um 21 34 03](https://github.com/FlowFuse/node-red-dashboard/assets/6088056/a4f12b32-ebd7-4174-84a5-2abf3468c357)

Dashboard 1.0
![Bildschirmfoto 2023-11-07 um 21 33 52](https://github.com/FlowFuse/node-red-dashboard/assets/6088056/1611642e-e0ee-425f-a77a-be690bdb6ad1)

### Which customers would this be availble to

All Users, (CE)

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Thanks @novski - I've added this to our todo list
