### ISSUE TITLE
ui-dropdown allows keyboard text entry and misbehaves on Android.

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#331]
The dropdown widget allows keyboard entry of arbitrary text after selection, which I don't think it should.  On Android this causes the keyboard to popup when the widget is clicked, making it difficult to use.  The D1 dropdown does not allow keyboard entry.

**Comment by joepavitt** [comment]
Should be closed by https://github.com/FlowFuse/node-red-dashboard/pull/1077 - @colinl to verify

**Comment by colinl** [comment]
Confirm closed by #1077. If Allow Search is disabled in the config then keyboard entry is not allowed and the keyboard does not popup on Android.
