### ISSUE TITLE
Dashboard will not run if multiple pages have the same url

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#334]
If two or more pages have the same url then opening the dashboard shows a warning that this is the case, but, even though it is just a warning, it is impossible to move on to show the dashboard anyway.

This is a regression in 0.7.2, 0.7.1 did show the dashboard even if there were duplicate urls.

**Comment by joepavitt** [comment]
Yes, this is intentional. 

Express servers should not be configured to have multiple pages served at the same address, it would be a lottery on which one gets served.

The warning is intentional and encourages page setup to be configured correctly.

**Comment by colinl** [comment]
I think it should say it is an error then, not a warning.
Also it would be better if the user was prevented from adding a duplicate path while configuring the pages.

> Express servers should not be configured to have multiple pages served at the same address, it would be a lottery on which one gets served.

It worked on on 0.7.1 with them all left at the default of /

**Comment by joepavitt** [comment]
It did work, but it shouldn't have 😁

**Comment by joepavitt** [comment]
I agree re: the warning within NR too, this was a quicker win, and that warning will follow in a future version.

**Comment by colinl** [comment]
Is the validation in the editor in a todo list, or should it be raised as an issue so it doesn't get forgotten?

**Comment by joepavitt** [comment]
Raise please

**Comment by colinl** [comment]
Done: https://github.com/FlowFuse/node-red-dashboard/issues/338
