### ISSUE TITLE
< v-img> breaks on BASE64 injected via msg.payload

### ISSUE THREAD

**Issue by thejollypop** [FlowFuse/node-red-dashboard#340]
### **Description**
The [v-img component](https://vuetifyjs.com/en/components/images/) fails to render BASE64 images that are dynamically loaded via a msg.payload from my application. Instead of displaying the image, it shows a broken image icon. This occurs even though copying the BASE64 string directly in the template works fine. Please look into what may be stripping or corrupting the data when passed from the msg object. A fix is needed to process BASE64 from external sources reliably

### **Steps to reproduce:**
**Example flow:** 

`[{"id":"18b6ea94dbb8f64c","type":"group","z":"f6f2187d.f17ca8","name":"","style":{"fill":"#c8e7a7","label":true},"nodes":["1126bb6ebecd1d2f","92b79118cfabf23a"],"x":114,"y":159,"w":352,"h":122},{"id":"1126bb6ebecd1d2f","type":"ui-template","z":"f6f2187d.f17ca8","g":"18b6ea94dbb8f64c","group":"da785a307679c901","dashboard":"7a32b1c28e93b2d0","page":"03f87e2d8c3eba26","name":"Works","order":0,"width":0,"height":0,"head":"","format":"<v-img :width=\"300\" aspect-ratio=\"16/9\" cover\n    src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAAeFBMVEX///9bW1ucoUKSkpJeXl7c3bzr7Nnu7u5hYWH5+fnDxoxnZ2eXl5fp6enl5s7z8/PR0dG3t7eqqqqorFevs2dzc3O9vb34+fLIyMjY2Nji4uKjqE/R1KikpKR8fHy2uXKEhIR/f3/y8uXX2bK8v3+/w4TMz5/Iy5Z9QVipAAAGuklEQVR4nO1b25aiOhBVwQZGEIgSAUUR7e7//8MDuUAIhRJIus+sNftJo1CbSl1SSbFa/cPfDS90Qu8X5AYRLqwk2dlrAjcpLYTzn2HiZcjarWEkPg7MSnfi0h4R3pIoIlPSQ2y9k06x8zMD4vOJ0pkesGaDiEoF6VQNyNEnPk1UxTdwi1CP+Ow+RzyhgDRMRGDBN7cTq0AoxhjHcWGVI56ZLHYJ7AIPVqJo4O9ejn1opqxFpuAMbS9BL3zMwdaA8C6dLz+VFZug/N01XjrwV2uuJRTSjcqJz+IgiXjyljaEsK9+21e4i4f7FNwZ05D3LcpSzDJe3KcQq8r3evKvM4J7WPRswVe9Pu+ewFWmz25x7elwNoP7/ByP7OUMbDRb/EqypFkMdgtjaShG8hl2kCxfYiGBgazNFHq8MMIpj9+BjmUFFgwBiz/k5Rp4vty3amhd10UdA7vz58ZNk+GfQyLfsmYFz1EGXYbaceWSQFUM/5tS+dZM1x9j0OmgpAPUOwBFx4wAwG0J0l5Q5oscFzAxzAgs8n4AnS+4WRujocCQMwLaqwseD2xh9QbOM1WBjtVkHyy7XcXQCAeZqPCL1ECdGdSukNwF8ZATGgV2pcJSs6G/JyCvMI1VsSCyqyR+bf/kzobjy+J5SOrgYd8qFqzhX8BDQHkjO6FXGAjBFCO1reSEPAlo31vIRyp72QkRI4DBu8wGNPmwExZG0uAqK8b2FmQn5GlQvxmGqQ8U7wMnDKh8X9Ouhnx3LO/tlYP/ZM1aSKUAVIQXITEWAVMdRmlmODjVs8FNwtyTvgOdjd2vySfI0HRnO32IqE7AP6pKI7cBtps+zs+tKPxxI6O3rXTZ/kKw10+gxrF94v2hG+zppjrT0T+T5QTZSBUIENgcTsBvB5HBc6NGwGkCcQFSgAhsvslPe2iwf9FEAiwVg1EQJHAgPx2p7h/bT2odrQpOZ0UC6YtMyAicCKoHu3Eji34+Nn/6Qz62Fve5USTAUzFUDjEC/OsX/Vq1CvhoRiti8h/sP2RqbioE4ukEuq+VMBk9nBrXOG5VCEQvUjGogWP7w2fNZL//EK/4JipSIsCMsIBSkUjgVF3otweXs/nakpk4P1sOH833y0qJwCpsJgGBSwHIC8htqat3kejBLjhSDakRqCkEIyuRIYEDDbs3eZwOfzHLVCUwCoDAF3H4ozxO4kBF5mVllEBNofPCOgBuWUKqJ56OkqCsm8CZoGVwaqeAKJ7aw40Fp313nT4C7NtH97BU6JEOU1qrVUPxWTWgcfK53wMriAUEeJi/cTf8pMPsTydgvpYuCSQC3Pt4KmApkNA6TyfgjGX/9wSOXPNU7U8yeGKsJhIIm+RTTFwXSwSoWCKXxCCag7dscBoBnv2nnSgyAtsGjwtf6XSxuLHz6sAH9y1ohgaNMFMqQ8EFCXluZo+H5+3cDba4tPQG4Juh0zapQAI07j+gwR8hwFd/39DgewJ8CqZtRQwJHDuzerSx8fyQrntBgK3AJhbi+6OA2/PPpbf4qAuTw+Z8eD4GpkYrKrhm8kj219hhoY4w+FXx/084ppug3gE3nVgmtumngp5o2FdkfA/by8G2N+GwvIxNbuCkfh0ChhVIJu2j+qmZ/Tpehw70jNYymtnQbxIeOxj15VvDG6r6Z4OfyslHs87Ihu7aBus1/QTwiPxStzmOTQHcMLa8E2yICDZCqBdtZ+L0pGbQuKEsPwPkG9o3hwPR0Am1T/5ryGd6iZnTs1GEffFuqdzushB9J2zO101oIExRPHImJzphQmLiTv/iIPDH+wI6J9zxQ75Edxpg9Ri4Fm+d0EVdSlDuu3oDXgxA5sWd0ApWeXfCr/l0n+9FWkB4uROBtGdQiAh6+1heaCBsnrqNu8JJr9ZQzLMQYANpL+mGiSEd0B4xKLv7/YbR3NXMgIt0MELgsruUUpPQ9TS/JVi4nXpLohgY70truNqqbWUGYnJc1lLpkSC7jMF6QVdVxGLsQgbzOrOb6NveQp1BLDKwZ70r0etdUWeQ9tqudsqtJdJ7GTPcKesvVBMlCrm0zJ4VUJz+M6x38JkOAPmdHHtma44nv2DgDpbTAIJYLvPmGvGqcyNBDcXLijWIBz1r60XFXQiUTK4Fl835oFOGPP7S6iqC6+akLGIc5XkQ5FmUNi//gW+C6aht4Va4aVB9L2METqHynluHOe9ljFJQ14Kc5RfCGzjXS9h6m9MpouFbVCO4x4Z2gj3Q0SRcY7NbrhEqxxWRFOmP7ILnGFlJj0bz8l9sYFfvJbwgi6I0jbL83+b/X43/AOPJYeN561V9AAAAAElFTkSuQmCC\">\n</v-img>","storeOutMessages":true,"fwdInMessages":true,"resendOnRefresh":true,"templateScope":"local","className":"","x":390,"y":240,"wires":[[]]},{"id":"92b79118cfabf23a","type":"comment","z":"f6f2187d.f17ca8","g":"18b6ea94dbb8f64c","name":"<v-img> with msg.payload - WORKS","info":"","x":290,"y":200,"wires":[]},{"id":"da785a307679c901","type":"ui-group","name":"Group Name","page":"03f87e2d8c3eba26","width":"6","height":"1","order":-1,"disp":true,"className":""},{"id":"7a32b1c28e93b2d0","type":"ui-base","name":"UI Name","path":"/dashboard"},{"id":"03f87e2d8c3eba26","type":"ui-page","name":"Page Name","ui":"7a32b1c28e93b2d0","path":"/","layout":"grid","theme":"60578014b3d343c3","order":-1,"className":""},{"id":"60578014b3d343c3","type":"ui-theme","name":"Theme Name","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}},{"id":"966595811d0b484a","type":"group","z":"f6f2187d.f17ca8","name":"","style":{"fill":"#ffbfbf","label":true},"nodes":["fa9f0b1b062aaf5a","cdd87d3cf9f1f90d","3d06b27a3af0cbc8"],"x":94,"y":299,"w":372,"h":122},{"id":"fa9f0b1b062aaf5a","type":"ui-template","z":"f6f2187d.f17ca8","g":"966595811d0b484a","group":"da785a307679c901","dashboard":"","page":"","name":"Breaks","order":0,"width":0,"height":0,"head":"","format":"<v-img :width=\"300\" aspect-ratio=\"16/9\" cover src=\"msg.payload\"></v-img>","storeOutMessages":true,"fwdInMessages":true,"resendOnRefresh":true,"templateScope":"local","className":"","x":390,"y":380,"wires":[[]]},{"id":"cdd87d3cf9f1f90d","type":"inject","z":"f6f2187d.f17ca8","g":"966595811d0b484a","name":"Base64 Image","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAAeFBMVEX///9bW1ucoUKSkpJeXl7c3bzr7Nnu7u5hYWH5+fnDxoxnZ2eXl5fp6enl5s7z8/PR0dG3t7eqqqqorFevs2dzc3O9vb34+fLIyMjY2Nji4uKjqE/R1KikpKR8fHy2uXKEhIR/f3/y8uXX2bK8v3+/w4TMz5/Iy5Z9QVipAAAGuklEQVR4nO1b25aiOhBVwQZGEIgSAUUR7e7//8MDuUAIhRJIus+sNftJo1CbSl1SSbFa/cPfDS90Qu8X5AYRLqwk2dlrAjcpLYTzn2HiZcjarWEkPg7MSnfi0h4R3pIoIlPSQ2y9k06x8zMD4vOJ0pkesGaDiEoF6VQNyNEnPk1UxTdwi1CP+Ow+RzyhgDRMRGDBN7cTq0AoxhjHcWGVI56ZLHYJ7AIPVqJo4O9ejn1opqxFpuAMbS9BL3zMwdaA8C6dLz+VFZug/N01XjrwV2uuJRTSjcqJz+IgiXjyljaEsK9+21e4i4f7FNwZ05D3LcpSzDJe3KcQq8r3evKvM4J7WPRswVe9Pu+ewFWmz25x7elwNoP7/ByP7OUMbDRb/EqypFkMdgtjaShG8hl2kCxfYiGBgazNFHq8MMIpj9+BjmUFFgwBiz/k5Rp4vty3amhd10UdA7vz58ZNk+GfQyLfsmYFz1EGXYbaceWSQFUM/5tS+dZM1x9j0OmgpAPUOwBFx4wAwG0J0l5Q5oscFzAxzAgs8n4AnS+4WRujocCQMwLaqwseD2xh9QbOM1WBjtVkHyy7XcXQCAeZqPCL1ECdGdSukNwF8ZATGgV2pcJSs6G/JyCvMI1VsSCyqyR+bf/kzobjy+J5SOrgYd8qFqzhX8BDQHkjO6FXGAjBFCO1reSEPAlo31vIRyp72QkRI4DBu8wGNPmwExZG0uAqK8b2FmQn5GlQvxmGqQ8U7wMnDKh8X9Ouhnx3LO/tlYP/ZM1aSKUAVIQXITEWAVMdRmlmODjVs8FNwtyTvgOdjd2vySfI0HRnO32IqE7AP6pKI7cBtps+zs+tKPxxI6O3rXTZ/kKw10+gxrF94v2hG+zppjrT0T+T5QTZSBUIENgcTsBvB5HBc6NGwGkCcQFSgAhsvslPe2iwf9FEAiwVg1EQJHAgPx2p7h/bT2odrQpOZ0UC6YtMyAicCKoHu3Eji34+Nn/6Qz62Fve5USTAUzFUDjEC/OsX/Vq1CvhoRiti8h/sP2RqbioE4ukEuq+VMBk9nBrXOG5VCEQvUjGogWP7w2fNZL//EK/4JipSIsCMsIBSkUjgVF3otweXs/nakpk4P1sOH833y0qJwCpsJgGBSwHIC8htqat3kejBLjhSDakRqCkEIyuRIYEDDbs3eZwOfzHLVCUwCoDAF3H4ozxO4kBF5mVllEBNofPCOgBuWUKqJ56OkqCsm8CZoGVwaqeAKJ7aw40Fp313nT4C7NtH97BU6JEOU1qrVUPxWTWgcfK53wMriAUEeJi/cTf8pMPsTydgvpYuCSQC3Pt4KmApkNA6TyfgjGX/9wSOXPNU7U8yeGKsJhIIm+RTTFwXSwSoWCKXxCCag7dscBoBnv2nnSgyAtsGjwtf6XSxuLHz6sAH9y1ohgaNMFMqQ8EFCXluZo+H5+3cDba4tPQG4Juh0zapQAI07j+gwR8hwFd/39DgewJ8CqZtRQwJHDuzerSx8fyQrntBgK3AJhbi+6OA2/PPpbf4qAuTw+Z8eD4GpkYrKrhm8kj219hhoY4w+FXx/084ppug3gE3nVgmtumngp5o2FdkfA/by8G2N+GwvIxNbuCkfh0ChhVIJu2j+qmZ/Tpehw70jNYymtnQbxIeOxj15VvDG6r6Z4OfyslHs87Ihu7aBus1/QTwiPxStzmOTQHcMLa8E2yICDZCqBdtZ+L0pGbQuKEsPwPkG9o3hwPR0Am1T/5ryGd6iZnTs1GEffFuqdzushB9J2zO101oIExRPHImJzphQmLiTv/iIPDH+wI6J9zxQ75Edxpg9Ri4Fm+d0EVdSlDuu3oDXgxA5sWd0ApWeXfCr/l0n+9FWkB4uROBtGdQiAh6+1heaCBsnrqNu8JJr9ZQzLMQYANpL+mGiSEd0B4xKLv7/YbR3NXMgIt0MELgsruUUpPQ9TS/JVi4nXpLohgY70truNqqbWUGYnJc1lLpkSC7jMF6QVdVxGLsQgbzOrOb6NveQp1BLDKwZ70r0etdUWeQ9tqudsqtJdJ7GTPcKesvVBMlCrm0zJ4VUJz+M6x38JkOAPmdHHtma44nv2DgDpbTAIJYLvPmGvGqcyNBDcXLijWIBz1r60XFXQiUTK4Fl835oFOGPP7S6iqC6+akLGIc5XkQ5FmUNi//gW+C6aht4Va4aVB9L2METqHynluHOe9ljFJQ14Kc5RfCGzjXS9h6m9MpouFbVCO4x4Z2gj3Q0SRcY7NbrhEqxxWRFOmP7ILnGFlJj0bz8l9sYFfvJbwgi6I0jbL83+b/X43/AOPJYeN561V9AAAAAElFTkSuQmCC","payloadType":"str","x":220,"y":380,"wires":[["fa9f0b1b062aaf5a"]]},{"id":"3d06b27a3af0cbc8","type":"comment","z":"f6f2187d.f17ca8","g":"966595811d0b484a","name":"<v-img> with msg.payload - NOT","info":"","x":270,"y":340,"wires":[]}]`

### **Expected behavior**
The v-img component should process the valid BASE64 image string contained in the msg.payload and display the corresponding image.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
In your template where you have the dynamically injected `src`, for Vue to realise it's a dynamic proeprty, you need to add a `:` before the `src`, so your template would become:

```vue
<v-img :width="300" aspect-ratio="16/9" cover :src="msg.payload"></v-img>
```

Thanks for raising this though, as you've also uncovered that I've broken `ui-template `entirely in `main` branch with the new build pipelines! (not affecting any release yet)

**Comment by jerryhoy** [comment]
I'm experiencing this same problem. Has this been fixed?

**Comment by joepavitt** [comment]
@jerryhoy code written in a Dashboard 1.0 (AngularJS-based) template will not immediately work in 2.0 (now VueJS based)

You can see an example above: https://github.com/FlowFuse/node-red-dashboard/issues/340#issuecomment-1812892240
