### ISSUE TITLE
Form widget should send Number type fields as Numbers not strings

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#342]
On D1 the Form node sends fields that are of type Number as Numbers.  With D2 they are sent as strings.  Ideally they should be numbers I think.

**Comment by tonymacdonald2008** [comment]
Also noticed that number fields that are left blank are sent correctly as number 0 even those explicitly set to 0 are sent as "0".

**Comment by colinl** [comment]
Also it is annoying that number fields default to showing `0` which gets in the way when one comes to enter a value, particularly on a touchscreen device. I would argue that the field should initially be empty.

**Comment by colinl** [comment]
> Also noticed that number fields that are left blank are sent correctly as number 0

Actually, if the field is left at the initial default value, showing 0, then number 0 is sent, but if that is erased so that the field is empty, it is sent as an empty string.
