### ISSUE TITLE
Switch label uses the wrong colour (arguably)

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#347]
The Switch widget label displays in a paler colour than, for example, the Text widget label. I think the defaults should be the same.
For example:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/38307/10efe2c6-9e18-4f9f-b307-d31ea913ff51)

**Comment by joepavitt** [comment]
Thanks Colin, good spot.

**Comment by joepavitt** [comment]
It's actually the text that's the problem, all other components use Vuetify styling, the text component is custom-built doesn't doesn't use same font/weight
