### ISSUE TITLE
Default Page Path to /<page name> if left blank

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#348]
### Description

A feature suggestion - that if the page path is left empty that it defaults to /page_name, sanitised as appropriate.

### Have you provided an initial effort estimate for this issue?

I am not a flowfuse employee

**Comment by joepavitt** [comment]
It is perfectly valid though for a page to have no extension if you only have one page?

**Comment by colinl** [comment]
You could insist that the user enters `\` for the path in this case .

**Comment by joepavitt** [comment]
I'm just about to deliver something for this, not quite as requested, but when creating a new page, rather than offering a default path of `/`, it instead counts the number of `ui-page` nodes (`N`), and then sets the default path to `/pageN`. This ensures the default values never overlap
