### ISSUE TITLE
ui-template support for disabling msg passthrough

### ISSUE THREAD

**Issue by i8beef** [FlowFuse/node-red-dashboard#354]
### Description

Evaluating for a move over from dashboard 1 for gaps, and wanted to supply a few things I found around the template node (and Im assuming also the ui-markdown node).

1. The node seems to automatically pass through all msg's coming in to the output. I would like to see an option to disable this, so that you can use this to build custom controls where current state can always be passed in, and then the UI through the `send()` function can manage all output. Without this, such control schemes are prone to loops (output loops back to input, ad nauseum).
2. Message sent from the `send()` method seem to strip at least the "topic" of the msg object specified. ie, `send({topic: 'myTopic', payload: 'values' })` just gets a message like `{ payload: 'values' }` coming out. I really think whatever is blocking this should be looked at, its much easier to generate full msg's to send through to things like MQTT, etc.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
> 2. Message sent from the send() method seem to strip at least the "topic" of the msg object specified. ie, send({topic: 'myTopic', payload: 'values' }) just gets a message like { payload: 'values' } coming out.

That is not intentional, will take a look at that.

**Comment by joepavitt** [comment]
>  1. I would like to see an option to disable this, so that you can use this to build custom controls where current state can always be passed in, and then the UI through the send() function can manage all output. 

Great point

**Comment by joepavitt** [comment]
Requested here too: https://discourse.nodered.org/t/ui-template-feedback-thoughts/83579/11
