### ISSUE TITLE
Documentation for chart bar graph

### ISSUE THREAD

**Issue by colin-grierson** [FlowFuse/node-red-dashboard#355]
I'm trying to pass a set of data points to a chart to be displayed as a bar graph. I have found chart documentation at https://dashboard.flowfuse.com/nodes/widgets/ui-chart.html - this gives instructions and examples for how to pass data for line and scatter graphs - and a picture of a bar graph :-(
Where can I find instructions and examples for how to pass data to a bar graph?
Apologies if this is not the correct place for this question - please direct me to the correct forum if so
Thanks for your help, Colin

**Comment by joepavitt** [comment]
Thanks @colin-grierson - the perfect place to raise this. Will get some docs added for you soon.
