### ISSUE TITLE
Chart: Append/Replace Data Option

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#358]
### Description

By default, we assume that any newly received data into `ui-chart` should be appended to the existing data on the chart, however, in the case of showing API data for example, we may actually just want to replace the entire dataset with the newly received data.

Whilst this can be achieved by sending a `[]` msg to the chart to clear data, a lower-code approach would be to provide a configuration option on the chart itself which provided the option to _"Append"_ or "Replace", maybe even being able to define this as a `TypedInput`, so that we can control it on a msg by msg basis.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
I think it may be more important that it is available as a msg property than as a config item.  It is common to preload the chart with historical data and then add further data in real time.

**Comment by joepavitt** [comment]
Great point Colin. Node-RED's TypedInputs would allow for this. Example below of how we do this for defining the `topic`:

<img width="452" alt="Screenshot 2023-11-21 at 09 52 26" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/e48483de-8f93-4bc0-bf76-a2af908bbf14">

**Comment by joepavitt** [comment]
This has now been requested by multiple people, bumping up the priority

**Comment by colin-grierson** [comment]
My thoughts as a very new Node-red dashboard user
We should have consistency 
- The chart and table nodes are inconsistent. Given a set of data, chart updates/appends while table replaces existing data
- I think updating/appending is natural when each message contains one value, and replacing existing data is natural when a set of values are sent 
Having an explicit control in the configuration object is a great idea - it makes everything obvious
Allowing control via message properties is also a great idea
Ideally all controls should be able to be overridden via message properties
Having controls that are only in the message properties is not so good as they are not obvious and it can be hard to find the option exists
Why is the editor help so much different to the documentation at https://dashboard.flowfuse.com/nodes/XXXXXXXXX.html?
- If it adds too much work to make this happen, how about a link in the editor help to go to the much more complete documentation at flowfuse.com?

I really appreciate what you guys are doing
Regards, Colin

**Comment by joepavitt** [comment]
> The chart and table nodes are inconsistent. Given a set of data, chart updates/appends while table replaces existing data

Very good point - we could/should also have this feature added to table for consistency.

> Why is the editor help so much different to the documentation at

Two reasons:

1. The template for that help docs is a little more limited in terms of the content we can render (e.g. images, and general screen real estate) so we have to have mostly text-driven docs in-Editor.
2. Laziness/Slack on my part where I often forget to update the in-Editor docs. I generally focus on the hosted docs as I can be considerably more verbose and descriptive with examples, etc. there.

> If it adds too much work to make this happen, how about a link in the editor help to go to the much more complete documentation at flowfuse.com?

It's not too much, but definitely a laziness on my part. Linking to the online docs is a great idea though, but I do need to get the Editor help text updated, as Node-RED is regularly used in constrained environments where access to the general Internet isn't guaranteed.
