### ISSUE TITLE
Switch widget should accept msg.enabled true/false to enable it, as D1 does.

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#366]
### Description

The Switch widget should accept msg.enabled true or false to enable/disable its operation.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Just to clarify here, if you send a `msg.payload` to a `ui-switch`, the toggle will set to the "on" state. If you send `false`, it will set to the "off" state.

If you're looking to enable/disable operation, that would be utilising something like `msg.enabled = true` which is currently not supported - but can be, and I _think_ is what you're asking for?

**Comment by colinl** [comment]
> If you send `false`, it will set to the "off" state.

Actually, I believe that it is the configured on and off payloads that you have to pass in to set the switch.  However, here I am not talking about the on/off state of the switch, but whether it is enabled or not, in the same way a button can be enabled/disabled.  

> If you're looking to enable/disable operation, that would be utilising something like `msg.enabled = true`

Yes, exactly.  D1 uses msg.enabled for switches in the same way it does for buttons, text input fields etc.  I think any node that allows user input should have this feature (or at least those that do in D1).

**Comment by joepavitt** [comment]
> D1 uses msg.enabled for switches in the same way it does for buttons

In which case, I believe there is a typo in the initial issue description 😄 as you said `msg.payload` to control enabled/disabled state.

**Comment by colinl** [comment]
> I believe there is a typo in the initial issue description

Doh, yes you are right.  I got it right in the title but then brain fade set in for the description.
I will edit it.  Sorry for wasting your time.
