### ISSUE TITLE
Upload data via <v-file-input> and sending to NR

### ISSUE THREAD

**Issue by thejollypop** [FlowFuse/node-red-dashboard#369]
### Description

Hi @joepavitt :)I've been trying to upload an image buffer data using 'v-file-input' and then send it back to Node-Red (as in [this example](https://www.bezkoder.com/vuetify-image-upload-preview/)), but I'm having trouble achieving this. Is there currently a way to accomplish this task, or is it under development? I'm currently stuck and would appreciate any guidance. Thanks! 

Here's my flow:
  `[{"id":"ec1a1a728929b52f","type":"ui-template","z":"f6f2187d.f17ca8","group":"8f96c8a8cd1167fe","dashboard":"","page":"","name":"Upload","order":2,"width":0,"height":0,"head":"","format":"<v-file-input show-size multiple chips  :rules=\"rules\" accept=\"image/png, image/jpeg, image/bmp\"\n  prepend-icon=\"mdi-camera\" variant=\"underlined\" label=\"File input\" v-on:change=\"uploadFile\"   ></v-file-input>\n\n<script>\n  export default {\n    data: () => ({\n      rules: [\n        value => {\n          return (\n            !value ||\n            !value.length ||\n            value[0].size < 2000000 ||\n            'Avatar size should be less than 2 MB!'\n          )\n        },\n      ],\n    }),\n  }\n\n\nmethods: {\n  uploadFile(event) {\n    const file = event.target.files[0];\n    // Do something with the file buffer\n  }\n}\n\n</script>\n\n\n","storeOutMessages":true,"fwdInMessages":true,"resendOnRefresh":true,"templateScope":"local","className":"","x":360,"y":1520,"wires":[["92be470d1f3dcdfa"]]},{"id":"8f96c8a8cd1167fe","type":"ui-group","name":"Group Name","page":"97f11ee462ebc471","width":"12","height":"1","order":-1,"disp":false,"className":""},{"id":"97f11ee462ebc471","type":"ui-page","name":"Upload Example","ui":"6df09aad9a7a43bd","path":"/","layout":"grid","theme":"915cb05c7306f91c","order":-1,"className":""},{"id":"6df09aad9a7a43bd","type":"ui-base","name":"UI Name","path":"/dashboard"},{"id":"915cb05c7306f91c","type":"ui-theme","name":"Theme Name","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]`

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Thanks for raising @thejollypop - will try and take a look today

**Comment by joepavitt** [comment]
@thejollypop worth noting the `<script>` tag you've used in your template, _currently_ doesn't do anything. The leg work you've got here is being handled in the `@update:modelValue`.

I am hoping to allow for more verbose definition of Vue components shortly with #115 though
