### ISSUE TITLE
Slider "Show thumb label" addition

### ISSUE THREAD

**Issue by i8beef** [FlowFuse/node-red-dashboard#372]
### Description

It appears that the underlying vue.js control for the slider allows for a boolean OR `always` for `thumb-label`. I would love to be able to set it to this third value so the slider is ALWAYS displaying the current value. I would assume this would require changing the "Show thumb labels" setting to a dropdown or radio for the third value?

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Just to summarise the request here:

**before:** true/false
**after:** true/false/always

**Comment by i8beef** [comment]
Yessir, if I'm reading the docs for vuetify right... basically I'd like to be able to see the current value for any slider, and that seemed to fit with the old dashboard's setting to always show the value "thumb".

**Comment by i8beef** [comment]
Just adding a link to the docs on this: https://vuetifyjs.com/en/components/sliders/#thumb

This will allow you to see what the actual numeric value currently is / will be when released, etc. and would make the sliders easier to use overall.

**Comment by i8beef** [comment]
Thank you that works for the thumb!

FYI though I think we might have a regression in "step", it doesn't seem to work anymore.

**Comment by joepavitt** [comment]
Thanks for flagging, I can see the problem, will fix it in the next couple of hours

**Comment by i8beef** [comment]
Looks good again, thank you!
