### ISSUE TITLE
UI Button: Colors

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#375]
### Description

Dashboard 1.0 offers customisation on the text and background colour of the button. Dashboard 2.0 should do this too.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by m-schaeffler** [comment]
I changed all my buttons (still dashboard 1) so that they now use css classes and no more the two color options.

So from  my point of view these two parameters are no longer needed; also they does not really fit in to the whole concept.
