### ISSUE TITLE
Dynamic Visibility

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#377]
### Description

An epic to capture the wider piece of work of developing a consnistent framework by which _any_ widget or group can be made visible/hidden.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
First iteration of this is captured within #258

**Comment by joepavitt** [comment]
As a follow up - the option then send messages _directly_ to a node with something like `msg.visible = true`

**Comment by joepavitt** [comment]
@MarianRaphael fyi `ui-control` in Dashboard 1.0 _only_ controls visibility of Groups, it does not allow for control of individual widgets.

**Comment by MarianRaphael** [comment]
@joepavitt which should be fine for a version 1.0

**Comment by joepavitt** [comment]
Our [0.9.0 Release](https://github.com/FlowFuse/node-red-dashboard/releases/tag/v0.9.0) contains control over this on a page-by-page and group-by-group basis.
