### ISSUE TITLE
UI Chart - X Axis Label

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#382]
### Description

We are missing the ability to define the x-axis label for a chart (available in Dashboard 1.0)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by riprock67** [comment]
Just pinging this to see if there has been any progress.  Y-labels would be a nice bonus!  Thanks!

**Comment by joepavitt** [comment]
@riprock67 sorry it had slipped down in priority as we were planning to transition all charts to Apache ECharts, so would have been done as part of that, not sure when I'm now going to be able to fit that transition in though, so will tackle this now so it's moved forward.

**Comment by riprock67** [comment]
Thanks Joe!  This is great!  Scott
