### ISSUE TITLE
UI Chart - Interpolation Method

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#384]
### Description

For line charts, users should be able to define how data is interpolated between those lines.

<img width="220" alt="Screenshot 2023-11-24 at 09 58 03" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/311c7f97-a010-4ae6-a2f6-b4ecc6d9ca3a">

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by m-schaeffler** [comment]
I'm using line and step with dashboard 1.0
