### ISSUE TITLE
UI Dropdown - Placeholder

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#386]
### Description

Dashboard 1.0 offers the configuration of "placeholder" for a `ui-dropdown`

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
We already have "label", so I do feel like this is a low priority, event hough it's available in D1.0.

**Comment by joepavitt** [comment]
Closing as "label" in the new design covers this

**Comment by rakgupta** [comment]
I don't think "label" (in DB2) and "placeholder" (in DB1) are interchangeable. DB1 also has a "label" that is static and the "placeholder"  is a default selection (that is not necessarily in the list of valid values in the drop down). Please see details and screenshots in this thread [Dropdown Node DB2 Issue](https://discourse.nodered.org/t/dashboard-2-0-drop-down-node-placeholder/98037)

**Comment by joepavitt** [comment]
Hi @rakgupta thanks for the feedback. The key difference we have here is that for D2.0, the `label` is duel-purpose. It means more space the dropdown itself as we don't need to render a label to the side of the dropdown as was required in D1.0

**Comment by rakgupta** [comment]
@

> we don't need to render a label to the side of the dropdown as was required in D1.0

@joepavitt - thanks for the quick response. Let me see if I can work with that. It may need me to handle the labels via code as the "label" moves to the top when a value is selected. Eg: Initial (when nothing is selected", label = "All devices". When item is selected, change label to "Selected devices".... (see screenshots)

**DB2:**
<img width="614" height="111" alt="Image" src="https://github.com/user-attachments/assets/fd06a49f-2bfb-419d-9ec4-d58d6aa090ef" />

**DB1:**
<img width="790" height="107" alt="Image" src="https://github.com/user-attachments/assets/cb5ee638-b1a8-4dae-8f94-98aa55cba173" />

**Comment by joepavitt** [comment]
In your use case, the placeholder "All Devices" is a little strange as that suggests "All Devices" are selected? Generally you want to prompt a user, e.g. "Select Devices", which is appropriate as both a placeholder and label.

**Comment by rakgupta** [comment]
> is a little strange as that suggests "All Devices

Yes - the default is that all events for all devices are visible. When the user selects a device, only the data for that device(s) are shown.
