### ISSUE TITLE
ui-table column type selection

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#392]
### Description

Dash v1 ui-table allows selection of 'Link' for URL strings and 'HTML' for displaying HTML formatted strings.
Dash v2 ui-table does not offer any column types thus none of the URLs or HTML data is displayed correctly.

Request v2 ui-table widget be aligned with similar features as v1 widget.

### Existing Examples

Example of ui-table column selection:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/2d64aa76-0710-410c-b7ae-f2331aff6ec1)

Displayed in v1 dash as follows:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/b587fa54-2932-407e-95cc-2787b3f44ffb)
 
### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Just checking, the `ui-table` you're referring to for Dashboard 1.0 is this one: https://flows.nodered.org/node/node-red-node-ui-table? As it's not actually a core node in Dashboard 1.0?

**Comment by thebaldgeek** [comment]
Correct. Yes.
I was happy to see that ui-table is finally part of the v2 dash family.
Its been annoying to have to get users to install the dash and then the table for all these years.
Thanks for your work on the new v2.

**Comment by joepavitt** [comment]
Yep - just wanted to be sure. We have someway to go to get feature parity with that add-on, so thanks for raising this

**Comment by joepavitt** [comment]
Going to do a first pass of this locally and see how well it functions. I still have considerable reservations about unlocking this box, but I do understand the user value that this provides in supporting low-code uses cases.

The list of types has been added as a tasklist to the Epic
