### ISSUE TITLE
ui-table 'send data on click'

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#397]
### Description

v1 ui-table node has an input and output.
The output can be used to 'send data on click' where clicking any row/column will send that data to the nodes output.

v2 ui-table does not have either output or the option to 'send on click' any of the table data.

### Existing Examples

Sending data on output is a very important function that is used a great deal to drill into / get more details on any table data.
![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/ccc10498-1dd7-4453-8a76-10990d1314f9)

Typical example flow showing the use of this input/output.
![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/d0a5fc22-d65a-4492-b14d-4c46124cce86)

Clicking on the table column both shows the full data and also does a db lookup on that clicked term for display in a second table.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by thebaldgeek** [comment]
To be clear, the v1 sends the exact row and column data. ie, just the data in that one cell.

**Comment by colin-grierson** [comment]
When I use this option in Dashboard v1 I get the full row returned - which makes sense, returning just the cell clicked generally would not be enough to drill down

I need this function too

**Comment by thebaldgeek** [comment]
To be clear, when you click a single cell you get returned: 
msg.topic with the name of the cell the user clicked.
msg.payload with an object that has the key:value of the full row you clicked.

My 'drill down' use case uses both msg.topic and msg.payload.

ui_table v2 should have this exact functionality.

**Comment by maralti** [comment]
Hi, I would need this feature too. 

Table responsiveness is great but being unable to select one row and capture the selection prevents me from migrating to dashboard 2.0 so I will wait for ui_table v2.

Wonderful work anyway, thank you!

**Comment by thebaldgeek** [comment]
Unfortunately tables are not responsive at all - they need to be massive to be viewed (see the issue here https://github.com/FlowFuse/node-red-dashboard/issues/76#issuecomment-1858488178 )  since there is no horizontal scroll bar, so both responsive tables and 'on click' are 100% holding me up from using V2 in my main project.
