### ISSUE TITLE
Text node not displaying correctly across devices

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#400]
Probably similar to https://github.com/FlowFuse/node-red-dashboard/issues/151

Laid out a weather dashboard using v0.8.0 consisting of a row of text nodes.
On a desktop, looks OK, although the label on the 'info' text node is not aligned to the other text node labels, and appears that the 2 lines of text have pushed the label upwards. Shouldn't the label always be aligned at the top of the node's cell space?

![chart](https://github.com/FlowFuse/node-red-dashboard/assets/973580/48d8f10f-1d1a-428f-a776-1a4f8563dde1)

Things get worse when viewing the same dashboard on a mobile device

![chart2](https://github.com/FlowFuse/node-red-dashboard/assets/973580/d96c2cb7-88b4-4ee1-bfbb-b3700ef12d0e)

The size of the 'info' node is 3x1, whilst the others are 2x1.

**Comment by thebaldgeek** [comment]
+1 me too on this.

I can not get the text node to behave predictably like the v1 node.

It takes up a lot of extra space randomly (as do all the v2 objects it seems).
There does not appear to be a global way to control widget spacing / stacking like in the v1 'Site' tab.
The text node seems to float around as a result?

**Comment by thebaldgeek** [comment]
Using Node-RED 3.1.7 and dashboard 1.7.1 this is still a major issue.
With no way to set horizontal or vertical placement of text nodes, page layout in any mode is impossible to arrange.
Here is an example of a few text nodes on a desktop.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/598a1713-bdd0-4bb7-a5bf-8c6efadfe10f)

The spacing seems to be random. I can not - after a few hours of testing - find a way to set any order to the text placement.
When viewed on a mobile device:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/b04c51dd-31b4-4481-a936-34dd22cf4dcc)

I will submit a new issue for the gauge node not being responsive at all.

**Comment by thebaldgeek** [comment]
Trying to keep this thread updated with case-in-point comments from issue: https://github.com/FlowFuse/node-red-dashboard/issues/827

These text nodes were the exact ones I 'tamed' by putting them in a table:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/bea94d93-792b-4fd2-842a-c156f8ad4b2f)

Sure, I have not trimmed the table spacing / sizing neatly in the group yet, but it shows my point... The exact same data presents much more structured and orderly in a table vs spread out on the page as text elements.

Once I figure out how to theme the table, I think its going to look and work great.
