### ISSUE TITLE
Widget: Number Input

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#41]
### Description

<img width="384" alt="Screenshot 2023-06-23 at 21 31 29" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/121eb84e-608f-4218-a83e-823b4c019dc2">

Called a "numeric" in the existing Dashboard 1.0. Would be similar to #38, but provide up/down arrows in the UI to modify the value.

### Properties

Existing Dashboard 1.0 Properties:

<img width="500" alt="Screenshot 2023-06-23 at 21 29 56" src="https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/75783627-3c2e-46ba-b23f-f2a4a9e12642">

### Events

- **on-change**: this widget would need to send a message back to Node-RED when it's value is changed/updated

### Controls

- **enabled**: this widget can be enabled/disabled

### Existing Examples

Would require a custom built piece of HTML/JS

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
#75 includes the text input widget, which itself has a "number" mode. In Dashboard 1.0 however, the `numeric` was considered a different wigdet, and so we should be consistent here.

**Comment by m-schaeffler** [comment]
> #75 includes the text input widget, which itself has a "number" mode. In Dashboard 1.0 however, the `numeric` was considered a different wigdet, and so we should be consistent here.

From my point of view the numeric would no longer be necessary, if the text-input would get the missing features:
- min value
- max value
- step

**Comment by joepavitt** [comment]
Thanks for the input @m-schaeffler - Having seen a _lot_ of industrial Dashboards over the past few months ,I think I'm being persuaded more and more than a `ui-numeric` should be included as a standalone widget. It is very popular in industry, and has distinct layout/options difference from `ui-text-input`
