### ISSUE TITLE
Stuck with adding a new core ui node

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#414]
Hi @joepavitt,

I 'think' that the [documentation](https://dashboard.flowfuse.com/contributing/widgets/core-widgets.html) about contributing core nodes is not complete anymore, due to the recent packaging mechanism changes?

I assume that now both an import and export statement needs to be added to the [index.mjs](https://github.com/FlowFuse/node-red-dashboard/blob/main/ui/src/widgets/index.mjs), instead of the index.js file:
```
export {
    ....
    UIHeatmap,
}

// Exported as an object for look up by widget name
export default {
    ...
    'ui-heatmap': UIHeatmap,
}
```
It would also be nice if a troubleshooting section could be added to the documentation, with some tips to do intermediate checks.  Because I can't  even get a (dummy) heatmap node working, and no idea where to start searching...

I drag a dummy heatmap node on my flow, and I see some heatmap related stuff in my DOM tree arriving:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/3088d66b-21b3-4bf0-80d0-200acd06950b)

But my vue file is quite a fiasco:
```
<template>
    <div ref="heatmap_container" :class="className" />
</template>

<script>
import Heatmap from 'visual-heatmap/dist/visualHeatmap.esm.browser.min.js' // eslint-disable-line import/no-named-as-default, 
...
export default {
    name: 'DBUIHeatmap',
    ....
    methods: {
        onLoad (history) {
            debugger;
            ...
        },
        ...
    }
}
</script>
<style scoped>
</style>
```
I have the impression that my vue file is not loaded by the browser at all:
+ I don't see a div element in my DOM tree with id "heatmap_container".
+ My browser doesn't even try to load the minified js file (as I can see in the network tabsheet of the developer tools).
+ My chrome debugger never halts at the the `debugger` statement.

No idea whether I can do intermediate checks about my vue file (e.g. while building, deploying, client connect, ...)?

Thanks!!
Bart

**Comment by joepavitt** [comment]
Hey @bartbutenaers I can take a proper look at this on Tuesday when back at the desk. Should be able to unblock you fairly quickly.

**Comment by joepavitt** [comment]
@bartbutenaers do you have a fork/branch that you're working on that I can take a look at in the morning?

**Comment by bartbutenaers** [comment]
@joepavitt,
No my changes are not on a public fork yet.  Doing this at the moment only when I have a very short amount of me-time. 
But my problem is solved, because everything seems to be loaded now:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/4dcb394e-f2e4-4a90-84a4-0cc38d309004)

I will close this ticket for now, and create a pull request in the near future to make the documentation a bit more noob proof.
Sorry for the noise !!

**Comment by joepavitt** [comment]
Look forward to the docs PR
