### ISSUE TITLE
ui-template based v-menu missing on iOS devices?

### ISSUE THREAD

**Issue by kevinshane** [FlowFuse/node-red-dashboard#426]
### Description

Hi noob here, I am creating a v-menu with a v-btn, however the whole v-btn is missing on iOS device, on Andriod or pc it's working. When I remove v-menu, the v-btn shows up. Is it a bug? Thanks!

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
That does sound odd. 

Are you using the same browser across each device? Or could this be a Safari problem?

Happy to share a flow so we can take a look too? 

This may end up being a Vuetify bug, rather than something we can address directly.

**Comment by kevinshane** [comment]
Hi thanks for the reply, I've tested with iphone11proMax on iOS 14.2 with safari and chrome, both browsers are having exactly the same bug not showing v-menu at all. However I've switched to a 13proMax with iOS 16, the v-menu shows. Looks like it's an iOS bug for vuetify.

**Comment by joepavitt** [comment]
Thanks for looking into it further @kevinshane - if you can raise an issue on the [Vuetify GH Repo](https://github.com/vuetifyjs/vuetify), and link back to here, will be great to keep it tracked, as no doubt you won't be alone in hitting the problem.
