### ISSUE TITLE
Bug: Impossible to define full `msg` from `ui-template

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#427]
### Description

Due to the underlying handlers for the `this.send()` function, it is expected that this will _just_ send a value, and not a full `msg` object. We had a handler in place to prevent duplicate `payload` nesting, but this just surfaces that one value. Instead, we should treat anything sent via `on-action` or `on-change` as the full `msg` object.

This will require updating of pretty much every component, but will at least then enable the sending of a _full_ `msg` object from `ui-template. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gemini86** [comment]
Okay I'm finally finding this issue after trying to set the topic on an outgoing message with no success. Could we at least in the meantime add this note to the docs?

**Comment by joepavitt** [comment]
from https://discourse.nodered.org/t/dashboard-2-beta-development/83550/54?u=joepavitt

> One other point, if false or 0 are sent they are ignored so somewhere something is ignoring anything that does not compute as truthy.
