### ISSUE TITLE
Add "Themes" panel to Dashboard 2.0 sidebar

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#432]
### Description

Requested [here](https://discourse.nodered.org/t/dashboard-2-beta-development/83550/32?u=joepavitt) would make the `ui-theme` nodes easier to access as currently you can only find them by navigating to each relevant `ui-page` config node, or going to the "Config Nodes" menu in Node-RED, which, for non NR Developers, wouldn't be an intuitive place to go.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by diego780705** [comment]
I believe that "add", "remove" and "edit" is enough. This is for pages and groups.
