### ISSUE TITLE
D2 fails if httpNodeRoot is non-blank

### ISSUE THREAD

**Issue by TotallyInformation** [FlowFuse/node-red-dashboard#437]
As mentioned in the forum: https://discourse.nodered.org/t/dashboard-2-beta-development/83550/52?u=totallyinformation

A regression seems to have crept in because - despite completely removing all D2 nodes - including config nodes - removing D2, restarting, adding D2, restarting then adding a single text node, I cannot access the D2 dashboard page.

This is because, as always, I have the httpNodeRoot set to "nr" so that Node-RED page URLS are always prefixed - found this problem the hard way in the past whihc is why it is always set on my dev PC. D2 is still making assumptions that ignore httpNodeRoot and I get these errors:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/1591850/3ae3e12f-b4e4-4ace-8de1-32054797473c)

As you can see, it is trying to load resources without the /nr prefix which is incorrect and so cannot find them.

Almost certainly, this is the result of coded URL's that don't use the relative prefix of ./ so that they pick up the current URL prefix. The link in the Node-RED Editor has been corrected but the resource links haven't.

**Comment by joepavitt** [comment]
Thanks for capturing this Julian. Do you have an example of how the httpRootNode is set please?

**Comment by TotallyInformation** [comment]
Sorry for late response. `httpNodeRoot` is set in `settings.js`, it is a standard configuration option for Node-RED. I have it always set to `nr` in my dev setup so that I am always testing it. It means that http-in/-out, ws in/out and uibuilder (with the default config) all have all URL paths prefixed with `/nr/`.

**Comment by joepavitt** [comment]
I suspect this is also causing #563 and issues with running Dashboard on Home Automation too
