### ISSUE TITLE
[QUESTION] Any authorization example?

### ISSUE THREAD

**Issue by luixal** [FlowFuse/node-red-dashboard#439]
Hi,

As I've seen [in the docs here](https://dashboard.flowfuse.com/user/settings.html#dashboard-settings), a custom express middleware could be provided to add authorization to the dashboard.

Is there any example/guide available about how to configure this? or can someone point me out about how to accomplish this?

Thanks!

**Comment by joepavitt** [comment]
Hi @luixal - thanks for the question. I don't have any examples to hand, but it's the same approach as the general securing of a Node-RED Editor. The Node-RED forums may be able to assist better in getting Node-RED secured in this particular fashion. You can then use that same logic/settings to apply them here.

**Comment by luixal** [comment]
I was thinking the only way to secure the dashboard was using the middleware, which probably is the best way. I found some relevant info in case someone gets here:

https://nodered.org/docs/user-guide/runtime/securing-node-red#http-node-security

There is some info about how to use middleware for security purpouses.

Also kind of relevant:

https://discourse.nodered.org/t/oauth2-authentication-with-authentik/83238/2
https://discourse.nodered.org/t/oauth2-authentication-with-authentik/83238/2

If you only need to _"secure"_ it, just use the `httpNodeAuth` configuration in `settings.js` like this:

```js
httpNodeAuth: {user:"user",pass:"$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN."},
```

Cheers!
