### ISSUE TITLE
iFrame Widget Request

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#443]
### Description

Embedding other websites in dash v1 is possible but very messy and hit and miss functionality.    
 
I'd like to see a more robust dedicated iFrame widget for dash V2.

A lot of industrial applications use weather data, being able to embed a lightning / wind / storm radar weather map is a VERY frequent request we hear.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Is there a difficulty in using `ui-template` for this?

**Comment by mworion** [comment]
Hi, 
here is an example how I use iFrames with ui-emplate
Michel
```
<template>
    <div class="d-flex flex-column">
        <iframe 
            id="production"
            src="http://192.168.2.213/smartvisu/index.php"
            class="responsive-iframe"
            frameborder="0"
            style="border:0" 
            body-fill
        >
        </iframe>
    </div>
</template>

<script>
    export default {
        data() {
            return {
            }
        },
        watch: {
            msg: function () {
                document.getElementById('production').src = this.msg.payload;
            },
        },
        computed: {
        },
        methods: {
        },
        mounted() {
        },
        unmounted() {
        }
    }
</script>

<style>


    /* Then style the iframe to fit in the container div with full height and width */
    .responsive-iframe {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    width: 100%;
    height: 100%;
    }
</style>
```

**Comment by joepavitt** [comment]
I've just published https://flows.nodered.org/node/@flowfuse/node-red-dashboard-2-ui-iframe which covers this as a third-party widget. Closing the issue

**Comment by thebaldgeek** [comment]
Testing this new node and am finding that nothing shows up at all.
Nothing in the logs, no error in debug tab, nothing in the iFrame.
I have an inject at once a minute and the the full URL. Testing the URL in my browser brings up the website as expected.
Just nothing on the dash2.0 group. Not even a place holder.
Tested with both my URL of choice and https://google.com and neither show up.

**Comment by joepavitt** [comment]
Google will not work as its built with iframe blockers, and forbids use in an iframe.

Are you able to share the other URL? 

I can try and do some better error catching, but I'm not sure what the browser will give me to jump onto.

The way to sanity check this is using the `ui-template` method I'd shared previously, and using `<iframe src=""></iframe>` to be sure its the widget that's broken?

**Comment by thebaldgeek** [comment]
Did not know about google.com iFrame blocker, thanks for the tip.
Using https://opto22.com or https://nodered.org both show the same - nothing at all.

**Comment by joepavitt** [comment]
Opto22 site also has the iframe blocker, Node-RED does not though, so _should_ be working:

This flow will give you a quick tester.

```json
[
    {
        "id": "307c609f43d2b68f",
        "type": "ui-iframe",
        "z": "5141797ff72d0139",
        "name": "",
        "group": "bb21a845cf454195",
        "order": 0,
        "src": "/",
        "width": "10",
        "height": 8,
        "x": 290,
        "y": 220,
        "wires": []
    },
    {
        "id": "7ce392a0c84c4b39",
        "type": "inject",
        "z": "5141797ff72d0139",
        "name": "",
        "props": [
            {
                "p": "src",
                "v": "https://nodered.org/",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 130,
        "y": 220,
        "wires": [
            [
                "307c609f43d2b68f"
            ]
        ]
    },
    {
        "id": "bb21a845cf454195",
        "type": "ui-group",
        "name": "iframe",
        "page": "85043ba28e0273fe",
        "width": "10",
        "height": "8",
        "order": -1,
        "showTitle": true,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "85043ba28e0273fe",
        "type": "ui-page",
        "name": "Third Party Widgets",
        "ui": "c2e1aa56f50f03bd",
        "path": "/third-party",
        "icon": "account-group",
        "layout": "grid",
        "theme": "129e99574def90a3",
        "order": 1,
        "className": "",
        "visible": "true",
        "disabled": "false"
    },
    {
        "id": "c2e1aa56f50f03bd",
        "type": "ui-base",
        "name": "Dashboard",
        "path": "/dashboard",
        "showPathInSidebar": true,
        "navigationStyle": "default"
    },
    {
        "id": "129e99574def90a3",
        "type": "ui-theme",
        "name": "Another Theme",
        "colors": {
            "surface": "#000000",
            "primary": "#ff4000",
            "bgPage": "#f0f0f0",
            "groupBg": "#ffffff",
            "groupOutline": "#d9d9d9"
        },
        "sizes": {
            "pagePadding": "9px",
            "groupGap": "12px",
            "groupBorderRadius": "9px",
            "widgetGap": "6px"
        }
    }
]
```

**Comment by joepavitt** [comment]
Thinking also, it _may_ need a Node-RED restart after installing the third-party widget so that Dashboard can be made aware of the `package.json` changes and the inclusion of the third-party library

**Comment by thebaldgeek** [comment]
Imported, deployed, clicked inject, refreshed browser.
Blank group.
![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/e49f99a5-54a6-4cdb-9f3a-0e828cbaf813)

**Comment by thebaldgeek** [comment]
Restarted Node-RED and iframe is working as expected.
Perhaps this requirement for a restart be added to flows.nodered for this node.

**Comment by joepavitt** [comment]
@Steve-Mcl  is there a way in my package.json (or somewhere else) I can tell Node-RED to notify a user a restart may be required? I know I've seen that popup, but not sure how to configure it?
