### ISSUE TITLE
Page not updating when left in background on Android

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#444]
To see the problem, open a dashboard page in Chrome on Android and open another app or apps, so that the dashboard page goes into the background.  Leave it there for some time.  Using another client machine, change the state of a widget, then on the android device switch back to the page left in the background.  When I do this the widget state on the Android page stays at what it was previously, rather than showing the current data.  Further changes from the other client are reflected.  This is a serious issue.  I suspect the same thing will happen if the page is left in the foreground but the device is left untouched so that the screen is blanked and is left in that state for some time, though I have not confirmed that.

If the same operation is performed with D1, then a few seconds after switching back to the page it can be seen to auto-refresh somehow, so that the data is updated.  I don't know what mechanism is used to achieve that.

[Edit] I have ~~not~~ now confirmed that the same situation can arise if the page is left in the foreground for long enough, particularly on battery power (not charging).  I suspect again that Android is trying to extend battery life by putting the page to sleep.

[Further edit] The situation can be triggered on a device connected to WiFi (whether Android or not) by switching off the WiFi for 20 seconds then restoring it.

**Comment by colinl** [comment]
I think this is likely related to issue #620

**Comment by Soiski71** [comment]
Confirmed. For me it is the HTML page that stopps refreshing the HTML ( temp sensor codes ) from time to time in Android (always on) tablet.
Found out from Node Red server that in same time freeze happens the system log shows .

Pain as can not trust readings on screen with out confirmation of manual refresh of the page.

`10:11:03 SAMONE Node-RED[887]: 3 Mar 10:11:03 - [info] [ui-base:D2] Disconnected bFaAKBFddJvzUORBAAal due to ping timeout`

**Comment by colinl** [comment]
It is certainly much better.  Is there not still an issue that it stops retrying after a certain time?

**Comment by colinl** [comment]
I have removed my recovery hacks so will see what happens

**Comment by joepavitt** [comment]
> There is still something a bit odd going on though which I need to analyse more carefully to work out exactly what I am seeing.

Will leave this open in the mean time

**Comment by arturv2000** [comment]
@joepavitt At least in the PC (Windows with Edge) after a while the page stops being updated if left in background (Dashboard v1.9.1).

Typically, it is usually enough to change "tab", but this last "time" was necessary a page refresh.

**Comment by colinl** [comment]
Are you talking about ui-template nodes or regular UI nodes?

**Comment by arturv2000** [comment]
Typically the ui-templates nodes stop updating.

More rarely is the entire dashboard stops updating and is necessary a full refresh. But don't have quite sure about this one yet, only noticed today (brain is already used to simple doing an F5 when accessing a page after a while in background).

One funny thing, one time I had the developer tools open (showing the websockets messages) and there where no issues, even on next day the dashboard was still updating. Have to try again this to check if it is constant.

**Comment by colinl** [comment]
The ui-template issue is issue #747 or #619 which I think are duplicates.

**Comment by colinl** [comment]
I believe this has been fixed (not including the ui-template issues, which are detailed in #747 and #619) by various updates, and finally with PR #950
