### ISSUE TITLE
ui-template can end up with conflicting group dashboard and page entries

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#445]
In the flows file a ui-template node has entries for group, dashboard (ui-base) and page.  It is possible for these to get out of sync.  For example, see these two template records from the same flows file:
```
{
        "id": "1c35624c74ddbdcf",
        "type": "ui-template",
        "z": "997da33a0beedade",
        "group": "7545fdb22e4a388c",
        "dashboard": "ID-BASE-1",
        "page": "",
....
```
and
```
{
        "id": "de6cfe9d86ed5b93",
        "type": "ui-template",
        "z": "997da33a0beedade",
        "group": "7545fdb22e4a388c",
        "dashboard": "64d151d89e8704cf",
        "page": "0a534af73f5f11fb",
....
```
Note that they have the same group id, but different dashboards.  In the second one the page does belong to that dashboard, but the group does not belong to that page.

This gives rise to a flow file that shows multiple dashboard entries 
![image](https://github.com/FlowFuse/node-red-dashboard/assets/38307/dfd37845-9368-49d4-99b2-b71acdf1ae51)
Both ui-base config nodes show as in use so it is not possible to delete one of them. The only recovery method that I have found is to delete the template node, or hack the flows file to assign the template to the correct ui-base.  The additional ui-base then becomes unused and can be deleted.

To replicate the problem, import a flow containing a template which has different group, page and dashboard ids to the flow being imported into.  Then open the template node and change it to use a group from the original flows and deploy.  This edits the group entry in the template but leaves the original page and dashboard.

**Comment by joepavitt** [comment]
Great spot @colinl thanks for flagging

**Comment by colinl** [comment]
As a matter of interest, why does the template have page and dashboard properties?

**Comment by joepavitt** [comment]
UI Template can be scoped to a single page, or _all_ pages when using the "CSS (All Pages)" or "CSS (Single Page)" options.

**Comment by colinl** [comment]
Ye, of course.  The fix presumably is to make sure only one of those is ever filled in at a time.  Or to save the type and then just one link to the group/page/base.
