### ISSUE TITLE
Question: abstraction of widget placement ?

### ISSUE THREAD

**Issue by svdasein** [FlowFuse/node-red-dashboard#448]
I'm just wondering if there's been any thought in this project to the notion that one could sort of do the equivalent of "sub-flows" for UI components.  One way that might look is that one defines a sub-flow with UI elements, and then when deploying that sub-flow "something" let's one select where the UI elements will live.

This may well be possible right now and I'm just ignorant of it.  If we don't have it already though it'd be a really nice feature.

Sorry if this is a dumb question.

**Comment by joepavitt** [comment]
Yes - very much on the radar - but requires some underlying Node-RED changes: https://github.com/node-red/designs/discussions/77#discussioncomment-7580316

Sticking point is that each subflow needs to be able to define a `ui-group` to render into, and currently, you can't have a subflow define a property that is a config node (as `ui-group`s are)

**Comment by svdasein** [comment]
Awesome thanks @joepavitt
