### ISSUE TITLE
Debug reporting that state not loading correctly from server store

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#455]
Forum post link - https://discourse.nodered.org/t/dashboard-2-beta-development/83550/127

The following debug msg's are reporting state as undefined.
(I have added the node type as a suffix)

`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:87f1e1fa47a4d50a undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:24b58fe1f550fd18 undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:e4c76dbd1c4d844a undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:ee60257a3951b4eb undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:d050b3f87d0e7c2c undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:8c0b4930d485f3e4 undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:9009cf7f724cf7e3 undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:3a5ba08ef8bc953f undefined` - ui-text
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:195bc4d0420ab07a undefined` - ui-chart
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:11675ce3e247ee27 undefined` - ui-button
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:1a391f1b47f9ac5a undefined` - ui-button
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:12c7093609532b00 undefined` - ui-button
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:e2712a1bde4a33e5 undefined` - ui-button
`conn:fIHGK11AwN-UJ0DDAAAB on:widget-load:aa418cf38de5a548 undefined` - ui-button

**Comment by joepavitt** [comment]
And if you refresh your screen, are you then not seeing data that was there before?

**Comment by joepavitt** [comment]
Unfortunately I won't get a chance to fix this now until 30th at least as going away

**Comment by Paul-Reed** [comment]
> And if you refresh your screen, are you then not seeing data that was there before?

Yes, the chart redraws as expected, and the text nodes are retrieving their last state.
So DB working as expected, but reported as 'undefined' in debug.
I guess this is more about a problem with the debug, and not an issue with the dashboard?

> I won't get a chance to fix this now until 30th at least as going away

Not a problem, have a nice break, and we'll speak next year.

**Comment by joepavitt** [comment]
> So DB working as expected, but reported as 'undefined' in debug.

That's a relief - in that case, just an issue with the debug statement

**Comment by joepavitt** [comment]
Can confirm this is no longer a problem - closing the issue
