### ISSUE TITLE
Switch says "Invalid payload value" when using JSON

### ISSUE THREAD

**Issue by philosoma** [FlowFuse/node-red-dashboard#458]
While using JSON for the on/off payload on a switch node, when inputting it gives a debug output of "Invalid payload value". This worked well on D1 switches. The node correctly outputs when toggling on the dashboard, just doesn't like the input. Please see code example which includes both.

Node-RED: 3.1.3
node-red-dashboard: 0.11.1

Merry Christmas!

`[
    {
        "id": "0a3809a1fba82d0f",
        "type": "ui-switch",
        "z": "33871f41.a966a",
        "name": "D2 Switch",
        "label": "D2 Switch",
        "group": "d151d9768c817c7b",
        "order": 0,
        "width": 0,
        "height": 0,
        "passthru": false,
        "topic": "topic",
        "topicType": "msg",
        "style": "",
        "className": "",
        "onvalue": "{\"on\":true}",
        "onvalueType": "json",
        "onicon": "",
        "oncolor": "",
        "offvalue": "{\"on\":false}",
        "offvalueType": "json",
        "officon": "",
        "offcolor": "",
        "x": 430,
        "y": 3160,
        "wires": [
            [
                "4b7dc5df1dad2027"
            ]
        ]
    },
    {
        "id": "6d15a9cee510dc87",
        "type": "inject",
        "z": "33871f41.a966a",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"on\":true}",
        "payloadType": "json",
        "x": 270,
        "y": 3160,
        "wires": [
            [
                "0a3809a1fba82d0f",
                "51ff3b4877253efd"
            ]
        ]
    },
    {
        "id": "4ddf3d3136715a37",
        "type": "inject",
        "z": "33871f41.a966a",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"on\":false}",
        "payloadType": "json",
        "x": 270,
        "y": 3220,
        "wires": [
            [
                "0a3809a1fba82d0f",
                "51ff3b4877253efd"
            ]
        ]
    },
    {
        "id": "51ff3b4877253efd",
        "type": "ui_switch",
        "z": "33871f41.a966a",
        "name": "",
        "label": "D1 Switch",
        "tooltip": "",
        "group": "93b144f7.26dcd8",
        "order": 9,
        "width": 0,
        "height": 0,
        "passthru": false,
        "decouple": "true",
        "topic": "topic",
        "topicType": "msg",
        "style": "",
        "onvalue": "{\"on\":true}",
        "onvalueType": "json",
        "onicon": "",
        "oncolor": "",
        "offvalue": "{\"on\":false}",
        "offvalueType": "json",
        "officon": "",
        "offcolor": "",
        "animate": false,
        "className": "",
        "x": 430,
        "y": 3220,
        "wires": [
            [
                "4b7dc5df1dad2027"
            ]
        ]
    },
    {
        "id": "4b7dc5df1dad2027",
        "type": "debug",
        "z": "33871f41.a966a",
        "name": "debug",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 570,
        "y": 3190,
        "wires": []
    },
    {
        "id": "d151d9768c817c7b",
        "type": "ui-group",
        "name": "Lights",
        "page": "46dfd140ddb08ebf",
        "width": "6",
        "height": "1",
        "order": -1,
        "showTitle": true,
        "className": ""
    },
    {
        "id": "93b144f7.26dcd8",
        "type": "ui_group",
        "name": "Downstairs",
        "tab": "df1ea8f9.cfe798",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": false,
        "className": ""
    },
    {
        "id": "46dfd140ddb08ebf",
        "type": "ui-page",
        "name": "Home",
        "ui": "04ee189a49c54f22",
        "path": "/",
        "icon": "",
        "layout": "grid",
        "theme": "a6833bddd934a96b",
        "order": -1,
        "className": ""
    },
    {
        "id": "df1ea8f9.cfe798",
        "type": "ui_tab",
        "name": "Devices",
        "icon": "important_devices",
        "order": 1,
        "disabled": false,
        "hidden": false
    },
    {
        "id": "04ee189a49c54f22",
        "type": "ui-base",
        "name": "Dashboard",
        "path": "/dashboard"
    },
    {
        "id": "a6833bddd934a96b",
        "type": "ui-theme",
        "name": "Default",
        "colors": {
            "surface": "#ffffff",
            "primary": "#0094ce",
            "bgPage": "#eeeeee",
            "groupBg": "#ffffff",
            "groupOutline": "#cccccc"
        }
    }
]`

**Comment by joepavitt** [comment]
Okay, this is caused because, in JavaScript if we declare:

```js
const a = {on: true}
const b = {on: true}
```

and then do:

```js
a === b
```

The result is `false`.
