### ISSUE TITLE
Values of slider components are empty when changing ui-page

### ISSUE THREAD

**Issue by AxelRHD** [FlowFuse/node-red-dashboard#461]
I have created several ui-pages, which are getting filled by startup triggers.

There fist loaded page is rendered correct completetly. But when I switch the page, all values on the second page are empty. I have to update the page manually to get the values loaded.

Is there something I have to implement in the worflow or a workaround?

I tried to retrigger the states by listening on the $pageview event. But  that hasn't worked neither.

Thanks again for the support and your great project.

**Comment by colinl** [comment]
What widget types are you seeing this on?  Also what version of the dashboard?

**Comment by AxelRHD** [comment]
> What widget types are you seeing this on? Also what version of the dashboard?

Hi @colinl and thank your for the fast reply. I double ckecked it now and the only affected component is the slider. They jump to the minimum value, when I switch the tabs back and forth. Fortunately there is no data send to the actors. It is a visualization problem only.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/16512322/a1184940-aeea-44d3-9c4a-51c8f1db2f01)


The installed version of `@flowfuse/node-red-dashboard` is `0.11.1`.

**Comment by colinl** [comment]
I can replicate that, with just a slider connected to a debug node, then switching pages and back again returns the slider to min position.
Probably a good idea to edit the issue title to specifically mention the slider widget.

**Comment by AxelRHD** [comment]
> I can replicate that, with just a slider connected to a debug node, then switching pages and back again returns the slider to min position. Probably a good idea to edit the issue title to specifically mention the slider widget.

Done.

**Comment by joepavitt** [comment]
I believe this is resolved - it isn't occurring in my latest `1.4.0` version of Dashboard at least - will close, but please do re-open if someone is able to reproduce it with the latest version
