### ISSUE TITLE
ui-control doesn't work

### ISSUE THREAD

**Issue by mickym2** [FlowFuse/node-red-dashboard#462]
If I try to change a page with ui-control providing a pagename  as payload results in the following error:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/58858526/b3e42467-7117-4378-ad62-b42c0485c075)

There is no difference if the payload is just a string with the page name or an object. 

`[
    {
        "id": "6d82583848766447",
        "type": "inject",
        "z": "a97cdbbea18b6b7e",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Wohnzimmer",
        "payloadType": "str",
        "x": 470,
        "y": 360,
        "wires": [
            [
                "579210e720a9d6ca"
            ]
        ]
    },
    {
        "id": "579210e720a9d6ca",
        "type": "ui-control",
        "z": "a97cdbbea18b6b7e",
        "name": "",
        "ui": "56102368e4635988",
        "events": "all",
        "x": 640,
        "y": 360,
        "wires": [
            []
        ]
    },
    {
        "id": "ef62b141718fa06e",
        "type": "inject",
        "z": "a97cdbbea18b6b7e",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"page\":\"Wohnzimmer\"}",
        "payloadType": "json",
        "x": 440,
        "y": 400,
        "wires": [
            [
                "579210e720a9d6ca"
            ]
        ]
    },
    {
        "id": "56102368e4635988",
        "type": "ui-base",
        "name": "dashboard",
        "path": "/dashboard",
        "includeClientData": true,
        "acceptsClientConfig": [
            "ui-notification",
            "ui-control"
        ]
    }
]`

**Comment by colinl** [comment]
I see the same issue.
