### ISSUE TITLE
The order of items in a dashboard does not reflect the configuration

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/node-red-dashboard#479]
### Description

When working on an internal dashboard I noticed that the order of the elements are not the same as I have configured.

Configuration - https://d.pr/i/t3iact

Actual order

Objective 1
Objective 2
Teams by Tier
ui-markdown
Contracted Revenue Utilisation

I believe the order should be the same.

### Which customers would this be availble to

None

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/node-red-dashboard/issues/892
- [ ] https://github.com/FlowFuse/node-red-dashboard/issues/893
```

**Comment by robmarcer** [comment]
I just restarted the NR instance (this is running on FlowFuse 1.15) after which the items were in the correct order. I think that should not be necessary so I'll leave this bug open.

**Comment by colinl** [comment]
What I have noticed is that when a widget is added and deployed then its position in the dashboard right hand pane may not match its position in the dashboard.  If it is manually moved and deployed then the position becomes correct.

**Comment by joepavitt** [comment]
I have just improved this for pages with https://github.com/FlowFuse/node-red-dashboard/pull/848

Still need a little more work for groups and widgets

**Comment by colinl** [comment]
After adding a widget to a group, and deploying, if one exports the widgets in the group one can see that the `order` properties of the widgets are often messed up.

**Comment by joepavitt** [comment]
Thanks @colinl - this is one of my top priorities at the moment

**Comment by colinl** [comment]
Will the fix for this also be relevant for #710 and #722?

**Comment by joepavitt** [comment]
Relevant, but not a fix - that will require a bit more subflow/core work I believe

**Comment by joepavitt** [comment]
#892 and #893 opened to resolve this. I broke it into group and widget fixes to make it easier to review

**Comment by joepavitt** [comment]
This can be closed as both the attached issues are resolved
