### ISSUE TITLE
Multi-line timeline chart - Intermittent strange rendering behavior

### ISSUE THREAD

**Issue by txwireless** [FlowFuse/node-red-dashboard#487]
### Description

There appears to be a strange rendering behavior that occurs with a line chart with a timeline.  The data being passed is timestamped sensor data so it is always chronological, however after some time there will be a secondary line with a straight slope that crosses the entire timeline running the entire length of the x-axis.  It appears it might be related to when the data points and/or hours specified in the x-axis is exceeded.  It doesn't always happen, however over the last week I have seen it probably 50% of the time.  Sometimes it will resolve on its own, other times it has required I clear the dataset. 
[Main.pdf](https://github.com/FlowFuse/node-red-dashboard/files/13930024/Main.pdf)

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by txwireless** [comment]
For clarity, I'm passing the data to the chart in the following format. 
msg.payload = [{ x: <value>, y: <value>, line: <value> }, { x: <value>, y: <value>, line: <value> }]
x = epoch time - same for each line - all values passed at once
y = unique value of temp or humidity all in a float type format with a single decimal
line = name of each series
In the node ui, I'm utilizing:
x = key is x
y = key is y
line = key is line
x-axis - 24 hours - I have tried datapoints as well - timescale
y-axis - min 0, max 120
point - line, radius 0
Initially I didn't have the append/replace option - I'm presuming not specifying was append.  Replace doesn't make sense given the nature of this dataset.
Typically values are updated every 5 minutes with some outside of that window based on actions/changes.

**Comment by colinl** [comment]
Can you show us a screenshot?
Are you sure you are not getting occasional value where x has reduced, which would give a line going backwards across the chart?

**Comment by txwireless** [comment]
I attached a pdf to my original post or do you mean of the config?  Also attaching the code I use to populate the chart and another UI table element.  It’s been a few years since I have been doing JavaScript and I’m sure there is something more efficient but I was going with make it work and then clean up stuff after the fact.  This is my first node-red flow so I’m still in the learning curve process.  

`
// Setup Dates
const currentDate = new Date();
const timeE = currentDate.getTime();
const timeL = currentDate.toLocaleString();

// Get current values from flow context
var current = flow.get('current');

// Append current data to the new msg objects for reference in debugging, etc.
var modMsg = RED.util.cloneMessage(msg);
modMsg.timeEtamp = timeE;
modMsg.localtime = timeL;
var modMsg2 = RED.util.cloneMessage(msg);
modMsg2.timeEtamp = timeE;
modMsg2.localtime = timeL;

// Establish Appropriate Values
if (current.heater) {
    var hValue = 0;
    var hState = "On";
} else {
    var hValue = -1000
    var hState = "On";
};
if (current.ventilation) {
    var vValue = 120;
    var vState = "On";
} else {
    var vValue = 1120;
    var vState = "Off";
};

// Multi-line chart data
modMsg.payload = [
    { x: timeE, y: current.temp_outside_f, line: "Outside Temp" },
    { x: timeE, y: current.temp_inside, line: "Greenhouse Temp" },
    { x: timeE, y: current.humidity, line: "Greenhouse Humidity" },
    { x: timeE, y: hValue, line: "Heating" },
    { x: timeE, y: vValue, line: "Venting" }
];

// Current Snapshot Chart
modMsg2.payload = [
    {
        "Item": "Outside Temp",
        "Value": current.temp_outside_f,
        "Unit": "°F"       
    },
    {
        "Item": "Inside Temp",
        "Value": current.temp_inside,
        "Unit": "°F"
    },
    {
        "Item": "Humidity",
        "Value": current.humidity,
        "Unit": "%"
    },
    {
        "Item": "Heater",
        "Value": hState,
        "Unit": ""
    },
    {
        "Item": "Ventilation",
        "Value": vState,
        "Unit": ""
    }, 
    {
        "Item": "Last Updated",
        "Value": timeL,
        "Unit": ""
    },     
]

// Update Status
var statusMsg = "Last Updated: " + timeL;
node.status({ "fill": "blue", "shape": "ring", "text": statusMsg });

// Send messages to both outputs
return [modMsg,modMsg2];
`

**Comment by colinl** [comment]
> I attached a pdf to my original post

I missed that. For the future you can paste images directly here.
That looks exactly like out of sequence points being added in to the chart. What happened at 2:30?  Does your flow ever redraw the full chart, if so then make sure you have replace selected for that case.

**Comment by txwireless** [comment]
Nothing that I'm aware of.  The chart never auto-redraws unless there is a reboot or I instruct it to via an inject node.  Whenever either occurs, first it sends the empty message to clear the chart, then it reloads the persisted json and filters based on epoch timestamp to only reload the last 24 hours.  That said, if I do tell it to do that, it does eliminate the line issue.

In general there shouldn't be a case where the normal flow does an out of order message since they all come through the same function and it issues the timestamp at that point.  

So regardless of whether there is an underlying issue with the dashboards and/or cart.js, I hear you saying hat the chart always renders strictly as the input was passed and draws the line based on that and not what the x axis specifies.  To address:
- If I'm reloading, I should put the messages into an array (or whatever) and sort by timestamp prior to replaying, however since it seems to work fine when I reload presumably the messages were actually in order.
- For sending messages to the chart in the first place, my function should record the last message epoch and not pass one that is older than that into the chart.

I can certainly add those bits but candidly not sure if that will resolve.  I suppose the other related question is what happens when flows are redeployed and/or reloaded?

Thank you for your rapid responses.

**Comment by colinl** [comment]
> * it seems to work fine when I reload presumably the messages were actually in order.

How are you saving and restoring the data?



> * For sending messages to the chart in the first place, my function should record the last message epoch and not pass one that is older than that into the chart.

If you don't think it should ever happen then just put a check in to check the timestamps are in order, and trigger a notification of some sort in the event it does happen.  Do the same for the full redraw.  It could be there is a bug of course, in which case others will come across it eventually.  Personally I haven't seen anything like this so far.

**Comment by txwireless** [comment]
So I introduced a check based on epoch time and there were some out of order messages.  I tweaked some flows and it seems to have resolved.  I'm still not sure why it happened but the key was understanding that this element needs to be rendered in time order.

Anyways, I appreciate your responses and time.  I'm sorry about the work it introduced.
