### ISSUE TITLE
Sidebar: option to disable URL display

### ISSUE THREAD

**Issue by i8beef** [FlowFuse/node-red-dashboard#488]
### Description

Minor issue, but I'd love a way to turn off the sidebar nav item URLs being visible in the sidebar... I've looked everywhere I can think of and I can't find anywhere to do that.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
I'd actually be open to hiding them as the default - and only showing if no Page Name is provided? Once a page name is there, most of the URL seen is `/dashboard` anyway, which renders it useless information
