### ISSUE TITLE
Feature: add ability to name nodes

### ISSUE THREAD

**Issue by mman** [FlowFuse/node-red-dashboard#505]
### Description

Hi guys, migrating from original node dashboard to dashboard 2. So far loving the experience.

One thing I miss is the ability to give nodes a custom name that is displayed only when designing the dashboard for better orientation.

To keep the dashboard super clean and not consume space, I typically do not add chart title, or legend, or any names anywhere and at the moment my design node red dashboard contains lot of `unnamed charts`... see the attached example below.

<img width="831" alt="Screenshot 2024-01-22 at 12 11 13" src="https://github.com/FlowFuse/node-red-dashboard/assets/249814/d29e1067-45a4-4e5e-b7ea-75e0f7a8c328">

<img width="530" alt="Screenshot 2024-01-22 at 12 12 13" src="https://github.com/FlowFuse/node-red-dashboard/assets/249814/558176d5-2ef6-4de9-a1be-d511f46fbca1">

I am not sure if I understand it correctly but I thought that the ability to "name" nodes on the design canvas is a default built in feature that can not be disabled, but in dashboard 2 I do not see the option...

Am I missing something,

thanks,
Martin

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
As far as I can see it is only the Chart that is missing the Name field (though I have not necessarily checked all types).  I had not noticed that it is missing, but I agree with you that it should be there, if a chart is not labelled then it is very difficult to  adjust positions in the dashboard layout pane as they all show the same name.
