### ISSUE TITLE
Ability tp prepopulate a text input timepicker with a specific date /time

### ISSUE THREAD

**Issue by HiFiJ** [FlowFuse/node-red-dashboard#506]
### Description

Hi everyone,

thanks very much for this great project!

I'm looking for a way to prepopulate (set default data) the timepicker of the text input node.
My specific use case is setting a timerange for a database query. I'd like to set the default interval to yesterday till today, and furthermore update an "end date" timepicker when changing the start time picker (mainly to ensure the picked end time will not be further in history than the start time and help usability on mobile devices in preselecting a sensible default range).

Thanks for any insights,

Joost

Simplistic example flow:

[{"id":"7a37923690d57b1c","type":"tab","label":"Flow 7","disabled":false,"info":"","env":[]},{"id":"af049da3b63ea3ab","type":"inject","z":"7a37923690d57b1c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":180,"wires":[["9799794504a0650e"]]},{"id":"9799794504a0650e","type":"function","z":"7a37923690d57b1c","name":"function","func":"const d1 = new Date(msg.payload);\nmsg.payload = d1;\nnode.warn(d1);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":180,"wires":[["2910ee429f871065","7653a2c0c84e4341"]]},{"id":"2910ee429f871065","type":"ui-text-input","z":"7a37923690d57b1c","group":"8fc2d78887b94afe","name":"","label":"Starttime","order":2,"width":0,"height":0,"topic":"starttime","topicType":"flow","mode":"datetime-local","delay":300,"passthru":true,"sendOnDelay":false,"sendOnBlur":true,"sendOnEnter":true,"className":"","x":520,"y":180,"wires":[["7653a2c0c84e4341"]]},{"id":"7653a2c0c84e4341","type":"debug","z":"7a37923690d57b1c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":530,"y":260,"wires":[]},{"id":"8fc2d78887b94afe","type":"ui-group","name":"Dashboard2","page":"c50a894d7774c655","width":"6","height":"1","order":-1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"c50a894d7774c655","type":"ui-page","name":"Page 2","ui":"067e6014c0f8161c","path":"/page2","icon":"home","layout":"grid","theme":"35644d516a234825","order":-1,"className":"","visible":"true","disabled":"false"},{"id":"067e6014c0f8161c","type":"ui-base","name":"UI Name","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-notification","ui-control"],"showPathInSidebar":false},{"id":"35644d516a234825","type":"ui-theme","name":"Theme Name","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
You just need to feed in a string in the same format that the node sends the time.  So send in "10:35" for example, to set it to that time.

**Comment by HiFiJ** [comment]
Hi, thanks a lot for your reply!
Btw., what made me struggle is that it looks like the date/time string needs to be sent without seconds (hope I am right on this, did not get it to work otherwise).
So for future reference/anyone looking for this my working approach on preparing the date & time string now comes down to this:

`const d1 = new Date(msg.payload);
const dateAndTime = d1.toISOString().split('T')
const time = dateAndTime[1].split(':')
msg.payload = dateAndTime[0] + 'T' + time[0] + ':' + time[1]
`

Again, thanks for your help,

Joost

**Comment by colinl** [comment]
Does that give it to you in the correct time zone?  I would have thought that maybe getHours() and getMins() would be better. You might need some padStart() in there too.
```
const hours = d1.getHours().toString().padStart(2,"0")
const mins = d1.getMinutes().toString().padStart(2, "0")
msg.payload = `${hours}:${mins}`
```

**Comment by HiFiJ** [comment]
Yes, spot on - I overlooked the missing time zone correction. So I would propose this code as an example for populating msg.payload in a function node to dynamically set the datetimepicker (with the addition of the date for the datetimepicker):

```
var tempDate = new Date(msg.payload);

const hours = tempDate.getHours().toString().padStart(2, "0")
const mins = tempDate.getMinutes().toString().padStart(2, "0")

msg.payload = tempDate.toISOString().split('T')[0] + 'T' + `${hours}:${mins}`

return msg;
```

Thanks again very much,

Joost

**Comment by colinl** [comment]
That may give you the wrong date, as the date is also affected by the time zone.
