### ISSUE TITLE
Change Hamburger Icon and/or Add a Top Bar Logo 

### ISSUE THREAD

**Issue by enqoders** [FlowFuse/node-red-dashboard#520]
### **Description:**

As per [previous discussion](https://discourse.nodered.org/t/dashboard-2-0-top-bar-icon/84655), I am trying to add a logo/icon or change the hamburger icon of the top bar logo in Dashboard 2.0, but I am unable to do so. I have tried using the <v-app-bar-nav-icon> component as shown in the [Vuetify example](https://play.vuetifyjs.com/#eNp1Ut1ugjAYfZWmN7tQLE7UhbklOMlCnDo0Es3YRYWKzAINVMQte/e1OAdLtl60/c7323P68gGz1EMGY638QKAOB5xEjGJO7t0YgEGueDj1wVYgJVBCPEnoBqfAS2iS3rmQpWGE05MLgY/TPSAFJ7FPfmWVeZgxReQpMc6V0EviH5/whlFQWQDoYipR+crHHOuiekAQi4PbDc5IT2uGznA2P6rjxyAxxJouljtzGchruVmGPRHHqHFcvFsSGNLhxDFXCKEGyvuNN7uz7kp8tKem7dhW+/pZM6zVjSnynwJjhPCUbbgpQ4zF0pnNx92HtWVdubA+Y8ZPlMjnY98P40ChZMt10GZFPQxVBKB/GZCub1IrlkviPYqzTPSICgUfeCIojnChHEOf7wTaV1WBXOYQGgRhLAoxHSg9Tc5RZ/+iWqnKXy0FInueha+MAap9CfjZhJ2W1urD89lW4esXfV2v4w==) (lines 5-8), but it does not seem to work, The logo does not appear.

### **The following code has been tried:**
`<template>
<v-card flat>
<v-toolbar color="primary" dark extended flat>
<v-app-bar-nav-icon>
<img
:src="'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII'"
style="padding-left: 1px"
/>
</v-app-bar-nav-icon>
</v-toolbar>
<v-card class="mx-auto" max-width="700" style="margin-top: -64px">
<v-toolbar flat> </v-toolbar>
</v-card>
</v-card>
</template>`

### **Request:**
Adding this missing functionality to [`ui-theme`](https://dashboard.flowfuse.com/nodes/config/ui-theme.html) (or any other), so it would be possible to change the hamburger icon and/or add an image logo to the top bar logo in Dashboard 2.0. Highly appreciated!

![image](https://github.com/FlowFuse/node-red-dashboard/assets/149094652/2e371a0b-4418-4577-bbd1-9d957f32c11d)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by SynoUser-NL** [comment]
This would indeed be a nice feature to have. Preferably in the Theme settings.

**Comment by enqoders** [comment]
Fixed by using [Teleports](https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#teleports)

`[{"id":"5d2b7a7e1d4d4943","type":"inject","z":"f6f2187d.f17ca8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"https://awsmp-logos.s3.amazonaws.com/seller-atdjfmz7ehmiw/129a1f6666260032f382e46c1bce73f1.png","payloadType":"str","x":230,"y":320,"wires":[["af60996211d3b81b","17309fd51bfc9b24"]]},{"id":"af60996211d3b81b","type":"image","z":"f6f2187d.f17ca8","name":"","width":160,"data":"payload","dataType":"msg","thumbnail":false,"active":true,"pass":false,"outputs":0,"x":500,"y":380,"wires":[]},{"id":"303ba045929ce999","type":"ui-button-group","z":"f6f2187d.f17ca8","name":"test logo","group":"a3431b6ac253f9fd","order":0,"width":6,"height":1,"label":"button group","rounded":true,"useThemeColors":true,"passthru":false,"options":[{"label":"1","icon":"","value":"option_0","valueType":"str","color":"#009933"},{"label":"2","icon":"","value":"option_1","valueType":"str","color":"#999999"}],"topic":"topic","topicType":"msg","x":220,"y":360,"wires":[[]]},{"id":"17309fd51bfc9b24","type":"ui-template","z":"f6f2187d.f17ca8","group":"a3431b6ac253f9fd","page":"","ui":"","name":"","order":0,"width":0,"height":0,"head":"","format":"<template>\n    <Teleport v-if=\"mounted\" to=\"#app-bar-actions\">\n        <v-img :width=\"110\" aspect-ratio=\"4/3\" cover\n            :src=\"msg.payload\">\n        </v-img>\n    </Teleport>\n</template>\n<script>\n    export default {\n        data() {\n            return {\n                mounted: false\n            }\n        },\n        mounted() {\n            this.mounted = true\n        }\n    }\n</script>","storeOutMessages":true,"passthru":true,"resendOnRefresh":true,"templateScope":"local","className":"","x":480,"y":340,"wires":[[]]},{"id":"a3431b6ac253f9fd","type":"ui-group","name":"Group Name","page":"b35892f9400e03a6","width":"6","height":"1","order":-1,"showTitle":true,"className":"","visible":"true","disabled":"false"},{"id":"b35892f9400e03a6","type":"ui-page","name":"Page Name","ui":"0095684061591fec","path":"/page1","icon":"home","layout":"grid","theme":"517d454df1d3fc5a","order":-1,"className":"","visible":"true","disabled":"false"},{"id":"0095684061591fec","type":"ui-base","name":"Enqode","path":"/dashboard","showPathInSidebar":false,"navigationStyle":"icon"},{"id":"517d454df1d3fc5a","type":"ui-theme","name":"Theme Name","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"12px","groupGap":"12px","groupBorderRadius":"4px","widgetGap":"12px"}}]`
