### ISSUE TITLE
UI Template: this.send is sending multiple messages

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#524]
### Description

See: https://community.flowfuse.com/t/template-node-multiple-debug-messages-after-each-restart/536

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by omrid01** [comment]
Problem seems still not fully solved. See update in [https://community.flowfuse.com/t/template-node-multiple-debug-messages-after-each-restart/536/6.](url)

Thanks
