### ISSUE TITLE
Allow Dashboard to be run from reverse proxy with path change

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/node-red-dashboard#526]
### Description

Currently the dashboard uses hard coded full paths (stating with `/dashboard`) for assets and the socket.io connection.

Making them all relative paths will allow the dashboard to be proxied onto to a different path.

Making the paths relative in the `dist/index.html` moves things forward but the socket.io connection is still trying to open a full path.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Not sure this is a "small" sizing? If I recall, there were a lot of headaches when trying to do this before, but I'll see what we can do. Have any quick config I can run locally to give me a test environment for this?

I suspect there is overlap in a solution with https://github.com/FlowFuse/node-red-dashboard/issues/437

**Comment by hardillb** [comment]
yep, I'll update when done with call

**Comment by hardillb** [comment]
create the following file called `nginx.conf`

```
worker_processes 1;

events {
  worker_connections 1024;
}

error_log /dev/stderr;

http {

  server {
    listen 80;
    access_log /dev/stdout;

    root /var/www/html;

    location /test/ {
	    rewrite /test/(.*) /dashboard/$1 break;
	    proxy_pass http://172.17.0.1:1880/dashboard/;
    }
  }	
}
```

Then run:

```
docker run --rm -v `pwd`/nginx.conf:/etc/nginx/nginx.conf -p 8080:80 nginx
```

You may need to change `172.17.0.1` to host.docker.internal` on a mac.

This expects Node-RED to be running on port 1880 with a dashboard deployed and you access it via `http://localhost:8080/test/`

**Comment by L3v3L** [comment]
This probably affects Home Assitant users, as all node red endpoints are automatically proxied to /endpoint/ path

**Comment by robmarcer** [comment]
@hardillb can you let me know which customer this is? Either post a Hubspot link or tell me their details and I'll add it.

**Comment by robmarcer** [comment]
This customer requested this feature - https://app-eu1.hubspot.com/contacts/26586079/record/0-1/2454

**Comment by joepavitt** [comment]
- Complexity currently exists that `socketio` is using an absolute path, to use a relative path then means that SocketIO defaults to the base URL being `window.location.host` ([docs](https://socket.io/docs/v3/client-api/#iourl))
- We serve our app at a `./` base which means all assets are served at the same URL as `index.html`, which is normally `/dashboard` or `/<httpNodeRoot>/dashboard`. 
- We serve SocketIO at `/<httpNodeRoot>/dashboard/socket.io`

**Comment by joepavitt** [comment]
If I hardcode `setup.socketio.path` to be `/test/socket.io`, this does enable socketio comms, however, the next problem still exists in that Vue Router defines it's paths given the full `page.path` definition which still reverts to `/dashboard/<page>`

**Comment by joepavitt** [comment]
Just recording for test purposes the config file we've managed to get working locally:

```conf
worker_processes 1;

events {
  worker_connections 1024;
}

error_log /dev/stderr;

http {

  server {
    listen 80;
    access_log /dev/stdout;

    root /var/www/html;

    location /test/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

	    proxy_pass http://host.docker.internal:1880/dashboard/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
    }

    location /foo/bar/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

	    proxy_pass http://host.docker.internal:1880/dashboard/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
    }
  }	
}
```

**Comment by joepavitt** [comment]
Solution:
1. Utilise the fact that we can do relative HTTP requests, which automtically take into account the proxy. This is useful when we do out initial HTTP request to `./_setup`
2. We store reference to the `basePath` from that HTTP request
3. When establishing SocketIO client connection, utilise `basePath`, and replace anything before `/socket.io/` in the SocketIO `path`
4. Store `basePath` as part of our config in the VueX store
5. Utilise `basePath`, instead of `ui.path` when setting up the Vue router

**Comment by ortegafernando** [comment]
> Just recording for test purposes the config file we've managed to get working locally:

Hi, @joepavitt have you also tried third party nodes?

Thanks

**Comment by joepavitt** [comment]
I can't say I recall whether I tested this explicitly, but I have seen a few people recently complain about third party nodes not working, but I'd not been able to reproduce

**Comment by ortegafernando** [comment]
> I can't say I recall whether I tested this explicitly, but I have seen a few people recently complain about third party nodes not working, but I'd not been able to reproduce

Do you think it will be easy to solve? Do you know if the cahnge will be necessary in all third party nodes or in base dashboard 2.0 developement? 

In my humble opinion, I think nowadays working with docker and nignx is a must. What do you think? Does it have a easy solution?

**Comment by ortegafernando** [comment]
> I can't say I recall whether I tested this explicitly, but I have seen a few people recently complain about third party nodes not working, but I'd not been able to reproduce

May be here you need the information to reproduce it:
https://github.com/FlowFuse/node-red-dashboard/issues/1612#issuecomment-2640467065
