### ISSUE TITLE
Icons in switch widgets

### ISSUE THREAD

**Issue by fmarzocca** [FlowFuse/node-red-dashboard#531]
I use several ui-switch widgets with icons, but on Dashboard2 icons are not showing...

i.e. - not working:
lightbulb_outline (material icon)
fa-fire (font awesome)
fa-lightbulb-o (font awesome)

**Comment by hotNipi** [comment]
Document states that you can only use Material Design Icons. 
https://dashboard.flowfuse.com/nodes/widgets/ui-switch.html#properties

If to start supporting FontAwesome and then maybe many more possible icon providers, it just makes dashboard heavy to load and that surely should be avoided. The set of MD icons is much wider than it was available for DB1.

**Comment by fmarzocca** [comment]
Ah, so you need to update the inline documentation of the node:
<img width="309" alt="Screenshot 2024-01-31 alle 11 06 00" src="https://github.com/FlowFuse/node-red-dashboard/assets/8530030/fb51eb48-1b08-499f-a082-aa2a38595d2d">

**Comment by riprock67** [comment]
How does one change the size of the icon inline?  I know how to do it with font awesome, but it isn't clear in MDI.  Thanks!

**Comment by joepavitt** [comment]
> Ah, so you need to update the inline documentation of the node:

Apologies for that, thanks for flagging. Will get sorted.
