### ISSUE TITLE
ui-level

### ISSUE THREAD

**Issue by va2px** [FlowFuse/node-red-dashboard#536]
### Description

Is there any plan to add a ui-level flow into the Dashboard V2?

Thanks,

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hotNipi** [comment]
Whatever the considerations, do not to try to replicate. 
Steal ideas from grafana and maybe from here [(https://discourse.nodered.org/t/dashboard-2-0-is-now-generally-available/84913/43?u=hotnipi)](url)

I don't have plans to migrate ui-level to DB2 but happy to consult in terms of user feedback, features, improvements, technical proposals ...

**Comment by va2px** [comment]
Thanks a lot.  That's exactly what I was looking for.
