### ISSUE TITLE
Dashboard 'front page' does not appear on navigation list

### ISSUE THREAD

**Issue by colin-grierson** [FlowFuse/node-red-dashboard#537]
My dashboard has a front page ('IBMi Status Dashboard'), a page for displaying disk usage details and a test page. Previously when I displayed the navigation panel all three appeared. Now the front page does not appear on the list
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/f2ca5fa4-8ae8-4456-981f-b340bba3c02c)
- this is the front page display, but it does not appear on the navigation panel

Here is the list of pages
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/0d1962dc-1655-4570-92d8-d82752eab980)

I don't know if this problem first happened after I installed Dashboard V2 0.11.6 or after I configured ui-control widgets to automatically go to the ASP Usage Analysis page. Prior to going to 0.11.6 all three appeared.
- Deleting the ui-control widgets does not restore IBMi Status Dashboard to the navigation list

**Comment by colinl** [comment]
Check in the page config that it is set to Visible and Active. I managed to lose those on one page, possibly during an upgrade, I am not sure.  I see those are not mentioned in the help text for the node so I guess they were added later.

**Comment by colin-grierson** [comment]
Thanks ColinL, you are on the money. Visibility and Interactivity had no value set for my front page. Setting these to Visible and Active fixed the problem.  
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/3f5b7d79-fe08-4c1f-b34f-4463d756e8f4)

My other two pages are set Visible and Active.

The question becomes how does a page lose its Visibility and Interactivity settings during an update

**Comment by colinl** [comment]
Earlier versions of the page config node did not have those fields.  I imagine the code has been designed to cope with them not being there and apply the defaults.  Normally this seems to work ok, but sometimes it doesn't as we saw.  I think it may be something to with them being missing and at the same time the path is `/`.  I can't replicate the issue though.

**Comment by joepavitt** [comment]
This is likely my fault for not handling the backward compatibility too cleanly. I tried to cover all of the options and possibilities, I clearly missed some! Apologies!

Will close now as issue seems to have been resolved?
