### ISSUE TITLE
How I use socket comunication with template

### ISSUE THREAD

**Issue by diecamdia** [FlowFuse/node-red-dashboard#540]
Hi all, 

     I don´t know if this a issue o that I dónt konw to use it but, I have a template whith the following code:

   ````
data() {
            return {
                count: 0
            }
        }, ...
        mounted() {
            this.$socket.on('msg-input:' + this.id, function(msg) {
                console.log(this.count, msg.payload.counter)
                this.count = msg.payload.counter
            })
        }
````

    I see that the this.count is undefined. how I must use correctly? I 'm trying to reset a value with an inject. 

   Thanks

**Comment by joepavitt** [comment]
Hi @diecamdia - this is actually a bit of a JavaScript annoyance linked to function scope. The `this` inside a `function () { ... }` will refer to the `function` itself, not the Vue component.

Instead you have two options:

### 1. Anonymous Function:

```js
this.$socket.on('msg-input:' + this.id, (msg) => {
    console.log(this.count, msg.payload.counter)
    this.count = msg.payload.counter
})
```

Note the change in how we declare the function, this prevents the function from creating it's own scope.

### 2. Create a `vue` variable

Another common practice seen, if you do want to use a scoped function, is to assign `this` to a variable outside of the function first, e.g:

```js
const vue = this // maintain a reference the component's "this"
vue.$socket.on('msg-input:' + vue.id, function(msg) {
    // now, "this" in here only refers to the function, but "vue" maintains the connection to the surrounding component 
    console.log(this.count, msg.payload.counter)
    vue.count = msg.payload.counter
})
```

**Comment by diecamdia** [comment]
Hi @joepavitt,

    Thanks for the aclaration, is working fine.
