### ISSUE TITLE
Markdown Node only updated on Full Deploy

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/node-red-dashboard#552]
### Description

If a markdown node is deployed, then edited, but not a Full deploy, the node isn't reloaded.  Node isn't flagged for an edit.

Switching to Full Deploy works, but not for Modified Nodes or Modified Flows.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by SynoUser-NL** [comment]
We experienced something similar, however not just with the markdown node (button node, notification node had same problem). Starting a fresh NodeRED instance and porting\rebuilding the flow solved this for us.
