### ISSUE TITLE
UI-Theme does not refresh 

### ISSUE THREAD

**Issue by diecamdia** [FlowFuse/node-red-dashboard#553]
Hi, 
   I've created a new Theme and changed the colors:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/5762398/b25a78db-dfcc-4152-a4d9-b43852eb04a8)

but the page does not update the background color, even I implemented it several times and refreshed the page

![image](https://github.com/FlowFuse/node-red-dashboard/assets/5762398/8c44f79f-961f-4f0b-b330-89062c4c931e)

There is this in the explorer console:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/5762398/a853ea7c-1eaa-4dc3-af6f-022567398b20)

I only hava one Theme:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/5762398/c9387237-b765-4f17-a53f-eead9b244e7a)

and receive 2.

I've noted that refresh on full-deploy.

thanks,

**Comment by colinl** [comment]
Does it take if you restart node-red?

**Comment by diecamdia** [comment]
If I do a full deploy and restart node-red, it takes it

**Comment by joepavitt** [comment]
Thanks @diecamdia - the gap we have here is the requirement for a full re-deploy, as it's not _just_ `ui-theme` that needs to update, but also `ui-base`, but the Editor doesn't detect this.

**Comment by joepavitt** [comment]
Closing as duplicate of #332
