### ISSUE TITLE
Per user action audit log

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#56]
### Description

Once a user logs in, any actions taken by that user are logged.

Example. A month ago I had a user type very horrible words into any/all text entry (search requests) on my public aircraft tracking website. The words were so vulgar I had several other users complain to me about the offence they were caused. Since my aircraft website was public, and there is no way to know which user was typing in those phrases, there was nothing I could do but cripple the functionally of the entire site for all users and remove all text entry gadgets for a time and hope they got board and move on.

If each logged in user had an audit trail, I could have emailed the exact person, present the evidence, tell them they have 24 hours to stop doing that and if they don't, revoke their account.

**Comment by MarianRaphael** [comment]
See also: https://github.com/flowforge/flowforge-nr-dashboard/issues/1

**Comment by joepavitt** [comment]
Hey @thebaldgeek - just checking my understanding here, the words were input into the front-end text widgets, not into the Node-RED Editor?

Do you have some level of authentication, given that you're saying you would know the e-mail address of the user?

**Comment by thebaldgeek** [comment]
Correct. The words were typed in the dashboard text widget.
No one beyond me has access to the editor (as would be the case in most industrial automation use cases I suspect).
Node-RED has zero level of authentication, that is the core issue. You can only protect the editor or the entire site with one user/pass.
FlowFuse needs to enact a per user dashboard authentication along with some per user audit logging. Once that is in place, any text entered into any dashboard text widget would be logged so we would know who changed the setpoint, or entered any string. This is a standard function of pretty much ever SCADA system I have worked with.

**Comment by joepavitt** [comment]
> FlowFuse needs to enact a per user dashboard authentication along with some per user audit logging

We do already have [Dashboard Viewer Role](https://flowfuse.com/docs/user/team/#role-based-access-control) available which does exactly the first half of this. With regards to audit logging though, _currently_, in FlowFuse, only activity in the Node-RED Editor is logged, not in the Dashboard itself.

**Comment by joepavitt** [comment]
Really appreciate that feedback @thebaldgeek - I'll get some issues raised over in FlowFuse to cover that and will see what we can do.

**Comment by joepavitt** [comment]
Just going back through old issues. Now that we have https://dashboard.flowfuse.com/user/multi-tenancy.html#understanding-client-data and the ability, with the auth plugins, to detail `user` data, I think that we wouldn't extend this request beyond that point within Dashboard itself.

All events emitted would contain the `msg._client.user` object with an auth plugin, and then the user themselves can store these in a DB, or wherever appropriate to create the audit log.

Within FlowFuse, we have the attached (above) issues to track more verbose auditing within FlowFuse itself, and the ability to sign up to a team via a link as discussed above too.
