### ISSUE TITLE
Allow GAUGE segmental sub-labels to display mdi-icons

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#567]
### Description

Replacing the sub-label text with an icon, could identify the chart's usage, and therefore users could then leave the widget title blank, to maximize real-estate.
https://discourse.nodered.org/t/ui-gauge-is-available/85318/15

![gaugeoil](https://github.com/FlowFuse/node-red-dashboard/assets/973580/8bf1c4ad-b39c-49f7-a093-1aa86eee27e8)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
As a quick win here, client-side, check if `props.unit` has `mdi-` at start, if so, show an icon in place of the text. May need to improve the styling/sizing of the icon too vs. text-version

**Comment by colinl** [comment]
Is that not liable to be limiting at some point if you allow icons other than mdi?

**Comment by joepavitt** [comment]
> Is that not liable to be limiting at some point if you allow icons other than mdi?

Sure, but easy enough to support for now and override in the future.

**Comment by colinl** [comment]
Though you will be committed to supporting this for a long time, in order to avoid breaking changes as far as possible.

**Comment by Paul-Reed** [comment]
I see an additional config input box has been added to change the sub-labels - now 'units' & 'icons'.
I thought the original plan was;

> check if props.unit has mdi- at start, if so, show an icon in place of the text.

so that there was only one input box, for either text or a MD icon, which sounded a cleaner approach, and makes things easier for new users
Especially, if the icon/text size is increased, there would not be enough room for both an icon & text.
