### ISSUE TITLE
Layout for widgets in group seems wrong. Missing CSS declaration grid-row-end: span [rows]

### ISSUE THREAD

**Issue by hotNipi** [FlowFuse/node-red-dashboard#570]
### Description

Preconditions: Group size is 6x1
Expected layout :

![image](https://github.com/FlowFuse/node-red-dashboard/assets/35291460/c4bbef4a-42da-4b90-9e7f-0844f2300e59)

Where 2x2 button is second in order.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/35291460/9c51edf3-9a25-4087-8a46-e3d9f4e3a14f)

The actual outcome is:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/35291460/004bba38-12f3-4ff9-8491-de91124455dd)

The grid-row-end declaration is applied to the component but not for the containing div. 
This is same for all layouts, I took the reference image from layouts/Grid.vue

![image](https://github.com/FlowFuse/node-red-dashboard/assets/35291460/f84cee5c-4fde-4487-8e6b-2239c0ebecf3)

Both elements - the component and the container should have `grid-row-end: span [rows]` declarations. Otherwise I can't imagine it will somehow possible to arrange widgets in group.

Best, 
Endel

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by hotNipi** [comment]
Hi @joepavitt

I do shake this issue thread a bit just to get a little attention.
That is because I'm pretty sure it is a bug which in my world should get priority **emergency**. See that there is bunch of people trying to migrate from DB1 already and this is something which stands as obstacle. 
I have provided workaround for couple of my followers but I'd like to not share it widely cos I'm not sure about the future of this. 

So if I'm right and it is a bug - it's a 10 minute fix as described, if not - I'd like to hear how it should be possible to manage the widgets layout in group properly.

Thanks,
Endel

**Comment by joepavitt** [comment]
Thanks Endel, will sort today. I'm only on Dashboard two days a week (today and tomorrow) so hadn't had a chance to look at this yet

**Comment by joepavitt** [comment]
Fix incoming - thanks for the assist @hotNipi 

<img width="620" alt="Screenshot 2024-02-15 at 08 42 03" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/2bfd99fb-8797-46fe-85c4-7a7cd4d82def">

**Comment by hotNipi** [comment]
Thank you :)
This maybe now can help also sort out the ordering issue mentioned here https://discourse.nodered.org/t/node-ordering-in-groups/85448 
I have some doubths those may be slightly related ..
