### ISSUE TITLE
Sidebar: Add Pages & Groups

### ISSUE THREAD

**Issue by novski** [FlowFuse/node-red-dashboard#585]
The creation of UI tabs / groups or whatever you name the structure is completely unclear to me.
I cannot find appropriate doc's and if I trial and error I constantly delete unintended stuff. 
Add + signs above the UI pages (former Tab's) or document how I can add a widget (former Group) to a page.

**Comment by joepavitt** [comment]
Hi. Groups are still the same as they were in Dashbosrd 1.0.

We do have a short guide here: https://dashboard.flowfuse.com/getting-started.html#building-a-dashboard

Which shows that tou can drop any node in. Node-RED will then prompt you to create your first group, etc. In the editor panel of your new node.

I do agree the _"Add new ui-group"_ (and other config nodes) workflow is very annoying though, but unfortunately we are constrained by how Node-RED deals with this UX.

We do also have https://github.com/FlowFuse/node-red-dashboard/issues/66 to address this pain point too

**Comment by novski** [comment]
I am referring to another way of setup. The right Sidebar. With the initial Dashboard, I can add a Group, what makes it much more clear. With Dashboard 2.0 the "+ group"  Button is missing. That makes it confusing. 
<img width="524" alt="Bildschirmfoto 2024-02-17 um 20 49 56" src="https://github.com/FlowFuse/node-red-dashboard/assets/6088056/27796e48-e28c-40c4-bcbd-9496de19f334">

**Comment by joepavitt** [comment]
Will also need to address https://github.com/FlowFuse/node-red-dashboard/issues/684 as part of this, otherwise any new pages added do not then appear in the sidebar
