### ISSUE TITLE
Gauge color changes do not always align with the outer segments

### ISSUE THREAD

**Issue by colin-grierson** [FlowFuse/node-red-dashboard#591]
I am guessing the gauge data should be supplied as a numeric value in msg.payload as this makes sense and is how Dashboard 1 works. However it is just a guess as I cannot see anything in the built in documentation nor the FlowFuse documentation that says how values are to be provided, and none of the examples given are of working code.

Solved by restarting Node-Red. See comment below for color alignment problem

Trying out the gauge widget I am just getting an empty space in my display group
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/d32a4db1-df1d-4939-8d56-c1b1a2b6ca54)

Examining the html I can see a space is reserved for the gauge but there is nothing inside it (I don't have white on white)

> ...div data-v-fc34581d="" id="nrdb-ui-widget-d3e6d10a86042d15" class="nrdb-ui-widget nrdb-ui-gauge" style="display: grid; grid-template-rows: repeat(5, minmax(45px, auto)); grid-column-end: span 6;"></div...

Here is my gauge definition
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/c23d9014-a4fb-4adc-88b9-8d321fe74e57)

Here is the flow
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/f5a3e7c9-5c2a-4063-849b-08e11fb2572b)

Here is debug showing the input to the gauge (and LED)
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/78bf550d-173c-46a4-8112-aebc6e5bb955)

Thanks again for your help and it's great to see the additional widgets and features arriving.

**Comment by colinl** [comment]
Have you tried restarting node-red?

**Comment by colin-grierson** [comment]
And then I restarted node-red and the gauge appeared! However there appears to be a discrepancy in the coloring of the inner and outer rings
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/175fc27f-556e-4598-a5e5-cc25d92169e5)
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/a2283752-7b9a-4e4b-8d63-d272255e1b43)
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/c7b90482-dcbd-47af-98f2-ed7be8fa1b2c)

This happens because my data range (10-100) and segments range (0-100) were not the same 
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/7d1cb388-0059-4292-aaef-607b424aa3da)
The color changes align when the ranges are the same, e.g. both the green segment and the range starting at 10

It goes wrong the other way too. Starting the data range at zero and the first segment at 20 I get this:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/d1b4da00-144f-4f8d-9026-ceec694260fb)
![image](https://github.com/FlowFuse/node-red-dashboard/assets/41355165/c0f4b7f9-548c-404c-9490-92c423fcdceb)

I think the segment colors need to be positioned within the data data range so the color changes always align. Either that or the editor should insist the ranges are the same.

Cheers, Colin

**Comment by colin-grierson** [comment]
Thanks ColinL, I'll add a restart to my trouble shooting in future.

**Comment by joepavitt** [comment]
Restart isn't necessary, this occurs when the `min` of the Gauge doesn't match the first segment provided in the list of colours.

I have it on my list to make this check more robust

**Comment by joepavitt** [comment]
Summarising todos in here:

- Update the documentation to specify `msg.payload` is how to set the value
- Better validation in the NR Editor to make sure that the `min` value aligns with the smallest provided `segment`.
- Can also offer validation if a segment is provided that is _larger_ than the `max`.
