### ISSUE TITLE
ui-control - Show/Hide groups not working

### ISSUE THREAD

**Issue by m0gg3** [FlowFuse/node-red-dashboard#593]
Hi,

Can't get the ui-control to Show/Hide groups.
I have a ui-button with this payload to be sent:
`{
    "groups": {
        "show": [
            "Belysning"
        ],
        "hide": [
            "Camp",
            "Sensorer",
            "Batteristatus",
            "Relästatus"
        ]
    }
}`

And this is my groups:
<img width="245" alt="image" src="https://github.com/FlowFuse/node-red-dashboard/assets/36886316/e02f903e-4314-4e77-bba5-ade9d0d50d8b">

Nothing happends. Tried different names, different ways to set the payload (change node, function node, injection node etc).

At first I got no logs in the browser console, but now after a few restarts of node-red I get this when clicking the button:
<img width="811" alt="image" src="https://github.com/FlowFuse/node-red-dashboard/assets/36886316/b91e6d53-6d6c-4881-add5-7a1ee6c1f91c">

Using Safari on MacOS and iOS. Also tried Chrome on MacOS.
Node-Red 3.1.3
Dashboard2 1.1.0

**Comment by m0gg3** [comment]
Ok, so I googled quite a lot last night without finding anything. 
Today, during my lunch break I actually found what I think was a French youtube video, showing Dashboard 2.0, and he had the same issue but found out you need to specify the Group names like this:

'Page_Name:Group_Name'

So in my case that would be for one of them:
'Meny:Sensorer"

(I actually tried 'Meny_Sensorer' before, so close :D)

Now it works perfectly. So I guess a quick update to the documentation is an easy fix :)

Thanks!

**Comment by joepavitt** [comment]
Thanks @m0gg3 - I did think that was going to be the problem, but even my local testing examples don't reflect that update, which is odd., but my E2E tests do agree with this: https://github.com/FlowFuse/node-red-dashboard/blob/1cc842135cb73ea6ddc448a9f283dcd21a2a4fb4/cypress/fixtures/flows/dashboard-controls.json#L311

Documentation will get updated.
