### ISSUE TITLE
UI Notification: Confirmation Buttons

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#606]
### Description

![image](https://github.com/FlowFuse/node-red-dashboard/assets/99246719/df608cfd-fb19-4873-88d7-f50e54a6c03a)

In Dashboard 1.0, it's possible to define the "Layout" as a confirmation dialog instead. Currently, we only support a timed notification.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
Is this the same issue as https://github.com/FlowFuse/node-red-dashboard/issues/193 "Captures the "Dialog" functionality from ui-toast in Dashboard 1.0, that has not been ported to the ui-notification widget in D2.0"

**Comment by joepavitt** [comment]
Ah, better project management than I can handle there @colinl - thanks for spotting! Will close this is a duplicate
