### ISSUE TITLE
ghost ui-text in group after node deletion 

### ISSUE THREAD

**Issue by Soiski71** [FlowFuse/node-red-dashboard#612]
I'm seeing this in couple cases when using ui-text (to play around and learning) that even after the deletion of the ui-text node the text is rendered in the group. I have restarted node-red and refreshed and deleted the browser cache of the pages, but it does not help?

Node Red version 3.1.5 and @flowfuse dashboard2 ver.1.2.0

Sample screen (ghosts in the red arrows)
![image](https://github.com/FlowFuse/node-red-dashboard/assets/59532263/93abd438-a689-4dd3-bf40-e07b7f75ca63)

View page source shows them here.

 
![image](https://github.com/FlowFuse/node-red-dashboard/assets/59532263/10f8dde4-92a2-42e8-a968-85f6c3f0f3e3)

**Comment by tmichaeltx** [comment]
While I can't provide the same details as I deleted the page and then rebuilt without it, I will note that I had the same experience with the table component (plus the text label component that initiated the bug)

**Comment by joepavitt** [comment]
Just tried:

1. Add `ui-text`
2. Full Deploy
3. View Dashboard - widget is present
4. Delete `ui-text`
5. Full Deploy
6. View Dashboard - widget is _not_ present

Which is the behaviour I would expect. Going to try a partial deploy next.

**Comment by joepavitt** [comment]
Yep, partial deploy causes the problem - suspecting we're caching something in `ui-base`, and so the widget is not cleared from the list. Will dive in further and get it fixed.

Steps to reproduce:

1. Add ui-text
2. Full Deploy
3. View Dashboard - widget is present
4. Delete ui-text
5. Partial Deploy
6. View Dashboard - widget _is_ present
