### ISSUE TITLE
Dashboard should show Connection Lost notification if connection to server is lost

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#618]
With D1, if the connection to the node red server is lost then a Connection Lost notification is shown until the connection is regained.
With D2 there is no such indication, and components such as dropdowns appear to continue to function, but are of course not sending information to the server, and the dashboard is not being updated with current information.  This is a serious issue as, for example, a machine operator might not realise that there was a problem.
The Browser Console does show communications errors when the connection is lost.

To replicate, view the dashboard on a machine other than the node-red server.  Disconnect the network from the machine running the browser.

**Comment by joepavitt** [comment]
Closed by https://github.com/FlowFuse/node-red-dashboard/pull/790
