### ISSUE TITLE
ui-template widget receives no further messages after connection to the server is lost and recovered.

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#619]
Description editted:
After a network connection failure and recovery a ui-template widget does not receive any further messages.

~~On page refresh the last message sent to or received from a ui-template is replayed to it so it can restore its state. However, if the network connection between the browser and the node-red server is broken and then restored the widget is reset in some way such that it loses its data, but the previous message is not replayed.~~

To replicate, configure a ui-template widget with the contents below and feed it into a debug node. Also connect inject nodes that pass in dropdown options that change the selection, or import the full flow below.
Run a browser on a separate machine on the network, and open the Developer Console.
Select an option in the dropdown and it will be seen that the selection is sent to the debug node.
Refresh the browser window. The message is replayed to the template, as can be seen by `console.log()` in the watch msg function, and the selection in the dropdown is restored.
Disconnect the network so the browser cannot communicate with the server and wait a few seconds for connect error messages to appear in the browser console.
Now reconnect the network.  The selection in dropdown disappears.
Click the inject nodes to pass in values, nothing is shown in the log and the dropdown remains blank.

I don't know if there is something missing in the template. I will post on the forum to see if others can replicate this with their template widgets.

```
<template>
  <div>
    <v-select
      label="The label"

      variant="outlined"
      v-model="value"
      hide-details
      :items="items"
    ></v-select>
  </div>
</template>

<script>
export default {
  data() {
    return {
        dropdownData: {options: ['Foo', 'Bar', 'Fizz', 'Buzz']},

        value: "",
    }
  },
  watch: {
    msg: function(){
      console.log(`In watch msg ${JSON.stringify(this.msg)}`)
      if (typeof this.msg.payload === "string" && this.dropdownData.options.includes(this.msg.payload)) { 
        // a valid option received so set display value
        this.value = this.msg.payload
      }
    },
    value: function () {
      // the value has changed
      this.msg.payload = this.value
      this.send(this.msg)
    }
  },
  methods:{
  },
  computed : {
    items: function(){
      return this.dropdownData?.options ?? ""
    },
  }
}
</script>
```

Sample flow
```
[{"id":"1c66450a21990845","type":"ui-template","z":"318b3c8445d47122","group":"d8734fb40940c231","page":"","ui":"","name":"Dropdown test","order":0,"width":0,"height":0,"head":"","format":"<template>\n  <div>\n    <v-select\n      label=\"The label\"\n\n      variant=\"outlined\"\n      v-model=\"value\"\n      hide-details\n      :items=\"items\"\n    ></v-select>\n  </div>\n</template>\n\n<script>\nexport default {\n  data() {\n    return {\n        dropdownData: {options: ['Foo', 'Bar', 'Fizz', 'Buzz']},\n\n        value: \"\",\n    }\n  },\n  watch: {\n    msg: function(){\n      console.log(`In watch msg ${JSON.stringify(this.msg)}`)\n      if (typeof this.msg.payload === \"string\" && this.dropdownData.options.includes(this.msg.payload)) { \n        // a valid option received so set display value\n        this.value = this.msg.payload\n      }\n    },\n    value: function () {\n      // the value has changed\n      this.msg.payload = this.value\n      this.send(this.msg)\n    }\n  },\n  methods:{\n  },\n  computed : {\n    items: function(){\n      return this.dropdownData?.options ?? \"\"\n    },\n  }\n}\n</script>","storeOutMessages":true,"passthru":false,"resendOnRefresh":true,"templateScope":"local","className":"","x":380,"y":600,"wires":[["1a4be2a0a46eb7fc"]]},{"id":"1a4be2a0a46eb7fc","type":"debug","z":"318b3c8445d47122","name":"debug 63","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":640,"y":600,"wires":[]},{"id":"e8e64e4227c5548e","type":"inject","z":"318b3c8445d47122","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Foo","payloadType":"str","x":150,"y":580,"wires":[["1c66450a21990845"]]},{"id":"9dd3fc43170eecd3","type":"inject","z":"318b3c8445d47122","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Bar","payloadType":"str","x":150,"y":640,"wires":[["1c66450a21990845"]]},{"id":"d8734fb40940c231","type":"ui-group","name":"Charger","page":"f33c25a3d1e68ab9","width":"6","height":"1","order":-1,"showTitle":false,"className":""},{"id":"f33c25a3d1e68ab9","type":"ui-page","name":"Charger","ui":"04ee189a49c54f22","path":"/charger","layout":"flex","theme":"23aa79f4e489b044","order":8,"className":""},{"id":"04ee189a49c54f22","type":"ui-base","name":"Dashboard","path":"/dashboard"},{"id":"23aa79f4e489b044","type":"ui-theme","name":"Theme 1","colors":{"surface":"#ffffff","primary":"#514fba","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"},"sizes":{"pagePadding":"1px","groupGap":"1px","groupBorderRadius":"4px","widgetGap":"10px"}}]
```

**Comment by colinl** [comment]
It is worse than I thought, after the network is restored no messages at all are received by the template until the page is refreshed.
For me this is a disaster as one of my systems has a poor network connection and drops out occasionally, which makes the template non-functional.
I will update the description accordingly.

**Comment by colinl** [comment]
In fact it is not necessary to refresh in order to recover the situation, it is enough just to switch dashboard pages and back again.

**Comment by colinl** [comment]
A similar situation is seen if node red is restarted.

**Comment by oriri** [comment]
> A similar situation is seen if node red is restarted.

Got same situation when using these methods for a form
        save() {
            this.msg.payload = this.msg.thing;
            this.send(this.msg);
        },
        resetForm() {
            this.msg.thing = JSON.parse(JSON.stringify(this.originalThing));
        }

ui control node is issuing the events lost, connect, change. 
can confirm that  switching dashboard pages and back again is working

**Comment by colinl** [comment]
Closing this as it is a duplicate of #747
