### ISSUE TITLE
UI-Slider orientation

### ISSUE THREAD

**Issue by Robert-Adamiak** [FlowFuse/node-red-dashboard#624]
### Description

Hello,

Is there any way to change the orientation of a UI slider from horizontal to vertical? In the base dashboard, there was an option for the slider to automatically switch to vertical orientation if its height was greater than its width.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Currently, not an option in Dashboard 2.0, thanks for raising.
