### ISSUE TITLE
Table-UI FR: sort columns by clicking on header

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#626]
As a dashboard user viewing information in a table ui node, I would like to be able to sort the table information per column so that I can more quickly find the information I am looking for.

**Comment by joepavitt** [comment]
Just to note, as I know you just emailed about this too, I am in the process of updating our `ui-table` to use `v-data-table` instead so that this is supported.

**Comment by SynoUser-NL** [comment]
Thanks Joe!
