### ISSUE TITLE
button-group - Output message does not follow widget value configuration type

### ISSUE THREAD

**Issue by arturv2000** [FlowFuse/node-red-dashboard#642]
The widget `button-group` does not send data upon button click as defined on the widget config panel.

If the `value` is defined as `Number` in the output message the payload is a `string`, same thing in case we want to inject a new state for the button group, the value injected in `payload` also needs to be a string regarding the type configured.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/bc3381ea-f15b-4247-b964-fcea38bf4523)

Debug messages from Node `Debug47` is the output of the button-group.

**Comment by joepavitt** [comment]
Thanks for raising @arturv2000
