### ISSUE TITLE
Add Text color option to ui-theme

### ISSUE THREAD

**Issue by arturv2000** [FlowFuse/node-red-dashboard#644]
### Description

When creating a new ui-theme, would be useful to also have an option for default text color used for the widgets.

Has it is right now, if we change the ui-theme to a more "dark theme", we need to always create a template node in order to define CSS overrides for the text color (this happens for text widgets, and other widgets suffer from the same issue, for example slider), and we always need to add the new `class` when configuring the node or have an inject / function to set the correct class for the widgets.

It would be useful that in the future is not necessary to "handle" so much CSS to customize a little bit the dashboard.

Thank You

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Can you screenshot in a sample theme you're setting please? Vuetify is _meant_ to take care of this as the `color` is actually computed based on the background color currently.

**Comment by arturv2000** [comment]
Hi

Sure, this are the settings for the theme

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/6e3fd6d4-4f0a-43b8-ae53-073760be5f12)

And this is an example of the page

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/94561f62-e8d4-45d3-a140-c91912b03adf)

NOTE: The text label "Device Status Code: 0" i purposelly removed the class from the widget configuration.

The label for the slider and for the group buttons color is not "correct" for this kind of background.

NOTE: The text color for `table text` and for the `group title` appears correct without being necessary to do anything, so i assume that for certain parts of the page the `color` is being computed as you indicated by `vue` but seems that for widgets/nodes it is not.

**Comment by hotNipi** [comment]
There is one problem with generated theme to maybe investigate to get a bit better.

Cards (as where most of users place the content) have that rule set by vuetify theme

```
.bg-group-background {
    --v-theme-overlay-multiplier: var(--v-theme-group-background-overlay-multiplier);
    background-color: rgb(var(--v-theme-group-background)) !important;
    color: rgb(var(--v-theme-on-group-background)) !important;
}
```

Why the Important flag used at that level? Important flag is final resort. Almost always avoidable. And should be left for final user to apply if needed. Something is really gone wrong at some point. Maybe that question should go to vuetify people but it is not nice anyhow.

**Comment by joepavitt** [comment]
> The text color for table text and for the group title appears correct without being necessary to do anything, so i assume that for certain parts of the page the color is being computed as you indicated by vue but seems that for widgets/nodes it is not.

This is driven entirely by Vuetify's default theming of `v-label`, I'll look hat overriding it's default within D2.0

**Comment by joepavitt** [comment]
> Why the Important flag used at that level?

Can't recall off top of my head - I agree it's ugly, will try and verify why it's there.

**Comment by m-schaeffler** [comment]
I have also this issue.
Without CSS template it looks like:
![Bildschirmfoto vom 2024-03-28 18-09-00](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/32e8b84e-d87e-49af-b697-faa4e3bd25a9)
With CSS template:
![Bildschirmfoto vom 2024-03-28 18-09-58](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/80f6a714-a96f-48e8-adfe-d741c42b361c)
the CSS style template is:
```css
/* Farben */
label.nrdb-ui-text-label, span.nrdb-ui-text-value {
    color: white;
}
.red label.nrdb-ui-text-label, .red span, .redValue span.nrdb-ui-text-value {
  color: red !important;
}
.green label.nrdb-ui-text-label, .green span, .greenValue span.nrdb-ui-text-value {
  color: LimeGreen !important;
}
…
```
