### ISSUE TITLE
Option to hide the title bar

### ISSUE THREAD

**Issue by postlund** [FlowFuse/node-red-dashboard#645]
### Description

In the regular dashboard for Node-Red, it's possible to hide the title bar which is useful to save some vertical space if left menu is always shown. This is a feature I am currently missing and would love to see added. It is found under `Dashboard -> Site -> Options -> Hide the title bar`.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by arturv2000** [comment]
If possible, when implementing this, could we have the option as in DashBoard 1 default behavior, that the toolbar is always present even in long pages when making scroll.

I use the title bar to add information regarding dashboard operation (in my case, add a clock for reference and the indication of which devices are connected to the dashboard)

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/c9dd2c48-c6c7-420e-9b64-b10f28b85a52)

**Comment by joepavitt** [comment]
> If possible, when implementing this, could we have the option as in DashBoard 1 default behavior, that the toolbar is always present even in long pages when making scroll.

Great idea - shall make it so

**Comment by arturv2000** [comment]
Thanks

This worked.

```css
.v-toolbar {
  position: fixed!important;
  z-index: 1100;
}
```

**Comment by nileio** [comment]
+1 
and reference to this one https://github.com/FlowFuse/node-red-dashboard/issues/791 
I just add that the reason this feature is important is given that we have much more control with Dashboard 2 to inject our own widgets across the UI such as a top-bar we can need an option to hide the default topbar to allow us control the UI from the custom widgets..

thank you

**Comment by nileio** [comment]
@joelvandal was wondering if this feature is planned for release ? I feel it is a small change but will greatly be useful - currently i am doing all sorts of workarounds to show my own topbar but if I can hide the default title bar as we had the option in dashboard 1, this would be great ... thank you!

**Comment by joepavitt** [comment]
Think you were meant to tag me, rather than Joel. It is planned, but so are 200+ other items, so it's a long list I'm working through.

I'll bump it up the list, and try and get it in over the next week or two.

**Comment by nileio** [comment]
my apologies yes actually meant to tag @joepavitt :) thank you and appreciate your hard work, totally understand the list of feature requests is getting longer credit to the number of adopters as well!
eventually once I get to dig in the code a bit I'd be able to contribute - I support the direction of this project and I think it is heading into right directions .. there are some cool ideas that can make this even more awesome so looking forward

**Comment by joepavitt** [comment]
PR created @nileio FYI

It also includes the options as requested by @arturv2000 [here](https://github.com/FlowFuse/node-red-dashboard/issues/645#issuecomment-1997263092)
