### ISSUE TITLE
Cannot load third-party widgets when setting httpAdminRoot

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#649]
Hi guys,

I was migrating some of my custom ui nodes, and their umd files were being loaded without problems.

Now I needed to setup the `httpAdminRoot` in my settings.js file, for example to "my_root".  
However from then on the custom umd files are not loaded anymore:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/f34316c0-b02b-463f-9a71-376be4e34a7a)

The problem is that the third party nodes are loaded from this location:
```
https://my_host_name/resources/@bartbutenaers/node-red-dashboard-2-ui-svg/ui-svg.umd.js
```
However they are available now at the new http admin root:
```
https://my_host_name/my_root/resources/@bartbutenaers/node-red-dashboard-2-ui-svg/ui-svg.umd.js
```
I would appreciate if somebody could have a look at it.  Because to test my web-push ui node, I need to have an SSL connection with LetsEncrypt certificates.  Which are in my setup only available when I use the httpAdminRoot.  So I am a bit stuck...

Thanks!!!
Bart

**Comment by bartbutenaers** [comment]
BTW I am using the latest version of the dashboard...

**Comment by bartbutenaers** [comment]
I had a quick look during my lunch break, and I "think" the `httpAdminRoot` path should be taken into account in [this ](https://github.com/FlowFuse/node-red-dashboard/blob/7988b07b43c9374a794f9052f5c81939f4c38ce2/ui/src/util.mjs#L166) statement:
```
// Load the component library - umd assigns this to window[packageName]
await import(`/resources/${file}`)
```

**Comment by bartbutenaers** [comment]
Hmm I thought to fix this quickly in a PR, but of course the `RED` object is not available on the client side...
So I had a quick look at how you had implemented the `httNodeRoot`.  Am I correct that this parameter is not being passed to the frontend code, but it is used to [construct](https://github.com/FlowFuse/node-red-dashboard/blob/main/nodes/config/ui_base.html#L224) the socket.io path on the server side?  I am not sure at the moment how I need to get the `httpAdminRoot` variable value to the frontend side, or that I have to use it in the server side to construct the path?

**Comment by joepavitt** [comment]
> Am I correct that this parameter is not being passed to the frontend code, but it is used to [construct](https://github.com/FlowFuse/node-red-dashboard/blob/main/nodes/config/ui_base.html#L224) the socket.io path on the server side

We faced this issue a couple of weeks ago, and actually now pass the base root through for this reason. 

We now add a `basePath` property to our `setup` store: https://github.com/FlowFuse/node-red-dashboard/blob/7988b07b43c9374a794f9052f5c81939f4c38ce2/ui/src/main.mjs#L62C9-L62C34

So the solution here would be to pass in VueX into the `util.mjs` file, and use `setup.basePath` accordingly. I should be able to take a look at this today.

**Comment by joepavitt** [comment]
Ah, just realised this is `httpAdminRoot` not `httpNodeRoot`, this is currently not exposed in `setup`. I shall make it so.

**Comment by bartbutenaers** [comment]
Awesome!  Thanks @joepavitt and hope you have a nice weekend!!

**Comment by joepavitt** [comment]
Thanks Bart, this is likely to not get into a release until next week, but changes were lightweight if you do want to just pull them into your local should you need it sooner
