### ISSUE TITLE
Auto Generated Defaults

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#66]
### Description

When first creating a Dashboard, there is an annoying amount of clicking to do just to get a default Dashboard setup. It would be nice if, when dropping in a widget node, the relevant UI config nodes sort themselves out, and can be modified _if required_.

Particularly, this is relevant for Groups, Pages & underlying UI base nodes themselves, as well as the new ui-theme` nodes, where we could provide some nice default theme options to choose from, but provide the singular "Default" theme _without_ needing to manually select that each time.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
Was about to open an issue on this indeed, before i spotted this. Using the dashboard for the first time would benefit from defaults set.

**Comment by joepavitt** [comment]
Complexity in where we inject logic to check this. Ideally, it would be at the point a node is dropped onto the Cnavas, however, I can't seem to find any even that I can hop into here. The `.js` file operates at runtime (after a deployment), and the `html` file just seems to handle `odedit...` events that are related to the sidebar and `onpaletteadd` which is when a node is first added to the side paletter as an option.

**Comment by RickBullotta** [comment]
Another option would be to provide a button or other artifact in the widget configuration to automatically create the group/page/base node is none are assigned. Just need to be cognizant of "node bloat" and orphaned nodes that were autocreated and later overridden.
