### ISSUE TITLE
Clients get out of sync from centralised datastore

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#679]
### Current Behavior

If you have two separate Dashboard clients open and connected to a centralised Node-RED instance with Dashboard 2.0, the server has a single source of truth.

If one client updates that data, e.g. through a toggle switch, the centralised store of data is updated. However, other clients are not aware of this change _until_ they  refresh, which is not the desired behaviour. Any clients connected should update if a client has been the driver of change (i.e. user clicks a toggle).

This already works for all instance where a node is injected with a new value.

### Expected Behavior

All clients should reflect the server-side datastore at all times, unless using multi-user authentication/Dashboards architecture

### Steps To Reproduce

1. Add a toggle switch
2. Open two browsers connecting to the Dashboard
3. Toggle the switch on one of the clients
4. Note that the other client doesn't automically update

### Environment

- Dashboard version: 1.4.0

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
This will require a little re-think of our underlying architecture, as this _should_ just be working out of the box, but the events flow doesn't allow for it currently.

**Comment by joepavitt** [comment]
Forum Discussion: https://discourse.nodered.org/t/how-to-retain-the-state-of-a-button-on-and-off-between-page-updates-and-different-browsers/86404/8?u=joepavitt

**Comment by colinl** [comment]
Also https://discourse.nodered.org/t/dashboard-2-changes-in-one-viewer-not-reflected-in-another/85949/5

**Comment by joepavitt** [comment]
Sorry @uschmelmer - no updates on this currently

**Comment by joepavitt** [comment]
So we use `widget-change` as an event to register a "change: of state. This event is found in:

1. Button Group
2. Dropdown
3. Number Input
4. Radio Group
5. Slider
6. Switch
7. Text Input

I can make them all synchronise, but some of them feel _odd_ to syncronise, particularly 7, and maybe even 2?

**Comment by joepavitt** [comment]
@colinl would really value your opinion here too?

**Comment by colinl** [comment]
I think they should all synchronise.
Text input is conceptually the same as number input, it just happens that one is entering text rather than a number.
Similarly a dropdown is just a text or number input with a limited set of values.

Watch out for the switch node when in 'show state of input' mode.  It would be easy to break that I imagine.

**Comment by uschmelmer** [comment]
Would it be possible to add an option to ui-node's settings to enable and
disable sync. With sync enabled by default?

Colin Law ***@***.***> schrieb am Di., 12. Nov. 2024, 18:04:

**Comment by colinl** [comment]
Can you describe the use case for not wanting sync?

**Comment by uschmelmer** [comment]
At least for text input it could be usefull to disable sync for example if
you want to gather log input simultaniously  from different terminal
stations.

Colin Law ***@***.***> schrieb am Di., 12. Nov. 2024, 18:57:

**Comment by joepavitt** [comment]
> Can you describe the use case for not wanting sync?

In all of your internal Dashboards at FF, I would say we'd favour no syncing, but in the HMI use case on a Factory Floor, I can see the sync being favourable.

I built a first iteration today, ans it works very well, and utilises the existing "Client Data" tab, where you can check on/off syncing already, to decide whether to sync to different sessions or not.
