### ISSUE TITLE
Subflows: Element Sizer widget doesn't work after being placed inside a subflow

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#683]
### Current Behavior

When creating a subflow with Dashboard 2.0 nodes inside, the `elementSizer()` widget (where you define the size of a widget on a Dashboard 2.0 node) is not functional.

### Expected Behavior

Users should be able to set _any_ width and height of their widgets when inside a subflow (as a quick MVP improvement for this)

Future improvements could be a modification to the `lementSizer()` such that we can define `auto` in a single direction, i.e. `4` in height, but `auto` the width to fill it's parent/group

### Steps To Reproduce

_You will need the Node-RED `4.0.0-beta` for this to be reproducible._

1. Create a new subflow in Node-RED
2. Drop any Dashboard 2.0 node into that subflow
3. Double-click the new node, and try to modify it's size.

### Environment

- Dashboard version: `1.4.0`
- Node-RED version: `4.0.0-beta`

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
Ideally I would like to be able to set the size via subflow properties.

**Comment by joepavitt** [comment]
> Is it time to switch to typedInputs for width and height props?

I'm not convinced by this as a user experience - the existing widget is useful because it's context/group aware for the maximum value. However, having the width/height separately definable as "auto" (or "fill" as a new option?) could be very nice.

**Comment by joepavitt** [comment]
We could split this into:

1. Change the widget to be a typed in put with `auto`, `num` and `env` (Size 3 is probably appropriate)
2. Introduce the "fill" option (probably a size 3/5 on it's own)

**Comment by Steve-Mcl** [comment]
> 1. Change the widget to be a typed in put with auto, num and env (Size 3 is probably appropriate)

I can pick this up as described in item 1. 

Just need to double check:
 - this is for `group` widget only? or all places where a sizer exists?
 - there will be 2 inputs (height & width) both having `Auto`, `num`, `env`
    - for `num`, will there be any validation?

Alternatively, we could keep the sizer and add a checkbox "override size" (or similar) that swaps the sizer for the 2 inputs (that would permit Env Var syntax)

**Comment by joepavitt** [comment]
> this is for group widget only? or all places where a sizer exists?

Good point, the core problem here is that the Widget's themselves don't have a functioning `elementSizer` widget when inside a subflow. As such, I vote:

Iteration 1 - if no group found, or if the group is an env-var, allow for any size definition on the widget `elementSizer` - that closes this issue.

Further iterations then seek to capture what is discussed here, and I'll open new issues accordingly, which could include the switching to TypedInputs, etc.

**Comment by Steve-Mcl** [comment]
Joe, a compromise to achieve a level of automation might be:

If the UI node is inside a subflow, show typedinputs that permit `auto`, `num`, `env`

This way, regular uses of nodes (outside of subflow) get the familiar sizer

Users attempting do RAD with subflows will need to set values or env vars. (i mean the sizer currently doesnt work nor makes sense in the subflow as is anyhow right?)

**Comment by joepavitt** [comment]
Let's do it @Steve-Mcl - I'm still cautious of over-scoping/over-engineering here in order to resolve the issue at hand. Please don't get carried away.

**Comment by Steve-Mcl** [comment]
As discussed and demoed, the sizer is now displayed as text boxes instead (MVP - in that users can freely set width or `${env}`

If the feature gets used and improvements are requested, this can be a 2nd iteration.
