### ISSUE TITLE
Notification : OK/Cancel Dialog

### ISSUE THREAD

**Issue by borega94** [FlowFuse/node-red-dashboard#689]
### Description

It would be useful if there was not only one option to close notifications.

As in Dashboard 1.0, there is an option to have one button for OK and one for Cancel.

For example, you have a button to delete a file and then a notifitcation where you ask the user "Sure" or "Cancel".

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by colinl** [comment]
I think this is a duplicate of #193

**Comment by borega94** [comment]
@colinl I think you're right.
