### ISSUE TITLE
Add client IP address in msg._client.user object

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#694]
### Description

Request to add the client IP address from a Dashboard user (DB instance under FlowFuse) in the msg._client.user object.
As discussed on NR Forum: https://discourse.nodered.org/t/client-ip-address/86594

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Closed by #957

**Comment by SynoUser-NL** [comment]
Thank you!
