### ISSUE TITLE
Issue with colors in tables when using template

### ISSUE THREAD

**Issue by arturv2000** [FlowFuse/node-red-dashboard#698]
### Current Behavior

Hi

Just updated to V1.5.1 and noticed a significant change.

I have some custom tables (using template node) and with the new version they all have a "background" color, they seem to have the color `--v-theme-surface` by default, this behaviour did not happen in V1.4.1. Table defined with `v-data-table`.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/49e1a189-ba6f-4839-ac85-6b6eae5fb2af)

The one on the right is a table with custom template (is not yet "fixed"), the table on the left is already "fixed", added `style="background-color: rgb(var(--v-theme-group-background));"`

### Environment

- Dashboard version: V1.5.1
- Node-RED version: v3.1.7
- Node.js version: 20.11.0
- npm version: 10.4.0
- Platform/OS: Ubuntu 22.04.3
- Browser: Edge 122.0.2365.92

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
This seems to also occur for other Vuetify widgets too - not sure if was triggered by a Vuetify version bump. Will take a look at get the default styling consistent.
