### ISSUE TITLE
Text input node in a subflow crashes Layout Order Editor

### ISSUE THREAD

**Issue by phfeustel** [FlowFuse/node-red-dashboard#709]
### Current Behavior

Using a text input node in a subflow crashes Layout Order Editor.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at <anonymous>:753:84
    at Array.filter (<anonymous>)
    at <anonymous>:753:63
    at Object.eachNode (red.min.js?v=:16:57181)
    at Object.eachNode (red.min.js?v=:16:87852)
    at buildLayoutOrderEditor (<anonymous>:747:19)
    at refreshSidebarEditors (<anonymous>:905:13)
    at later (<anonymous>:44:38)
```

I dug a bit into it and I think the line to blame is [this one:](https://github.com/FlowFuse/node-red-dashboard/blob/66d3aaa6036e34fad1c26abdbfcc78c61286209a/nodes/config/ui_base.html#L1085) 
In my case, when looking into the JS object and also the exported flow JSON `env` on the subflow does not have any `ui` property.

So, one way to fix this, could be to switch the comparisons from:
`subflowDef.env.filter(env => env.ui.type === 'conf-types' && env.type === 'ui-group')`
to 
`subflowDef.env.filter(env => env.type === 'ui-group' && env.ui.type === 'conf-types')`

### Expected Behavior

After adding a text input node in a sub flow the layout order editor is still functional.

### Steps To Reproduce

1. Create a page
2. Create a subflow containing a text input node
3. Add the sublfow to the page
4. See the contents of the Dashboard 2.0 Layout Order Editor disappear

### Environment

- Dashboard version: 1.4.1
- Node-RED version: 3.1.3
- Node.js version: 16.20.2
- npm version: 8.19.4
- Platform/OS: macOS Ventura 13.4.1 (22F82)
- Browser: ARc Version 1.35.0 (47750) Chromium Engine Version 123.0.6312.59

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
fyi @Steve-Mcl

**Comment by colinl** [comment]
Using node-red 4.0.0 Beta 1 I am not able to replicate the issue.
I thought it was necessary to use v4 when using dashboard nodes in a subflow.

**Comment by phfeustel** [comment]
@colinl Thanks for the hint. Would you please point me to the documentation on this?

**Comment by phfeustel** [comment]
@colinl I think I found what you meant: https://dashboard.flowfuse.com/user/subflows.html#configuring-subflows-for-dashboard-2-0

But luckily my use case does not need configurable ui-groups; the group where the text input should be displayed in is static. 

In any way, I guess, the bug mentioned above is worth fixing.

**Comment by phfeustel** [comment]
@joepavitt thanks for the feedback.

I did a quick retest on Node-RED: 4.0.0-beta.: Same issue; I think the comparison code from above is just bugged and needs switching the conditions.

<img width="980" alt="image" src="https://github.com/FlowFuse/node-red-dashboard/assets/22401554/a2e07148-4652-4ff8-99b8-c05336b6c16c">

**Comment by colinl** [comment]
Just checking, did you restart node red?
Add I said, I don't see the issue.

**Comment by phfeustel** [comment]
Yes, I'm using node red in docker: Stop the 3.1.3; pulled the 4.0.0-beta image; started this and then did a full page refresh in the browser.

**Comment by phfeustel** [comment]
@joepavitt Any update or ETA?

As a side node: I patched the line above in my local installation and it is running now for 3 weeks stable. Should I open an pull request?

**Comment by joepavitt** [comment]
> Should I open an pull request?

please, PRs are always welcome, never need to ask for permission :)

**Comment by phfeustel** [comment]
Closed by https://github.com/FlowFuse/node-red-dashboard/pull/800
