### ISSUE TITLE
support HTML in msg.payload of ui-text.

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#715]
### Description

I sometimes use HTML in the format property of dashboard 1.0 `ui-text`.

As this is no longer available, I tried to use HTML in `msg.payload` instead.
This HTML code is not executed but just written out:
![Bildschirmfoto vom 2024-03-28 18-21-18](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/2f746373-dcd5-4afc-81aa-9441c2e0c0b0)

It's clear that this is due to injection attacks. Would it be possible to have a switch in the `ui-text` to allow HTML in the `mag.payload`?

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by colin-grierson** [comment]
This is similar to #615 "Markdown-UI & Template-UI node do not process HTML\Markdown sent to it by NR Template node"

**Comment by joepavitt** [comment]
This is now supported and was closed with https://github.com/FlowFuse/node-red-dashboard/pull/1046
