### ISSUE TITLE
Properties are missing in config page o ui-button

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#716]
### Current Behavior

In the config page of `ui-button` these parameters are missing:
- Icon
- Icon Position 
- Label

![Bildschirmfoto vom 2024-03-28 18-43-20](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/5515f9db-6407-4835-aa0a-ccfcd52d609b)

### Expected Behavior

The parameters are shown and working.

### Steps To Reproduce

open a `ui-button` to edit its parameters.

### Environment

- Dashboard version: 1.6.0
- Node-RED version: 3.1.8
- Node.js version: 20.12.0
- npm version:
- Platform/OS: RaspberrypiOs
- Browser: Firefox 124.0.1 on Ubuntu 23.10

### Have you provided an initial effort estimate for this issue?

I'm not a member of flowfuse

**Comment by joepavitt** [comment]
Published in the [1.6.1 release](https://github.com/FlowFuse/node-red-dashboard/releases/tag/v1.6.1)

**Comment by joepavitt** [comment]
Thanks for spotting this @m-schaeffler 👏

**Comment by m-schaeffler** [comment]
I confirm the issue is fixed
