### ISSUE TITLE
Navigation Bar does not collapse after page change

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#727]
### Current Behavior

Navigation Bar does not collapse after a new page was selected.

### Expected Behavior

Navigation Bar does collapse after a new page was selected.

### Steps To Reproduce

Set the `Style` of `ui-base` to `Collapsing`.

### Environment

- Dashboard version: 1.6.1
- Node-RED version: 4.0.0 beta1
- Node.js version:
- npm version:
- Platform/OS: Raspberry OS
- Browser: Firefox / Ubuntu

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by joepavitt** [comment]
Could you grab a screen recording of this please?

**Comment by m-schaeffler** [comment]
And as a reference the dashboard 1:
1. I open the navigation bar
2. select a page
3. and the navigation bar closes by itself
[dashboard_1.webm](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/649c41a6-af95-4cca-8612-31bc0d628860)

**Comment by joepavitt** [comment]
Ah, perfect, now I understand the request, thanks!
