### ISSUE TITLE
Docs: Update docs homepage with improved links and CTAs

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#729]
### Description

Docs home page was built as a very quick first iteration, and with current traffic, feel like we could provide better information and more useful resources to the users visiting the site. This is our PH heatmap for the past 7 days:

<img width="1457" alt="Screenshot 2024-04-02 at 17 21 32" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/9a3b6c89-7d49-4088-b6e6-fd39ca917546">

**Proposal:**

- Remove the three tiles and replace them with "Recommended Reading" & move "Diverse Widget Collection" to be a third pill CTA
- Add CTAs for FlowFuse below this to help people get started with a NR Instance quickly.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@joepavitt There's two links to GH now, in the middle and top nav bar. Seeing how little contributions we get I'd remove the button in the middle.

The more colorful display of recommended reading I think is a good iteration. I'd like to get one of those 3 when there's an e-book to download. But that's a nth iteration thing.

**Comment by ZJvandeWeg** [comment]
@joepavitt Wouldn't it be nice to show the string to search for in Node-REDs manage pallette on the landing page? That's the one thing you'd like to know as Node-RED dev?

**Comment by joepavitt** [comment]
> There's two links to GH now, in the middle and top nav bar. Seeing how little contributions we get I'd remove the button in the middle.

There always has been, but I'm glad you've said that as I wanted to do the same. I shall remove it.

**Comment by joepavitt** [comment]
> Wouldn't it be nice to show the string to search for in Node-REDs manage pallette on the landing page? That's the one thing you'd like to know as Node-RED dev?

I'll see what I can do
