### ISSUE TITLE
FR Notification: ability to close a notification with an input message

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#733]
### Description

We are using the Notification node to display a Please wait.. message for actions that take a little bit of time. It would be nice to be able to have the flow close the Notification once the action is completed.
Currently, the only possibility is to have the Notification time-out or have the user close the Notification.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by SynoUser-NL** [comment]
Thanks @joelvandal ! 
Tried your solution and this works exactly how I think the Notification node should behave. So great work!

That being said, I do think that this functionality should be part of the DB2 Notification node. The bit you're doing in the <scripts> section and even the <v-card-actions> section isn't really low-code anymore, so adjusting this for more buttons would not be easy for most low-code users. Also, when trying with the Cancel button enabled, clicking that button does not generate a payload message to take action on (although I'm sure that could be programmed into the behaviour of the modal).

For us, should we want to make NR instances available for more people to be used as a low-code solution, we'd like something like your solution to just be possible with the standard Notification node that is also maintained as part of the Dashboard package.
Hoping that you and @joepavitt  agree..

**Comment by SynoUser-NL** [comment]
Looks great!
So this will be an additional Dashboard 2 node, to be installed with the Palette Manager?

**Comment by Steve-Mcl** [comment]
This is more possible via #932
