### ISSUE TITLE
Dashboard Buttons Not Using Custom Theme

### ISSUE THREAD

**Issue by jtempletmg** [FlowFuse/node-red-dashboard#746]
### Current Behavior

I created a V2 dashboard where I used a custom theme.  I then added a button to the dashboard. The button did not use the custom theme (used the default theme instead).

![image](https://github.com/FlowFuse/node-red-dashboard/assets/30485733/6c65e11f-7ba6-486c-a901-5467fb15a9e1)

### Expected Behavior

Buttons should use the "Primary" color for buttons or perhaps there needs to be another option for widget color?

### Steps To Reproduce

* Create a dashboard
* Add a custom theme, changing all color options in the theme to something other than the default
* Add a button to a page
* Deploy - observe button uses the "Default" theme still

### Environment

- Dashboard version: 2.0
- Node-RED version: 3.1.7
- Node.js version:  ???
- npm version: ???
- Platform/OS: Raspberry Pi 4
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Can you send over a screenshot of your theme please?

**Comment by joepavitt** [comment]
This is my testing locally, and it behaves as I would expect:

<img width="473" alt="Screenshot 2024-04-05 at 17 03 28" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/c3b6e098-bccc-4daa-8c00-d307193987df">
<img width="740" alt="Screenshot 2024-04-05 at 17 03 45" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/32633976-c868-45e3-93f6-947edf2fe9a5">

**Comment by jtempletmg** [comment]
@joepavitt as requested:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/30485733/2e411a83-606a-4e95-91d0-33a855c44172)

**Comment by joepavitt** [comment]
Are you doing a full deploy or partial deploy?

**Comment by jtempletmg** [comment]
Full

**Comment by joepavitt** [comment]
Looking at your project, you have two themes:

<img width="482" alt="Screenshot 2024-04-05 at 18 04 08" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/11605eea-7d7b-4d30-8483-11ae6c4237c2">

One still has the Primary set to Blue, and is used by all 4 pages.

**Comment by joepavitt** [comment]
I won't make changes directly to your flows, but that will definitely be the problem. Please do close the issue once you've verified.

**Comment by jtempletmg** [comment]
That did it!
