### ISSUE TITLE
Allow form elements to be pre-filled

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/node-red-dashboard#760]
### Description

**As a:** D2.0 user

**I want to:** pre-fill some form elements like in a data picker todays date

**So that:** forms can be filled out much faster

### Which customers would this be availble to

None

### Acceptance Criteria

- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3
- ...

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by colinl** [comment]
I believe that this is a duplicate of #363

**Comment by ZJvandeWeg** [comment]
Correct, thanks @colinl!
