### ISSUE TITLE
Themes edit floats randomly through dashboard layout

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#768]
### Current Behavior

The dashboard themes float randomly through the side panel layout.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/2cb6ec84-5c0b-4bd0-a361-e177e4e64ff1)

### Expected Behavior

I don't expect themes to be be shown at all in the layout tab as they have their own tab.

### Steps To Reproduce

Use the dashboard layout tab.
I suspect that you may need a few pages and groups as I am not sure when they started to show up.

### Environment

- Dashboard version: 1.7.1
- Node-RED version: 3.17
- Node.js version: 20.11.1
- npm version: 10.2.4
- Platform/OS: Windows 11
- Browser: All

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by thebaldgeek** [comment]
Yes to both.
(And I see that mine is a triple post of the issue, sorry about that - my search skills are clearly lacking).

**Comment by joepavitt** [comment]
Yeah, this is odd, as it was definitely fixed in `1.7.0` with https://github.com/FlowFuse/node-red-dashboard/pull/744

**Comment by thebaldgeek** [comment]
After a restart of Node-RED, I no longer see this issue.
