### ISSUE TITLE
Gauge node is not responsive

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#769]
### Current Behavior

When viewing gauges on mobile, they are too small to read.

Gauges on desktop / laptop:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/8d15ac75-4d92-4951-a85d-0fb47d8b584c)

(Note, not sure why the top three are super jumbo sized, they are all built the same and no changes made from default - They all should be the same size as the KBOS on on the bottom).

When viewed on Android or iPhone the gauges look like this:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/3d4429d3-a722-4627-b649-f11dad1f3e2a)

### Expected Behavior

I would expect the gauge to be rendered differently on a small screen, or drop to a text only display of the value.

### Steps To Reproduce

Place two or more gauges on a group.
View on mobile device or F12 -> mobile view on a browser.

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by thebaldgeek** [comment]
From a post in the Node-RED Discord.
http://temples.tplinkdns.com:2880/dashboard/current
(Note, the site seems to be down quite often)

Here is how the weather page looks on a Pixel 7 and 8.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/62e46c52-91f3-463e-8929-b9fb6ce98161)

**Comment by jtemple967** [comment]
@thebaldgeek I think you may have copied/pasted the wrong link. I actually had 2 dashboards available for public viewing for a while, here's the one for the weather:

http://temples.tplinkdns.com:1880/dashboard/current

**Comment by joepavitt** [comment]
Closing this out as I think https://github.com/FlowFuse/node-red-dashboard/pull/979 covers a fix for this. It wasn't an issue with gauges per say, more that our breakpoints on this screen size weren't sensible, so we were trying to squeeze too much content in horizontally.
