### ISSUE TITLE
ButonGroup: add JSON aus output format

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#776]
### Description

Please add JSON as a possible output format for button group.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by m-schaeffler** [comment]
My use case as an example:
![2024-04-17 08_32_13-Node-RED _ Diagramm – Mozilla Firefox](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/fdb6ec87-3771-49c8-b9a1-9a61dd8e9ac4)
![2024-04-17 08_32_36-Node-RED _ Diagramm – Mozilla Firefox](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/dba3c490-83b1-4d4b-9f94-e1d605e6db83)

**Comment by bartbutenaers** [comment]
@joepavitt,
If it can be of any help to reduce your todo list a bit, I can have a look at this one.  Just let me know...
Bart

**Comment by joepavitt** [comment]
> If it can be of any help to reduce your todo list a bit, I can have a look at this one. Just let me know...

Always very welcome ❤️

**Comment by bartbutenaers** [comment]
[Pull request](https://github.com/FlowFuse/node-red-dashboard/pull/780) created.
