### ISSUE TITLE
Button: Add passthrough

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#777]
### Description

Plaease add such a passthrough option also to the button widget:
![2024-04-17 08_35_41-Node-RED _ Diagramm – Mozilla Firefox](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/ef7f8ad2-a158-48f4-b734-38bd002c5635)

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by colinl** [comment]
Is issue #209 actually what you are looking for?

**Comment by joepavitt** [comment]
Closing as duplicate of #209 - will prioritise as now requested by more than one person.

**Comment by joepavitt** [comment]
hmm, actually they're

**Comment by colinl** [comment]
I can't see the point in just passing through.  If that is required then just wire round the button.

**Comment by m-schaeffler** [comment]
yes, emulate a click fulfills my needs
