### ISSUE TITLE
Chart: set a complete multiline chart with one single message.

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard#786]
### Description

Please add a way to set a complete multiline chart with one single message.
I do this at the moment with one message per line and this gives not a high quality experience.

see this screen cast:
[Bildschirmaufzeichnung vom 2024-04-18, 19-12-14.webm](https://github.com/FlowFuse/node-red-dashboard/assets/31366299/0c160529-9479-4689-aeb7-42c50143589b)

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by arturv2000** [comment]
Hi

You can do that in a single message, the way I do it is as follows:

Example:

```javascript
let _data = [];

msg.payload.channel.forEach(function(element) {
    if(element.isError == false){
        _data.push({name: element.Name, val: element.Val});
    }
});

return {payload: _data};
```

This is for a single point insertion per message.

And in the Chart configuration set as:
![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/f42e9918-7ddf-4236-bb39-19d6b857aa07)

**Comment by m-schaeffler** [comment]
I tested this: it is working fine and even simplifies the code generating the chart.
