### ISSUE TITLE
SideBar related to DashBoard2 empty

### ISSUE THREAD

**Issue by arturv2000** [FlowFuse/node-red-dashboard#789]
### Current Behavior

Not sure if this is a Node-Red issue or a DashBoard2 issue.

Was "playing" with Sub-Flows using Node-Red V4.0-Beta2 and something unexpected happened.

Don't know why, but the side bar that shows the dashboard widgets (pages / group / widget) is blank.

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/6cadf123-2daa-4ce7-872f-0c03bc90a8c5)

The browser is generating error in console when accessing that sidebar tab

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/416c7528-52c9-469e-88d2-23d0ddbc39b3)

### Environment

- Dashboard version: v1.7.1
- Node-RED version: 4.0.0-beta2
- Node.js version: 20.12.2
- npm version: 10.5.0.0
- Platform/OS: Ubuntu LTS 22.04.4
- Browser: Edge 123.0.2420.97

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by arturv2000** [comment]
Just to update, if i delete all the subflows from the project (not the subflow itself, all the nodes with the subflows), the sidebar restores to default behavior.

If i place a single subflow it will crash.

https://github.com/FlowFuse/node-red-dashboard/assets/17281826/66ea4d46-61ff-4938-abc0-9d60864927b1

**Comment by colinl** [comment]
I am pretty sure this was fixed just in the last few days, but I can't find it.  If I am right then the fix should be in the next D2 release.

**Comment by colinl** [comment]
This is it, #709.  I think this is a duplicate of that one.
It does not look as if it has been fixed yet, though the cause has been identified.

**Comment by arturv2000** [comment]
Thanks.

I don't have a text input, but 3 drop downs, 2 sliders, 2 buttons and two text (labels).

Will try the fix mentioned on the issue.

**Comment by colinl** [comment]
> I don't have a text input,

Probably any ui node may cause the problem.

**Comment by arturv2000** [comment]
OK, was able to test.

The issue (at least in my case) was not with any ui-node, the issue stated appearing when i added a enviroment variable (text type)

![image](https://github.com/FlowFuse/node-red-dashboard/assets/17281826/c9f4e22b-cb8f-4dd4-a5f2-9ede7e822421)


If I remove the environment variable, the sidebar will load OK.

Tried to apply the fix indicated in #709 and it is working.
