### ISSUE TITLE
Option to hide the top bar

### ISSUE THREAD

**Issue by nileio** [FlowFuse/node-red-dashboard#791]
### Description

In Dashboard 1, we have an option to hide the title bar as below screen shot

![2024-04-20_19-16-12](https://github.com/FlowFuse/node-red-dashboard/assets/24714766/024b9d9e-900c-478d-bd95-2fc1df54138f)

we require a similar option in Dahboard 2 against the page or the entire UI to hide the top bar of the page or rather across the entire UI. In my current implementation, I am using a custom widget which is in itself a topbar with my own custom implementation, however, for this to correctly work the topbar should be hidden.

Thank you.

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by arturv2000** [comment]
Already requested, #645

**Comment by nileio** [comment]
@arturv2000 sorry did not realise it was already requested and not yet implemented -- I would close this and reference it is managed with the other issue 
https://github.com/FlowFuse/node-red-dashboard/issues/645
