### ISSUE TITLE
ui-template: template is not rendered until content is sent

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#796]
### Current Behavior

In the UI-Template node, a <v-container> contains one or more <div>'s that display information from a message ( like {{msg.payload.item}} ).
<div>'s are not displayed until the template node receives a message providing the content.

### Expected Behavior

<div>'s are rendered on the page without the content that is to be received by the message information (empty, but the outline of the page (template) layout is visible). 
When the message is received, the <DIV's>then display the information in the message within the defined page (template) layout.

### Steps To Reproduce

Place:

```
<template>
  <v-container class="message-container">

        <div class="message-header">
          Please check the data below!
        </div>
        <div class="message-details">

          <div class="category-container">
            <div class="category-header">
              <v-icon class="mdi">mdi-ticket</v-icon>Ticket #:
              <span class="small-text">{{ msg.new_data.ticket }}</span>
            </div>
          </div>
          
        </div>

  </v-container>
</template>
```

in a ui-template node and Deploy.
The `<div>` is only displayed when a message is reveived containing data.ticket.

### Environment

- Dashboard version: 1.7.1
- Node-RED version: 3.1.7
- Node.js version: 18.19.1
- npm version:
- Platform/OS:
- Browser: Edge, Firefox, Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by SynoUser-NL** [comment]
The workaround for this now is to send a message with empty keys, which displays the div's. However this adds (in my view unnecessary) complexity to flows.

**Comment by colinl** [comment]
If you show the browser developer console you will see your template gives an error on initial display
`TypeError: Cannot read properties of undefined (reading 'ticket')`
because msg is not defined the first time it attempts to show it.
Instead use something like
` <span class="small-text">{{ msg?.new_data?.ticket ?? "" }}</span>`

**Comment by SynoUser-NL** [comment]
Hmm.. thanks!
That is a much better workaround.
Can I ask where you've found the information on that ? syntax ? We've missed that bit..

**Comment by colinl** [comment]
That is standard (modern) javascript. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Keep in your mind while coding in templates that data may not yet be present, and code accordingly.

**Comment by SynoUser-NL** [comment]
Thanks! Learned something new.. :)
