### ISSUE TITLE
ui-table: possibility to hide array values that are displayed

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#804]
### Description

When sending an array to the ui-table node, all array keys are displayed. Great!
However, some data may not be of interest for the user but would be nice to have once the user clicks on a (or multiple) rows, like for instance a database row id.
Would it be possible to add a field in the configuration where one can define one or more column names that are not visible, but are sent as part of the messsage when the user clicks on the row?

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
> Would it be possible to add a field in the configuration where one can define one or more column names that are not visible, but are sent as part of the message when the user clicks on the row?

You already can - that's the "Auto Columns" option.

**Comment by joepavitt** [comment]
<img width="480" alt="Screenshot 2024-04-26 at 16 23 44" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/84de20f3-8478-44a1-88d3-0bcdffb9d848">

**Comment by SynoUser-NL** [comment]
Sorry, completely overlooked this..
Thanks!
