### ISSUE TITLE
Ditch the Connection Re-established popup!

### ISSUE THREAD

**Issue by colinl** [FlowFuse/node-red-dashboard#811]
### Description

The Reconnecting message that appears after a connection failure is very annoying, as it appears for several seconds almost every time I bring the dashboard to the foreground on Android.  I don't thinks it conveys any useful information.  I cannot safely click the Close button because if one is a fraction of a second late clicking it then the widget underneath receives the click.

### Have you provided an initial effort estimate for this issue?

I am not a flowfuse employee

**Comment by cgjgh** [comment]
If I may interject, perhaps making notification configurable, allowing en/disabling and setting of notification dismiss delay, would be a better approach here. I myself and @Paul-Reed, if I recall correctly, in addition to the maintainers I’d assume, find it useful.

**Comment by colinl** [comment]
> I myself and @Paul-Reed, if I recall correctly, in addition to the maintainers I’d assume, find it useful.

In what way do you find it useful? I can see that during debugging that may have been the case, but once the comms failure notification is working correctly then the fact that the failure popup is not there means that the connection must have been restored.  There is no such indication in Dashboard 1, the fact that the Connection Failed message is not shown indicates that all is well.

**Comment by cgjgh** [comment]
> the fact that the Connection Failed message is not shown indicates that all is well.

Good point. Notifications should logically appear as a result of an exception, in this case communication failure. That said, reconnection notification would seem more appropriate in a debugging capacity.

I do however enjoy regularly being able to see a visual indicator that my data is live, but something less intrusive like a green/red circle at top right of header could suffice.

That’s my perspective on the issue, but the final decision rests with the maintainers.

**Comment by cgjgh** [comment]
Any thoughts on an always present circular status indicator in top right corner as an optional alternative to the notifications? Something like the one I'm using below:
![Status Indic](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/23909800-30ae-4812-8d93-8c67e7d7b021)

**Comment by joepavitt** [comment]
I'm happy to add this as an example in the "Template Examples" docs, but I'm not sure I can be convinced of this being the default., or as part of core, as it would interfere with any `app-bar-actions` that users define.

**Comment by cgjgh** [comment]
Ah yes, it would definitely interfere. 

But what about something smaller like this? But choice is totally up to you.![Screenshot 2024-05-12 144931](https://github.com/FlowFuse/node-red-dashboard/assets/160297365/9d3505da-7aa2-4e3d-b60a-06501d3cd6a1)

**Comment by nileio** [comment]
@cgjgh I guess the point is that given the top right side of the bar is completely configurable , it is not advisable to have anything in there at all whether small or large - for example we have custom toolbar actions extensions in there.. having said that I am also not a big fan of popup notifications at all and in fact wish we ditch any sort of popup notifications everywhere unless absolutely necessary to convey a critical state that requires user intervention or alert

**Comment by colinl** [comment]
I still don't see the need for a 'reconnected' popup.  D1 does not have one, the connection lost message just disappears, and I don't remember anyone ever asking for it.

**Comment by cgjgh** [comment]
Not sure if anyone else has had this problem, but I’ve quite often had times where even though Dashboard was disconnected the alert didn’t show which was my reason for wanting an always present indicator. On any socket connect or disconnect event it sets a connected variable which indicator is mapped to. This has proved much more reliable than the alert, with indicator being correct 100% of the time.

But just testing the waters here, if no one else has this issue then it’s definitely not necessary to add it.

**Comment by colinl** [comment]
I have not seen that issue.  Since the disconnected was introduced then it seems to have been reliable.
