### ISSUE TITLE
Add "development" NODE_ENV option for build

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#819]
Hi guys,

In the [vite.config.js](https://github.com/FlowFuse/node-red-dashboard-2-ui-example/blob/main/vite.config.js#L16) file of the *node-red-dashboard-2-ui-example* repository there is a mechanism available to skip the minification of the code during development.  Which I use in this way:

1. Set the related environment variable during development:
   ```
   export NODE_ENV=development
   ```
2. Create a bundle:
   ```
   npm run build
   ```
3. Now I can debug the frontend code in the vue file easily because I see the original code.

However I don't see that variable in the dashboard.  Instead I see in the [package.json](https://github.com/bartbutenaers/node-red-dashboard/blob/4d691e55b9e1837ef8d39e744dfa672fcafbde6a/package.json#L34) file another mechanism.  So not sure if my above way of working is optimal...

Could anybody enlighten me a bit what is the best way to use this, and why the custom nodes need to use that environment variable.  Or is there perhaps a relation between the build:dev and the NODE_ENV?  Because I would like to see both the dashboard code and my own custom node code without minification...

Thanks!
Bart

**Comment by joepavitt** [comment]
Not necessarily an intentional play here. Think this was just overlooked when doing the build pipeline for Dashboard as `vite` was introduced after some time of already having a webpack build in place. For the UI Example, we built that using a template generator, so it would have come packaged with it.

Will update this to be requesting a "development" mode for working with Dashboard

**Comment by bartbutenaers** [comment]
Thanks!
But how can I avoid the dashboard to be minified?

**Comment by joepavitt** [comment]
> But how can I avoid the dashboard to be minified?

Currently, not a configuration option

**Comment by bartbutenaers** [comment]
Going to close this issue since the [pull request](https://github.com/FlowFuse/node-red-dashboard/pull/834) is merged
