### ISSUE TITLE
Add a way to pass parameters to a page

### ISSUE THREAD

**Issue by nileio** [FlowFuse/node-red-dashboard#820]
### Description

per slack discussion,
provide a way to pass URL parameters to a page , that is `?param1=x&param2=y` should be parsed into an object of `params` which can be accessed by any `ui-template`
I believe @joepavitt mentioned that this can then be accessed via `this.$route`

-- Use case --

Dashboard home page contains a list of devices using a table component or a ui-template. A second details page contain widgets to provide detailed information about the device. On clicking on a specific device on the main home page, it should navigate to the details page, and list the details for that device. The details page should then access the `params` provided in the URL of the page via `this.$route` or other mechanism to avoid using other external libs or workarounds to retrieve the list of params passed to the page..
Currently we have `ui-control` emits a `msg` with a `payload` of "change", and `tab` (aka page) index , and `name` of destination page. Also `ui-event` node emits a `msg` with a `topic` of "$pageview"
from a `ui-template`, I would like to access the `params` passed to the page.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by thebaldgeek** [comment]
+1 for this feature. It is an often requested feature from my site users... To be able to click on a table element and navigate to a details page about that cell text that was clicked.
Right now, you have to highlight the cell data, copy it to clip board, navigate to the new details screen and paste in the text and click the 'search' button to get the data.

**Comment by joepavitt** [comment]
Thanks for the +1, will try and make it a priority given its popularity, should be able to get it in next week

**Comment by joepavitt** [comment]
Two required pieces to ensure this is functional:

- UI Event: Make sure we include the `query` fields here on any `$pageview` events
- UI Control: Make it easy to define query fields for a given page navigation payload
