### ISSUE TITLE
UI Text cuts off content

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#827]
### Current Behavior

Capturing a specific issues raised in this comment:https://github.com/FlowFuse/node-red-dashboard/issues/767#issuecomment-2090635687

### Expected Behavior

The examples detailed have 2 x `ui-text` widgets:

- 2 x 1 sixes and left-aligned
- 3 x 1 sized and centre-aligned

I see three options here with respect to how to handle the responsiveness:

#### 1. Very Strict Height

The user would have selected a specific size to render each ui-text widget, e.g. `2 x 1`. As such, it should be rendering with a height of "1" row, and not wrap the content.

<img width="278" alt="Screenshot 2024-05-07 at 14 05 42" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/3d9eb7e2-4d83-43a6-8aa0-76b505887513">

We should however format the cut off content with ellipsis. If we choose this route, we end up with the above example

#### 2. Mostly Strict Sizing

We allow for the two elements inside ui-text to wrap, moving the label and value onto separate lines.

<img width="282" alt="Screenshot 2024-05-07 at 14 05 27" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/6bcfb2cd-b91b-4729-b6f7-7468509e2ebf">

In most cases, the row height here is not affected, as our default row height has some accountancy for situations like this, so is quite tall.

#### 3. Flexible Row Height:

Here, we disregard the concept of the row height, and auto-fill to our content. The main issue we have then is that the row-height itself is then considered taller than it should be, and stretches other elements in that row.

<img width="279" alt="Screenshot 2024-05-07 at 14 07 28" src="https://github.com/FlowFuse/node-red-dashboard/assets/99246719/d4686051-be21-478e-9c1a-ee46565fa038">

I'm working on revamping the layout to remove the dependency of the other elements in that row, on the tallest, but it's proving a challenge.

### Steps To Reproduce

Add multiple ui-text widgets in, and resize your screen to lower than the width of the content. Particularly good example is the injection of a timestamp due to how long the number is.

### Environment

- Dashboard version:
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
@thebaldgeek - would appreciate your opinion here - but I'm swaying towards Option 2?

**Comment by thebaldgeek** [comment]
I'm leaning to option 2 as well.
While option 3 might sound attractive, I think having the high grow in unexpected ways will prove to be a problem.

In working with dash2.0 I am understating (retraining my dash1.0 brain) more and more how structured the grid layout works.
With 1.0 and zero responsiveness, the grid was used to build to the single chosen screen size.
But with 2.0 the grid is now more flexible.
Thus option 2 where the end user can chose the view of the 2x1 vs 3x1 for their requirements and it will flow better between screen sizes.

**Comment by joepavitt** [comment]
> If tables can be 'tamed' or be made to be responsive folks might find putting their text data into a table

This is a priority for me this week

**Comment by joepavitt** [comment]
Looking at https://github.com/FlowFuse/node-red-dashboard/issues/400#issue-2014056488 my concern here with (2) is that this wouldn't work too well as it'd get cut off after 1 line of text in the "value" field, but I'm really not comfortable with the unpredictability of (3) as an option.

Bringing in @Paul-Reed too as he raised the original original issue (sorry this has taken so long for me to get round to)

**Comment by Paul-Reed** [comment]
Looking at #828 I assume you went with option (2)?
...probably the best all round option.

**Comment by joepavitt** [comment]
We have @Paul-Reed - but it's easily changed. I think (2) is the next best iteration, and we'll see how it goes from there.
