### ISSUE TITLE
Why no editableList is being used

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#863]
Hi guys,

I wanted to add a feature to the code of the [ui_form.html](https://github.com/FlowFuse/node-red-dashboard/blob/main/nodes/widgets/ui_form.html#L91), but there is something I don't really understand.

The config screen contains this table:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/f66988d8-7b0e-4f35-9e40-060cef4fbe22)

It looks like an [editableList](https://nodered.org/docs/api/ui/editableList), but it isn't one.  I mean it is created from scratch using html/js/css.  

I am wondering if there is any reason why it is done that way?
For example due to some limitations of the editableList perhaps...

If there is no particular reason, is it ok if I try to create a PR to refactor it to use an editableList?

Thanks!
Bart

**Comment by joepavitt** [comment]
Migrated from Dashboard 1.0 - no more thought went into it than that. Happy to revamp it though

**Comment by bartbutenaers** [comment]
This has been implemented in pull request [1187](https://github.com/FlowFuse/node-red-dashboard/pull/1187)
