### ISSUE TITLE
Hide disabled ui nodes

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#874]
Hi guys,

I don't think a similar issue has been reported yet, and didn't find anything about it in the documentation.
BTW it is no high priority, so no pressure! 

I have currently a large amount of svg nodes in my flow, to test the features during development.  So I wanted to keep my dashboard a bit clean, by disabling these ui nodes in my flow editor:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/d18a9362-6660-4dcd-bf53-8ad8bd41127f)

So the are all disabled now in my flow editor:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/68d81d78-f01c-4602-8f51-e43e1be78236)

But they are still available in my dashboard:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/808b8494-7ba4-4985-8568-50b0191a5c23)

Not sure whether that is perhaps the intention: that a disabled ui node will appear as disabled in the dashboard?  
But I had expected it to become hidden.  

Thanks for illuminating me!
Bart

**Comment by colinl** [comment]
Does it change the symptom if you refresh the browser page and/or restart node red

**Comment by joepavitt** [comment]
It's a great point, will need to work out where that `disabled` property gets surfaced, but it's a reasonable request

**Comment by colinl** [comment]
With, for example, ui-text nodes, I find that disabling them immediately makes them disappear from the dashboard.  Is this a negative feature specifically of the svg node?

**Comment by bartbutenaers** [comment]
@colinl,
No the svg nodes were just an example, because I have a lot of them because I am currently developing the new version.  But I would use the same mechanism for all ui nodes (custom and third-party): if you disable it in the flow editor, then it shouldn't appear in the dashboard.  
So it would be nice if the dashboard could take care of it.  Because if some (third-party) node developer forgets about it, it becomes confusing if not all ui nodes behave the same way.

**Comment by colinl** [comment]
If you disable a text node for it disappear? 
The node I am developing also does disappear for me.

**Comment by bartbutenaers** [comment]
Hey Colin,
Thanks for the feedback!!
Yes indeed if I disable a radiobutton ui node, it disappears from my dashboard immediately after a deploy.
And your custom node also disappears, while my svg node doesn't...
Did you have to do anything special with your custom node to get this kind of behaviour?

**Comment by colinl** [comment]
> Did you have to do anything special with your custom node to get this kind of behaviour?

No, not intentionally at least.

**Comment by bartbutenaers** [comment]
Then you must have some kind of magic developer fingers ;-)

**Comment by bartbutenaers** [comment]
Damn, you are right.  It works already fine, even for my svg node...
I had so many svg nodes in my flows for testing, that I had the impression that they were not hidden when disabled.
So it works fine.  Although it would be nice if it was somewhere documented...
Sorry for the noise guys!
