### ISSUE TITLE
Create multiple dashboard instances

### ISSUE THREAD

**Issue by dsl400** [FlowFuse/node-red-dashboard#876]
### Description

The goal is to create multiple dashboards 

mysite/ui/main_dashboard
mysite/ui/second_dashboard

the instances should be completely independent  and the url segment should be defined by the creator

**Comment by joepavitt** [comment]
Appreciate the issue, will close though as it's a duplicate of https://github.com/FlowFuse/node-red-dashboard/issues/23

it's a very difficult topic, but something we know is of high value, so it's high up our list.
