### ISSUE TITLE
Features for Forms Node

### ISSUE THREAD

**Issue by jakobgabriel** [FlowFuse/node-red-dashboard#891]
### Description

Dear Flowfuse team, 

I was just looking into the forms node:
1. I am searching for options to make sure that a user does not send unfinished datasets.

A modal for the form that can be used as a confirmation for the user to send the data. 

2. And a dropdown within the form with or without a multiselection option might be good.

Both ideas might be benefitial feature. 

Best regards, Jakob

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
> I am searching for options to make sure that a user does not send unfinished datasets.

This should already be possible by marking the relevant fields as "required", the "Submit" button should be disabled until the relevant form fields have been submitted.

**Comment by joepavitt** [comment]
> A modal for the form that can be used as a confirmation for the user to send the data.

We have #193 which will cover a dialog-type widget. Rather than it being a config on `ui-form`, I think it would make sense to control this from within the Node-RED flow directly - but is obviously subject to us implementing #193 first

**Comment by joepavitt** [comment]
With 1. definitely implemented already, and 2 covered by https://github.com/FlowFuse/node-red-dashboard/issues/814, I'll close this out as a duplicate
