### ISSUE TITLE
Dash 2.0 template 'CSS (Single Page)' impacts entire site.

### ISSUE THREAD

**Issue by thebaldgeek** [FlowFuse/node-red-dashboard#901]
### Current Behavior

Template node that is set for 'CSS (Single Page)' impacts all dash pages.

### Expected Behavior

Expected template node 'CSS Single Page' to be honored and not propagate site wide.

### Steps To Reproduce

Place template node.
Set as follows:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/7385116/206585a2-e98e-419a-a9de-5a846125e2d0)

Deploy. Visit pages on site, note how all pages have monospace font.
Refresh each page, note correct font displayed. Go back to view the page with the monospace font, then re-visit any other page, note it now has monospace font till refreshed.

Simply viewing page with the template CSS impacts all other pages till they are reloaded.

### Environment

Dashboard version: 1.10.0
Node-RED version: 3.1.7
Node.js version: 20.11.1
Platform/OS: Windows 11
Browser: Chrome, Firefox and Edge

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Can re-produce. The challenge here is that we need to unload some CSS. If you navigate straight to a page that doesn't have the "Single Page CSS" defined for, it won't load. If you navigate to the configured page, then top any other page, the CSS persists.
