### ISSUE TITLE
Dynamic properties for button groups

### ISSUE THREAD

**Issue by postlund** [FlowFuse/node-red-dashboard#905]
### Description

Would it be possible to support `msg.options` for button groups, similarly to how it works for drop down menus?

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
Yes - will hopefully be going in, in the next few weeks. We're doing a big sweep of dynamic property updates at the moment https://github.com/FlowFuse/node-red-dashboard/issues/833

**Comment by postlund** [comment]
Ah, nice, looking forward to that! 👍 Thank you!

**Comment by postlund** [comment]
Nice! 🥇
