### ISSUE TITLE
Format of timescale axis in chart node

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#912]
### Description

Hi guys,

I added a chart to my dashboard to show some timeseries data, so I selected the timescale x-axis type:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/f4c52488-cb5b-4545-bd7a-bbec48dd7f11)

Which looks like this in the dashboard:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/b02f59ba-b73c-49e8-bc3a-ddfedcabf2d9)

Me and my familly are Dutch speaking, so the PM and AM is quite confusing for us.  
We are used that times are represented in a 24 hour format, for example `07:24` or `23:59`.  

Not sure if there is already a possibility to configure it somehow like that?  I assume not...

Thanks!
Bart

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
@bartbutenaers what's the equivalent in Dashboard 1.0 for this? Or is it 24 hr clock by default?

**Comment by bartbutenaers** [comment]
@joepavitt
To be honest I have never made a decent dashboard before...

But by looking at the config screen of the Chart ui node in dashboard D1, it looks like there were already some formatting options available:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/fe7e19e5-a01a-4e82-903a-ffb09691ada8)

When selecting "custom" it was also possible to enter any kind of format:

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/67f6b006-4adf-4d84-b008-66408f9e6b31)

**Comment by bartbutenaers** [comment]
Joe, if I you want I can try to create a PR for this one...

**Comment by joepavitt** [comment]
PRs always welcome 😊
