### ISSUE TITLE
Notification node does not send output messages anymore

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard#928]
### Current Behavior

Hi guys,

I wanted to create a new pull request for the Notification node, but that node does not send output messages anymore (both for `widget-action` and `widget-change`) when the button is clicked or at timeouts.   Some time ago it worked well, and the [ui_notification.js](https://github.com/FlowFuse/node-red-dashboard/blob/main/nodes/widgets/ui_notification.js) code hasn't been changed meanwhile.

When I click the button, the msg is being swallowed [here](https://github.com/FlowFuse/node-red-dashboard/blob/main/nodes/config/ui_base.js#L516):

![image](https://github.com/FlowFuse/node-red-dashboard/assets/14224149/290bcea8-8d61-4330-8059-6af0bf76355a)

So I assume I can fix it by applying an onAction handler in the ui-notification.js file?
But I am a bit confused why it worked before, because it looks to me that the above check is already quite some time available in the ui_base.js file...

Does anybody has an idea what could have caused this?

Thanks!!
Bart

### Expected Behavior

The Notification node sends an output message when I click the button.

### Steps To Reproduce

Click the button on the Notification node.

### Environment

- Dashboard version: 1.10.0
- Node-RED version: v3.1.3
- Node.js version: v18.19.0
- npm version: 10.2.3
- Platform/OS: Windows
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by colinl** [comment]
With 1.11.1 I am finding that it does send a message using this flow, but it sends it immediately rather then when it times out.
```
[{"id":"f62e6b2cf266dcb4","type":"ui-notification","z":"997da33a0beedade","ui":"ID-BASE-1","position":"top center","colorDefault":true,"color":"#000000","displayTime":"5","showCountdown":true,"outputs":1,"allowDismiss":true,"dismissText":"Close","raw":false,"className":"","name":"","x":640,"y":5320,"wires":[["c9ee1a6e73543d33"]]},{"id":"c9ee1a6e73543d33","type":"debug","z":"997da33a0beedade","name":"debug 2516","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":870,"y":5320,"wires":[]},{"id":"15b6545726c63e27","type":"inject","z":"997da33a0beedade","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"From Inject","payloadType":"str","x":400,"y":5320,"wires":[["f62e6b2cf266dcb4"]]},{"id":"ID-BASE-1","type":"ui-base","name":"Dashboard","path":"/dashboard","includeClientData":true,"acceptsClientConfig":["ui-control","ui-notification"]}]
```

**Comment by bartbutenaers** [comment]
Hi @colinl,
Thanks for giving it a go!
When I import your flow, I still have the same behaviour: only my input message is being forwarded directly to the output.  And when I click the button on the notification, no message is being send.
Therefore I had added a fix for this in [this](https://github.com/FlowFuse/node-red-dashboard/pull/932) PR (see point 2).

**Comment by colinl** [comment]
Yes, that is what I see. It sends it on immediately instead of sending a message when it closes.

**Comment by bartbutenaers** [comment]
This is solved by pull request [932](https://github.com/FlowFuse/node-red-dashboard/pull/932)
