### ISSUE TITLE
ui-form submit button has to be clicked twice

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#935]
### Current Behavior

when filling out a form, I cannot click the button first time

![chrome_VmEInVT5FG](https://github.com/FlowFuse/node-red-dashboard/assets/44235289/5b4bba79-de1c-4f2e-9f6f-7fd86135a79d)

### Expected Behavior

Button should be clickable 

### Steps To Reproduce

add a form with 1 text entry (required)
deploy
enter text
click button
click button

### Environment

- Dashboard version: 1.11.0
- Platform/OS: Windows
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Guessing this is linked to the fact that validation is done `onBlur`. The first click blurs and validates, which _then_ activates the submit button
