### ISSUE TITLE
Meta descriptions for each page in our documentation

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#956]
### Description

https://dev.to/paullaros/adding-dynamic-meta-tags-to-vitepress-4l99

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
@Hasmin-AC FYI - we do already have this for all nodes and config nodes in the documentation using the `description` frontmatter in our `.md` files, e.g: https://dashboard.flowfuse.com/nodes/widgets/ui-event.html

We can just include:

```md
---
description: Page description goes here
---
```

We also have this for all other `md` files I can find in the `./user` folder, and `/contributing`. They were added by @ZJvandeWeg two months ago. Which pages were missing this still that you'd seen?

**Comment by Hasmin-AC** [comment]
@joepavitt I reran the report now and yes it all does look updated now.
