### ISSUE TITLE
UI Notification - Not positioning correctly

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#960]
Add to that another issue we've had for a couple of versions (but haven't gotten around to reporting) that may or may not be related: we're using several notification popups, about half of them set to display Center on screen, the others are positioned Top Center. Every one of the Center ones, on all dashboards, appear on the bottom center of the screen.

We are using a little CSS code for styling, nothing too fancy, and disabling that makes no difference. I don't think I've seen anyone else complain about this either, although I must admit I haven't been following the new issues as closely as I perhaps should. Or there are few people using the Center setting.
When I set the popup to appear Bottom Center, it appears bottom right. The rest all appears as configured.
And as I said we've seen this for a couple of versions now (somewhere from V1.08 onwards) and I think such a very visual anomaly would be addressed within a version or 2 at most. 
If this isn't an already known issue and you can replicate it, I'd be happy to submit an issue for it of course.

_Originally posted by @SynoUser-NL in https://github.com/FlowFuse/node-red-dashboard/issues/947#issuecomment-2161379784_

**Comment by joepavitt** [comment]
Two problems here:

1. `Bottom Center` wasn't working because we had a duplicated value - our fault
2. `Center` wasn't working because of an underlying Vuetify [bug](https://github.com/vuetifyjs/vuetify/issues/19870) which has since been fixed, so should be in a new version of Vuetify soon

**Comment by SynoUser-NL** [comment]
As of DB2 version 1.12.4 this issue remains unsolved in our instances.

**Comment by joepavitt** [comment]
@SynoUser-NL which of "Bottom Center" and "Center" isn't working?

The former we fixed, the latter, the underlying bug sits with Vuetify. I can try and introduce a workaround

**Comment by joepavitt** [comment]
Although it seems Vuetify have fixed their bug, so we may just need the relevant version bump on our side.

**Comment by SynoUser-NL** [comment]
@joepavitt 
ah yes.. Positioning a notification in Center still shows on the bottom of the screen. Bottom Center we don't actively use.
Introducing a workaround would not be necessary, better to change the root cause of course.
