### ISSUE TITLE
Add css to change icon size

### ISSUE THREAD

**Issue by Paul-Reed** [FlowFuse/node-red-dashboard#965]
A[ forum post](https://discourse.nodered.org/t/icon-size-using-native-switch-dashboard-2-0/88611) asked if the icon size could be increased in the dashboard 'switch' node, and a solution was provided by @hotNipi as follows;
![hotNipi](https://github.com/FlowFuse/node-red-dashboard/assets/973580/b6088b95-87bc-46ed-aca0-213f1cce2a6b)

Font Awsome icons use a similar solution, for example `fa-coffee fa-2xs` to change icon size, and use the range `fa-2xs`, `fa-xs`, `fa-2sm`, `fa-lg`, `fa-xl`, `fa-2xs` and `fa-2xl`.  
Would it be possible to integrate the css into the dashboard core css, so that sizing would be readily available 'out of the box'.

Maybe could be also be used for https://github.com/FlowFuse/node-red-dashboard/issues/955 and also https://github.com/FlowFuse/node-red-dashboard/issues/888

**Comment by hotNipi** [comment]
`mdi-18px`,  `mdi-24px`,  `mdi-36px` and  `mdi-48px` are supported out of box.
With the CSS override mentioned above it can be customized to any size. 
I think maybe doesn't need any additions.

**Comment by Paul-Reed** [comment]
Thanks @hotNipi 
You are quite correct, and makes a big difference visually.

Before -

![cpu1](https://github.com/FlowFuse/node-red-dashboard/assets/973580/40277563-8a6d-4496-ad42-89f4516f78c9)

...and adding mdi-48px

![cpu](https://github.com/FlowFuse/node-red-dashboard/assets/973580/69bab04b-d06f-4a6c-92d8-c9fbe96743d1)

@joepavitt maybe close this issue??

**Comment by hotNipi** [comment]
Maybe just to add some words in related documents. There's more `mdi-` helper classes the one can use.

Size
`mdi-18px`  `mdi-24px`  `mdi-36px`  `mdi-48px` 

Rotate
`mdi-rotate-45`  `mdi-rotate-90`  `mdi-rotate-135`  `mdi-rotate-180`  `mdi-rotate-225` ` mdi-rotate-270`  `mdi-rotate-315`

Flip
`mdi-flip-h`  `mdi-flip-v` 

`mdi-flip-*` and `mdi-rotate-*` can't be used at the same time.

Spin
`mdi-spin`

Color
`mdi-light`  `mdi-light mdi-inactive`  `mdi-dark`  `mdi-dark mdi-inactive` 

But to say that they work everywhere it takes to at least try it before.

**Comment by joepavitt** [comment]
@hotNipi where did you find the list of utility classes? I can't find any suitable docs for `mdi`?

**Comment by hotNipi** [comment]
I do remember myself using some of those (not dashboard related) so did a bit digging
An old site here at the end of the page https://pictogrammers.github.io/@mdi/font/2.0.46/

I did look DB2 compiled index-xxxxx.css  - they all exist.

**Comment by Paul-Reed** [comment]
I also found it for version 7 - https://pictogrammers.github.io/@mdi/font/7.4.47/

**Comment by joepavitt** [comment]
Thanks both, updated the PR to point to those docs

**Comment by bartbutenaers** [comment]
Hi guys,

Do you know whether something like this can also be applied to icons in other ui nodes?
The following does _**not**_ work for me in a ui button:

![image](https://github.com/user-attachments/assets/a861391f-c642-4712-9d1e-8f208e438e3a)

I assume that is because this icon styling option is only for colors...

Thanks!!

**Comment by Paul-Reed** [comment]
@bartbutenaers Works OK if you add the size in the top icon box.

![button2](https://github.com/user-attachments/assets/4bc45a5a-6c4c-4003-baec-29f805c1282e)

![button](https://github.com/user-attachments/assets/e21a95ac-e734-4024-9f17-5a63a8732868)

**Comment by bartbutenaers** [comment]
Hi @Paul-Reed,
That was easier to fix as I had expected...
Thanks for sharing your knowledge!!!
