### ISSUE TITLE
Inputs and Default Values for a NodeRED Forms

### ISSUE THREAD

**Issue by jakobgabriel** [FlowFuse/node-red-dashboard#967]
### Description

Is it possible to set min, max and default values for fields within the nodered dashboard forms node?

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Being able to set defaults is actually next on my list, hopefully tomorrow, possibly next week. We're tracking it in https://github.com/FlowFuse/node-red-dashboard/issues/833 as a higher level update for dynamic inputs across all nodes.

For the min/max, the min/max here is only applicable to the `number` type, bit trickier, but I can look into it.

**Comment by joepavitt** [comment]
Closing to focus this into https://github.com/FlowFuse/node-red-dashboard/issues/1000
