### ISSUE TITLE
Dashboard 2 V1.11.1 - Radio Button: false emmits null instead of false

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/node-red-dashboard#970]
### Current Behavior

The radio button with 2 options ( true and false) appears to send msg.payload null instead of false.
Selecting the True option will send true (boolean).

### Expected Behavior

The radio button output message should send false (boolean) when the false option is selected.

### Steps To Reproduce

1) Make a flow with a Radio button and a Debug node.
2) In the Radio button, configure 2 options: True\true (boolean) and False\false (boolean)
3) In Dashboard, select the False option
4) In the Debug node output, the msg.payload is null instead of false (boolean)

### Environment

- Dashboard version: V1.11.1
- Browser: multiple (opera, firefox, vivaldi)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by bartbutenaers** [comment]
@SynoUser-NL,
To avoid that @joepavitt gets nuts of the large amount of issues, I have quickly implemented a solution for this one via pull request [971](https://github.com/FlowFuse/node-red-dashboard/pull/971) ;-)
Bart

**Comment by SynoUser-NL** [comment]
@bartbutenaers Thanks Bart

**Comment by bartbutenaers** [comment]
@SynoUser-NL,
@joepavitt has released version [v1.12.0](https://github.com/FlowFuse/node-red-dashboard/releases/tag/v1.12.0) today, which contains your fix.  So closing this now.

**Comment by joepavitt** [comment]
Closed by #971
