### ISSUE TITLE
HowTo: Use button from dashboard 2.0 to get an external Link.

### ISSUE THREAD

**Issue by martin2day2** [FlowFuse/node-red-dashboard#987]
### Description

Hello,

how can i setup NodeRed to add an exernal Link with an Dashboard 2.0 button.
I found the solution to setup a template genaerate an html button, but i want to use the dashboard 2.0 button.

Thank you very much
Martin

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
So, two options here, neither are which support _now_, but would be easy for us to add:

1. We add a "URL" property to the button, to support this natively on the button itself. 
2. We support, in `ui-control`, the ability to pass an external link/path to `ui-control`, which would navigate the user to that given link.

I think I'm favouring `2` as it's more generalised solution, doesn't over populate `ui-button` with options, and is consistent with a more general "node-red" user pattern, as in, some button clicks could navigate you to another page, some external, some trigger something completely different

**Comment by hotNipi** [comment]
But if the reason to not use ui_template is only that the button doesn't look like default UI_button, then it is just to apply necessary classes to it.

```<template>
    <v-btn 
        href="https://www.google.com"
        target="_blank"
        elevation="0"
        class="v-btn v-btn--block v-theme--nrdb v-btn--density-default v-btn--size-default v-btn--variant-flat"
    >
    Navigate to Google
    </v-btn>    
</template>
```
