### ISSUE TITLE
ui-text-input, multiline text area does not fill available space.

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/node-red-dashboard#989]
### Current Behavior

text area does not fill available space.

![chrome_QI22j5GcSK](https://github.com/FlowFuse/node-red-dashboard/assets/44235289/26c25e8d-20ec-4d32-bef7-ba36001aa091)

### Expected Behavior

multi-line text box should fill space

### Steps To Reproduce

add a ui-text-input and set the size height greater than 4

### Environment

- Dashboard version: 1.11.1
- Node-RED version: 3.19
- Node.js version:
- npm version:
- Platform/OS: Windows
- Browser: Chromw

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hotNipi** [comment]
CSS override to make it as it should:

```
.nrdb-ui-text-input .v-input--horizontal {
    grid-template-rows: auto 0;
}

.nrdb-ui-text-input textarea {
    height:100%;
    resize: none;
}
```
It is not solution to use directly as fix. The component has gridarea for messages, If it will be used for something - there's 0 pixels for it to live.
