### ISSUE TITLE
ui-dropdown doesnt display selected value when sent via. msg

### ISSUE THREAD

**Issue by SandeepAgarwal13** [FlowFuse/node-red-dashboard#992]
### Current Behavior

When i send msg.options with 10-15 options and also send msg.payload with desired selected value - it doesnt display the selected value always. I need to send the msg again with the same msg.payload again (with a minor delay) to ensure its reflected.

### Expected Behavior

When msg.options and msg.payload are sent on the same msg - the node should reflect the selected value.

### Steps To Reproduce

refer to discussion (https://discourse.nodered.org/t/dashboard-2-dropdown-inconsistent-behavior-on-msg-input/88712/5)

### Environment

- Dashboard version:1.11.1
- Node-RED version:3.1.9
- Node.js version:20.10
- npm version:10.2.4
- Platform/OS:Windows
- Browser:Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by bartbutenaers** [comment]
@joepavitt, I will have a look at this issue.

**Comment by joepavitt** [comment]
Thanks @bartbutenaers I suspect it's because we check `msg.payload` _before_ `msg.options`, then realise there is no valid option (as they're not set yet, so disregard it.

**Comment by bartbutenaers** [comment]
Yes indeed, that was also what I was thinking..

**Comment by joepavitt** [comment]
Closed by #1002
