### ISSUE TITLE
ui text box - when user clears the data - no event gets generated.

### ISSUE THREAD

**Issue by SandeepAgarwal13** [FlowFuse/node-red-dashboard#996]
### Current Behavior

I write something in ui_text box - once i leave / release focus - event gets generated - with payload of what user typed.
I deleted the data in ui_text box - no event gets geenrated. So user has no way to know the new content of ui_text

### Expected Behavior

I write something in ui_text box - once i leave / release focus - event gets generated - with payload of what user typed.
I deleted the data in ui_text box - event will empty payload (undefined/empty/null - any is ok) should get generated. 

### Environment

- Dashboard version:1.11
- Node-RED version:3.1.9
- Node.js version: 20.10
- npm version:10.2.3
- Platform/OS:Windows
- Browser:Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
If I recall, @colinl had opinions on this at some point, as we implemented it as you've described. I'm open to a change to still emit if no value though, especially since we've added control over _when_ the events are emitted (on blur, etc), the user has more control

**Comment by SandeepAgarwal13** [comment]
Once user add a value and event got generated - it would get used in a flow.
Then user decided to delete this value - the backend editor would have no ways to know that now the value is empty. 
We may not be able to do validations that user did not input a value - as editor has event to work on.
